export type September4BlogPost={slug:string;title:string;excerpt:string;minutes:number;focus:string;question:string;published:'2026-09-04';modified:'2026-09-04';body:string[]};

const build=(focus:string,trigger:string,scenario:string,fields:string,boundary:string,measure:string,owner:string)=>[
 `${focus} starts with a trigger that a representative can recognize during live customer work: ${trigger}. Put that trigger beside the covered queue, service window, approved source, and ${owner}. An unwritten convention will fracture across shifts. When the rule changes, record the reason and effective time so an older habit does not quietly survive beside the new instruction.`,
 `${scenario} The representative should separate what the customer said from what the system proves, complete the permitted check, and stop when the next action needs authority they do not hold. A warm response matters, but it cannot replace an accurate status. Explain what is known, what happens next, and who owns the decision without inventing an outcome or deadline.`,
 `A decision-ready record carries ${fields}. Every field should help the next person act. Copying an entire conversation can hide the current question and spread information the receiver does not need; a one-word status leaves too much to reconstruct. Preserve material wording, the source checked, the due point with its time zone, and any uncertainty that remains.`,
 `The operating boundary is clear: ${boundary}. Keep that sentence next to the normal steps. If the authorized owner is offline, use the approved interim response and owned follow-up. A Philippines night shift may cover intake while a client specialist is unavailable. Intake coverage does not create authority for restricted decisions.`,
 `A ticket assignment or message proves movement, not acceptance. The receiver needs usable context, the relevant access, and an explicit acceptance state. Set an acknowledgement deadline and a backup route. If nobody accepts the case, keep the gap visible rather than burying it under a generic pending label.`,
 `Review ${measure}, then read the records behind the counts. Fast closure can be wrong, while a careful stop may protect the customer when identity, privacy, payment, or policy authority is unclear. Separate ordinary cases, exceptions, exclusions, and missing evidence so managers can see which part of the process needs repair.`,
 `Test one ordinary request, one ambiguous request, one handoff, and one unavailable-owner case. Ask the sender and receiver to name the next action using only the record. If they disagree, repair the missing field or conflicting instruction before adding coaching. Repeat the same cases after changing one control.`,
 `${owner} should close the review with one decision, one action owner, and a review date. Record what the sample showed and what it could not establish. A dependable ${focus.toLowerCase()} routine will not remove every exception; it gives representatives a safe choice, protects customer promises, and leaves evidence managers can use.`,
];

const specs=[
 ['offshore-call-center-vip-label-governance','Offshore call center VIP label governance without queue distortion','Define who qualifies for priority handling, what the label changes, and when it expires.','VIP label governance','a priority label has a named source, scope, permitted benefit, and expiry','A repeat buyer is marked VIP, but that label provides no authority for a refund exception.','label source, effective period, permitted service change, ordinary promise, decision owner, and removal reason','priority may change sequence or routing but never bypasses verification, privacy, payment, or approval controls','label age, inconsistent treatment, removed labels, missed ordinary promises, and exception requests','the customer-experience policy owner'],
 ['call-center-voicemail-callback-consent','Call center voicemail callback consent for safe follow-up','Plan voicemail and callback steps around purpose, channel permission, and identity risk.','Voicemail callback consent','the contact purpose and recorded channel permission are known','A support callback reaches a shared voicemail with no permission to leave account details.','callback purpose, number source, permission, attempt time, safe message, next attempt, and owner','representatives leave only approved minimal wording and never switch channels without permission','voicemail outcomes, authorized retries, withdrawn permission, repeat calls, and disclosures','the contact-permission owner'],
 ['philippines-call-center-local-holiday-handoff','Philippines call center local-holiday handoffs across client queues','Keep promises owned when Philippine and client holidays differ.','Local-holiday handoff','staffed queues and reachable decision authority are checked separately','A US queue stays open during a Philippine holiday with a smaller Manila shift and two hours of finance coverage.','queue, staffing window, open promises, restricted decisions, approver hours, backup, and customer wording','the offshore team continues approved routine work but does not inherit offline client authority','unaccepted handoffs, holiday arrivals, backup use, changed promises, and carryover','the cross-border coverage owner'],
 ['offshore-call-center-misroute-return-rule','Offshore call center misroute return rules that preserve customer context','Return incorrectly routed work without forcing a restart.','Misroute return rule','a misroute has a reason, retained context, destination, and acknowledgement deadline','A warranty question reaches billing, although billing can see the verified order and stated need.','verified need, route, completed checks, safe context, destination, promise, and acceptance','a queue may return work for a specific missing requirement but cannot erase the original promise','misroute reasons, bounce count, acceptance time, repeated explanation, and final ownership','the routing-governance owner'],
 ['call-center-customer-request-withdrawal','Call center customer request withdrawal without accidental closure','Confirm what the customer withdrew and preserve remaining obligations.','Customer request withdrawal','the exact request being withdrawn is identified','A caller cancels a delivery inquiry but still expects a promised billing-correction update.','customer wording, requests in scope, linked commitments, completed actions, remaining obligations, and confirmation','representatives close only withdrawn work and retain unrelated promises or required holds','withdrawal reasons, reopened items, retained promises, incorrect closures, and confirmation','the case-closure owner'],
 ['offshore-call-center-broken-link-escalation','Offshore call center broken knowledge-link escalation at the point of work','Give representatives a safe route when approved guidance will not open.','Broken knowledge-link escalation','an inaccessible source is recorded as an operational event','A return-policy link fails during chat while an older saved response remains searchable.','question, failed URL, error time, approved alternate, interim step, affected queue, and owner','only a confirmed alternate may be used; uncertain versions go to the named owner','failed links, affected contacts, alternate use, corrections, repair time, and recurrence','the knowledge-platform owner'],
 ['call-center-promised-email-proof','Call center promised-email proof beyond a sent status','Verify that promised follow-up uses approved content and reaches the right address.','Promised-email proof','the exact promise, permitted address, and approved template are visible','An agent promises setup instructions, but automation uses an outdated address and closes the case.','promise, address source, template version, send result, delivery signal, failure route, and owner','agents verify permitted details and do not expose account information in an unsafe retry','promised messages, bounces, corrections, delivery, repeat contact, and premature closure','the outbound-communications owner'],
 ['philippines-call-center-accent-clarification','Philippines call center accent clarification without customer friction','Use respectful confirmation when a material spoken detail is unclear.','Accent clarification','clarification targets a fact needed for lookup, routing, quantity, or commitment','On a noisy call, an agent cannot tell whether the customer said fifteen or fifty.','material detail, neutral clarification, confirmed value, correction, downstream use, and uncertainty','agents confirm decision-driving facts without guessing or turning accent into a quality label','corrected entries, lookup failures, repeat explanations, misroutes, and task outcomes','the interaction-quality owner'],
 ['offshore-call-center-supervisor-chat-queue','Offshore call center supervisor chat queues for traceable decisions','Move urgent questions out of private messages and into an owned route.','Supervisor chat queue','a question includes its category, urgency basis, source context, and decision owner','An agent privately messages three supervisors about an exception and gets two different answers.','customer question, source checked, decision requested, due point, responder, version, and acknowledgement','frontline agents request a decision but cannot choose the most convenient conflicting answer','response time, duplicate questions, conflicting answers, corrections, and source updates','the supervisor-coverage owner'],
 ['call-center-silent-transfer-recovery','Call center silent-transfer recovery when the receiving line drops','Recover failed transfers without losing context.','Silent-transfer recovery','a failed live transfer creates a visible recovery action','A verified technical-support caller goes silent when the specialist line disconnects.','transfer start, verification, need, failure signal, callback permission, retry owner, and due time','agents preserve permitted context and use the approved reconnection route','dropped transfers, reconnect time, repeated explanation, abandoned recovery, and acceptance','the transfer-operations owner'],
 ['offshore-call-center-work-note-correction','Offshore call center work-note corrections with an audit trail','Correct inaccurate notes while preserving cause and downstream impact.','Work-note correction','a material correction has attribution, time, reason, and an impact check','A note says email contact was approved, but review shows permission covered only a return call.','original statement, corrected fact, evidence, affected actions, author, notification owner, and time','agents never silently overwrite material history or reuse disputed permission','corrected notes, downstream notices, repeated errors, customer impact, and source repairs','the records-governance owner'],
 ['call-center-end-of-shift-open-chat','Call center end-of-shift open-chat handoffs before sign-out','Keep live chats owned when a scheduled shift ends.','End-of-shift open-chat handoff','a chat remains owned until accepted or safely closed under the approved rule','A billing chat waits for a specialist answer as the Manila agent reaches shift end.','need, verification, last message, dependency, next update, boundary, and accepting owner','agents cannot close solely for shift time or continue outside approved staffing and access','open chats, acceptance delay, wait, dropped sessions, overtime exceptions, and repeats','the real-time queue owner'],
] as const;

export const september4BlogPosts:September4BlogPost[]=specs.map(([slug,title,excerpt,focus,trigger,scenario,fields,boundary,measure,owner])=>({slug,title,excerpt,minutes:10,focus,question:`How should an offshore call center manage ${focus.toLowerCase()}?`,published:'2026-09-04',modified:'2026-09-04',body:build(focus,trigger,scenario,fields,boundary,measure,owner)}));
