export type August31BlogPost = { slug:string; title:string; excerpt:string; minutes:number; focus:string; question:string; published:'2026-08-31'; modified:'2026-08-31'; body:string[] };

const buildBody = (focus:string, boundary:string, scenario:string, evidence:string, owner:string) => [
  `${focus} works best when the operating rule is visible before a customer reaches the queue. For this workflow, ${boundary}. Write that boundary beside the supported call reasons, systems, and coverage window. Representatives then know what they may complete, what must be recorded, and when the work belongs with ${owner}. A clear boundary also gives supervisors an observable standard for training and review instead of asking them to judge a vague promise after the fact.`,
  `Map the workflow from the customer’s point of view. Begin with the signal that starts the work, confirm the minimum facts needed for the approved action, and state the next step in plain language. Consider ${scenario}. The representative should not have to infer urgency, authority, or customer permission from an incomplete note. The queue guide should name the safe question, the permitted action, and the stop rule for missing or conflicting information.`,
  `Ownership must survive every transfer and shift boundary. A useful record identifies the customer’s stated need, checks already completed, action taken, unresolved dependency, due point, and next accountable person. “Sent to another team” is activity, not accepted ownership. Require the receiving owner to accept the item or return it with a specific missing field while there is still time to protect the customer promise.`,
  `Test the design with ordinary, ambiguous, and exception cases before broad rollout. Include a case where the normal owner is unavailable and one where the customer changes the request. Review ${evidence}, but read the source records behind the count. A fast result can conceal a weak handoff, while a careful escalation may be the correct outcome when the requested action exceeds the representative’s authority.`,
  `Keep access and customer information proportional to the task. Representatives need enough context to continue the approved work, not unrestricted access to every prior interaction. Record customer preferences only when they change the permitted next step. If identity, privacy, payment, legal, or policy questions arise, preserve the minimum operational facts and route the decision to ${owner} rather than improvising an exception.`,
  `Supervisors should review a small, defined sample close to the event. Score observable behaviors such as correct routing, accurate notes, promise clarity, accepted ownership, and safe escalation. Separate an individual coaching need from a broken source, unavailable approver, unclear field, or system defect. Publish the reason for any workflow change so later reviewers can distinguish new behavior from old instructions.`,
  `Use a controlled pilot to learn without moving every queue at once. Choose one request type and coverage period, brief the people who receive exceptions, and agree on a pause condition. Pause expansion when records lack owners, promises repeatedly pass their due points, or reviewers cannot reproduce the expected decision. After one correction, repeat the same sample rather than changing several controls together.`,
  `A durable ${focus.toLowerCase()} routine closes the loop with the process owner. Report the observed pattern, representative examples, exclusions, and the decision needed; avoid turning one rate into a provider-wide claim. Assign the next action and review date. The goal is a queue where customers receive an honest next step and managers can trace why the work was completed, handed off, or stopped.`,
];

const specs = [
  ['offshore-call-center-escalation-acknowledgement','Offshore call center escalation acknowledgement: proving an owner received the case','Design an acknowledgement rule that distinguishes a sent escalation from accepted work with a due point and accountable owner.','Escalation acknowledgement','a case is not accepted until a named receiving owner confirms the request and next review point','a billing exception reaches a manager near the end of the offshore shift','acceptance delay, returned escalations, overdue promises, and repeated customer explanations','the authorized escalation owner'],
  ['call-center-callback-attempt-record','Call center callback attempt records: what each contact should prove','Create callback records that preserve the promised window, permitted channel, attempt result, and next action without vague disposition codes.','Callback attempt records','each attempt must link to the original promise, approved contact method, result, and remaining obligation','a customer requests an afternoon phone call but the first attempt reaches voicemail','attempt timing, successful connection, repeat attempts, closure reasons, and customer recontact','the callback queue owner'],
  ['philippines-call-center-time-zone-labels','Philippines call center time-zone labels for safer customer promises','Use explicit time-zone fields and readback rules so offshore teams do not turn local hours into missed customer commitments.','Time-zone labels','every time-bound promise must identify the customer-facing date, time, and time-zone convention','a Manila-based representative schedules a callback for a customer whose account uses US Eastern Time','time corrections, missed windows, reschedules, and disputes about promised times','the scheduling policy owner'],
  ['offshore-call-center-knowledge-search-fallback','Offshore call center knowledge search fallback when no answer appears','Give representatives a practical stop, search, and escalation sequence when the approved knowledge source does not answer the request.','Knowledge search fallback','an unsuccessful search is a routing signal and never permission to invent an answer','two similar articles appear, but neither covers the customer’s product version','failed searches, escalations, later corrections, and repeat contacts','the authorized knowledge owner'],
  ['call-center-disposition-change-governance','Call center disposition change governance for cleaner reporting','Control additions and edits to call disposition codes with definitions, examples, owners, and a migration plan.','Disposition change governance','a new code must support a named operational decision and remain distinguishable from outcome and escalation','supervisors propose a broad “resolved” code that combines several different customer outcomes','coding agreement, use of catch-all codes, reopened work, and reporting breaks','the reporting owner'],
  ['offshore-call-center-customer-update-cadence','Offshore call center customer update cadence for unresolved work','Set honest update intervals for pending customer work without promising a resolution the representative cannot control.','Customer update cadence','an update promise covers when the customer will hear from the team, not when an external dependency will be resolved','a support case waits on a client specialist who has not confirmed a completion time','kept update promises, dependency age, repeat contacts, and unexplained closures','the case owner'],
  ['call-center-queue-reopening-rules','Call center queue reopening rules that preserve prior context','Define when closed work should reopen, when a new case is appropriate, and how the prior decision remains visible.','Queue reopening rules','reopening requires a recorded trigger, link to prior work, and current accountable owner','a customer supplies missing evidence after a case was closed for no response','reopen reasons, duplicated cases, repeated verification, and final outcomes','the queue governance owner'],
  ['philippines-call-center-shift-overlap-agenda','Philippines call center shift overlap agenda built around open work','Replace status-heavy overlap meetings with a concise review of due promises, exceptions, dependencies, and accepted ownership.','Shift overlap agendas','the agenda should prioritize customer work crossing the shift rather than narrating completed activity','an urgent callback and a pending manager approval both approach their due points during overlap','acceptance time, overdue cross-shift work, returned handoffs, and repeated explanations','the incoming shift supervisor'],
  ['offshore-call-center-complaint-update-boundaries','Offshore call center complaint updates without unsupported remedies','Help representatives acknowledge complaints, preserve evidence, and communicate the next review without deciding an unapproved remedy.','Complaint update boundaries','acknowledgement, investigation, remedy approval, and customer closure are separate events','a customer requests compensation that the offshore queue is not authorized to approve','acknowledgement timing, remedy ownership, kept promises, and repeat complaints','the complaint decision owner'],
  ['call-center-outage-message-control','Call center outage message control during changing incidents','Keep customer-facing outage language current with source ownership, effective times, version control, and a fallback when facts change.','Outage message control','representatives may state only the current approved facts, next update point, and permitted customer action','an incident estimate changes while agents still have an older response open in a template','old-version use, unsupported estimates, corrections, escalations, and customer recontact','the incident communications owner'],
  ['offshore-call-center-verification-retry-limits','Offshore call center verification retry limits and safe alternatives','Set bounded verification attempts, disclosure limits, and approved alternatives without weakening account protection.','Verification retry limits','failed verification must limit disclosure and lead to a defined safe route rather than improvised extra questions','a legitimate caller cannot access the usual verification factor and asks the agent to make an exception','repeat attempts, abandonment, safe alternative completion, and exception requests','the security policy owner'],
  ['call-center-quality-sample-exclusions','Call center quality sample exclusions: keeping review results honest','Document which interactions are excluded from a quality sample, why they are excluded, and who reviews the resulting blind spots.','Quality sample exclusions','every exclusion needs a reason, owner, and impact note so the reported sample is not mistaken for the whole queue','unrecorded calls and specialist transfers disappear from an otherwise routine quality review','exclusion rates, missing channels, reviewer agreement, and uncovered customer risks','the quality program owner'],
] as const;

export const august31BlogPosts: August31BlogPost[] = specs.map(([slug,title,excerpt,focus,boundary,scenario,evidence,owner]) => ({
  slug,title,excerpt,minutes:10,focus,question:`How should an offshore call center manage ${focus.toLowerCase()}?`,published:'2026-08-31',modified:'2026-08-31',body:buildBody(focus,boundary,scenario,evidence,owner),
}));
