type Aug18Post = { slug:string; title:string; excerpt:string; minutes:number; focus:string; question:string; published:'2026-08-18'; body:string[] };

const paragraph = (topic:string, decision:string, example:string, measure:string) => [
  `A useful ${topic} begins with a decision that the call center can actually observe. Before an offshore representative receives the work, write down ${decision}. This is not a promise about every customer or every queue; it is a boundary for one operating situation. The manager should be able to point to the call reason, the evidence available in the approved system, the action the representative may take, and the point where authority ends. That specificity keeps a broad service description from becoming an improvised call flow. It also gives training, quality review, and daily reporting the same definition of good work.`,
  `Design the workflow around the customer’s next need rather than around an internal department chart. Start with the opening signal, then name the minimum verification, the approved answer or action, and the record that must be left behind. If the request is unclear, the safe path is part of the design, not an exception to be explained later. For ${example}, the representative should know what to ask, what not to infer, and who owns the next decision. Keep sensitive changes, refunds, legal interpretations, and unapproved commitments with the designated manager unless a written rule says otherwise.`,
  `The handoff deserves its own test. A message that says “please review” does not identify an owner, due point, customer expectation, or unresolved risk. Require a concise record containing the reason for contact, verified context, action already taken, promised follow-up, and next accountable person. Review that record from the receiver’s perspective: could someone continue the work without asking the customer to repeat the story? If not, improve the fields or script before blaming the agent. A clean handoff is especially important when shifts, queues, or offshore teams change during the customer journey.`,
  `Use a small sample to check whether the process works under ordinary pressure. Include a straightforward request, an ambiguous request, and a case that reaches the authority boundary. Score observable behavior: correct opening, accurate verification, listening, approved wording, complete notes, correct disposition, and escalation quality. Do not turn a single miss into a sweeping claim about a person or provider. Look for the process cause first: missing knowledge, confusing routing, excessive access, a script that hides the stop rule, or a manager who is unavailable when the queue needs a decision.`,
  `Choose measures that reveal customer and operator consequences. In addition to volume or completion, inspect repeat contacts, transfers, overdue callbacks, corrections, unresolved records, complaint themes, and sampled call quality. The right ${measure} measure is not necessarily a target to maximize; it is evidence for a conversation about what should change. If speed rises while repeat contacts or corrections rise, the workflow is not healthier. If escalations fall because agents stop recording them, the apparent improvement is misleading. Pair counts with a few reviewed examples and the owner’s interpretation.`,
  `Roll out the change in a narrow queue or call reason first. Give representatives examples of normal work and boundary cases, let them practice the record fields, and have a supervisor review early calls close to the event. Publish a short change note when the script, routing, or access rule changes. Set a review date and a stop condition: pause expansion if the team cannot verify customers consistently, if promised follow-ups age without owners, or if managers cannot explain the exceptions. A controlled launch protects both the customer and the learning needed for the next queue.`,
  `Make the rule legible at the moment of work. A representative should not have to search several documents to discover whether a request is in scope, which field is required, or who receives an exception. Put the short version in the queue guide, link the fuller explanation for supervisors, and retire superseded examples. For ${topic}, practice the awkward middle cases because they expose hidden assumptions: incomplete information, a customer who changes the request, a system that is temporarily unavailable, or a handoff that arrives without enough context. The manager’s review should ask what made the safe action easy or difficult.`,
  `Close the loop with the people who own the surrounding process. A queue may reveal that an IVR label is misleading, that a knowledge article is stale, that a calendar rule creates avoidable callbacks, or that an escalation route has no reachable decision maker. Record the observation separately from the customer’s personal information and assign a process owner, due point, and review question. The purpose of ${topic} is not to create another isolated checklist. It is to make the call center easier to understand, safer to operate, and more honest about what the offshore team can complete in one interaction.`,
];

const specs = [
  ['call-center-ivr-to-agent-handoff','Call center IVR to agent handoff: preserving intent after the menu','Make the transfer from an automated menu to an offshore call center representative useful by carrying intent, verification state, and the next question into the live conversation.','IVR-to-agent handoffs','What should a call center IVR-to-agent handoff preserve?','the menu choice is a helpful signal, not proof of what the customer needs','a caller selects billing help but explains a delivery problem once connected','repeat contacts and transfers'],
  ['offshore-call-center-queue-admission-rules','Offshore call center queue admission rules for cleaner work','Decide which calls belong in an offshore queue, which need preparation, and which should go directly to a manager or specialist.','queue admission rules','How should an offshore call center decide which calls enter a queue?','queue admission is an explicit scope decision before staffing begins','a request arrives with missing verification or an unsupported account change','misroutes and avoidable escalations'],
  ['call-center-silent-call-protocol','Call center silent call protocol: a respectful recovery flow','Give representatives a clear, humane response to silence, dropped audio, and uncertain connection quality without pretending the conversation succeeded.','silent call protocols','What should a call center silent-call protocol include?','silence is a communication condition to recover, document, or close safely','an agent cannot confirm whether the caller heard an important instruction','reconnects and repeat contacts'],
  ['philippines-call-center-holiday-coverage','Philippines call center holiday coverage: a planning conversation','Plan holiday coverage through queue priority, approved hours, backup ownership, and customer communication rather than an unsupported promise of constant availability.','holiday coverage','How should a Philippines call center plan holiday coverage?','holiday coverage is a written operating choice tied to actual queues and owners','a scheduled closure collides with a callback promise and an urgent queue','missed promises and aging work'],
  ['call-center-knowledge-gap-escalation','Call center knowledge-gap escalation when an answer is missing','Create a stop-and-escalate path for questions that the knowledge base does not answer, keeping uncertainty visible and customers protected.','knowledge-gap escalation','How should a call center escalate a knowledge gap?','an absent article is a control signal, not permission to improvise','a representative finds two conflicting instructions for the same request','unsupported answers and repeat contacts'],
  ['offshore-call-center-voicemail-triage','Offshore call center voicemail triage that preserves urgency','Sort voicemail by stated need, risk, due point, and ownership so an offshore team can prepare callbacks without guessing priority.','voicemail triage','How should an offshore call center triage voicemail?','voicemail triage converts incomplete information into a safe next action','a message mentions a deadline but does not identify the account or requested remedy','overdue callbacks and misclassified urgency'],
  ['call-center-transfer-warmth-check','Call center transfer checks for a better customer experience','Define what a representative must explain and record before transferring a customer, including the reason, context, and receiving owner.','transfer checks','What should a call center check before transferring a customer?','a transfer is a handoff with a customer-visible explanation','the receiving queue cannot see the first representative’s notes','blind transfers and repeated explanations'],
  ['philippines-call-center-supervisor-span','Philippines call center supervisor span: a practical review lens','Evaluate supervisor capacity through queue risk, coaching obligations, exception volume, and decision availability instead of a universal ratio.','supervisor capacity','How should a Philippines call center assess supervisor capacity?','supervisor capacity depends on the complexity and volatility of the queue','one supervisor owns several queues with different scripts and escalation rules','unreviewed exceptions and delayed coaching'],
  ['call-center-customer-preference-recording','Call center customer preference recording: useful and bounded notes','Record communication preferences only when they support the approved customer journey, with clear fields, ownership, and limits on interpretation.','customer preference records','What should a call center customer preference record contain?','a preference is a customer-provided instruction, not an invitation to infer sensitive traits','a caller asks for a particular callback window and channel','missed preferences and inappropriate notes'],
  ['offshore-call-center-weekend-queue-design','Offshore call center weekend queue design','Build a weekend queue around actual call reasons, reduced authority, escalation availability, and Monday continuity.','weekend queue design','How should an offshore call center design a weekend queue?','weekend operations need explicit limits and a Monday receiving plan','a Saturday support request cannot be resolved until a weekday manager approves it','Monday rework and unresolved weekend records'],
  ['call-center-call-backlog-aging-rules','Call center call backlog aging rules that trigger action','Use aging bands and owner actions to prevent an old call from becoming invisible inside a large backlog.','backlog aging','How should a call center use backlog aging rules?','age is a routing signal that should change the next action','a callback is still open after the customer’s promised time','stale work and repeat contacts'],
  ['philippines-call-center-coaching-calibration','Philippines call center coaching calibration for consistent scores','Align supervisors on how to interpret the scorecard so coaching reflects observable call behavior rather than personal preference.','coaching calibration','How should a Philippines call center calibrate coaching scores?','calibration compares evidence and expected behavior before judging performance','two reviewers disagree about whether a handoff note was complete','score variance and repeated coaching'],
  ['call-center-customer-consent-handoff','Call center customer consent handoff: making permission visible','Keep customer permission and communication boundaries visible when work moves between representatives, queues, or follow-up channels.','consent handoffs','What should a call center customer consent handoff record?','permission must be tied to a stated action and approved channel','a customer agrees to a callback but not to a different type of message','unwanted contact and unclear follow-up'],
  ['offshore-call-center-peak-volume-trigger','Offshore call center peak volume triggers and response actions','Define the evidence that moves an offshore queue into overflow, callback, or manager-review mode during a volume spike.','peak volume triggers','How should an offshore call center respond to peak volume?','a trigger is useful only when it has a named response and owner','incoming volume rises while the normal callback promise is still open','abandoned work and opaque overflow'],
  ['call-center-agent-readback-standard','Call center agent readback standard for important details','Use concise readback to confirm names, dates, addresses, appointment details, and next steps without turning every call into a script recital.','readback standards','When should a call center agent use readback?','readback confirms material details before the record or promise is finalized','an appointment time is repeated across time zones and service options','corrections and missed appointments'],
  ['philippines-call-center-remote-work-checks','Philippines call center remote-work checks for queue readiness','Assess remote-work readiness through approved space, connectivity, access, privacy, backup, and supervisor contact rules.','remote-work readiness','What should a Philippines call center remote-work check cover?','readiness is evidence that approved work can continue safely in the stated setup','a representative loses connectivity during a customer verification step','disconnected calls and access exceptions'],
  ['call-center-customer-recontact-reason-codes','Call center customer recontact reason codes that teach the queue','Design recontact codes that explain why a customer returned, what failed, and which process owner should investigate.','recontact reason codes','How should a call center code customer recontacts?','a recontact code should point to a fixable operational cause','the customer calls again because a promised update never arrived','repeat-call patterns and corrective actions'],
  ['offshore-call-center-script-change-control','Offshore call center script change control','Manage script changes with an owner, version, effective point, training note, and rollback path so representatives do not mix old and new instructions.','script change control','How should an offshore call center control script changes?','a script is an operating control that needs version awareness','a new refund phrase is published while old printed guidance remains in use','old-version usage and avoidable corrections'],
  ['call-center-appointment-no-show-followup','Call center appointment no-show follow-up rules','Separate a missed appointment, a cancellation, an unreachable customer, and an internal scheduling error before assigning follow-up.','no-show follow-up','How should a call center handle appointment no-show follow-up?','a no-show label needs evidence and a clear next action','a customer says they never received the confirmation message','rebookings and disputed reminders'],
  ['philippines-call-center-quality-exception-log','Philippines call center quality exception log for repeat problems','Turn serious or recurring call-quality exceptions into owned actions without using the log as a substitute for coaching or process repair.','quality exception logs','What belongs in a Philippines call center quality exception log?','an exception log connects evidence, risk, owner, and closure decision','the same verification miss appears across several representatives','repeat exceptions and overdue fixes'],
  ['call-center-callback-time-window-rules','Call center callback time-window rules customers can trust','Translate customer availability into an owned callback window, with time-zone clarity, retry limits, and a safe close when contact fails.','callback time windows','How should a call center define callback time windows?','a callback promise is a bounded commitment rather than a vague intention','a customer gives a local-time window while the offshore queue works another schedule','late callbacks and failed contact'],
  ['offshore-call-center-manager-availability-map','Offshore call center manager availability map','Map when managers can approve exceptions, answer escalations, and receive urgent records so an offshore queue knows when to stop safely.','manager availability','How should an offshore call center map manager availability?','authority is useful only when its availability is visible to the queue','a representative reaches a restricted request outside the approving manager’s hours','held work and unauthorized decisions'],
] as const;

export const augustEighteenBlogPosts: Aug18Post[] = specs.map(([slug,title,excerpt,focus,question,decision,example,measure]) => ({ slug,title,excerpt,minutes:10,focus,question,published:'2026-08-18',body:paragraph(focus,decision,example,measure) }));
