export type September2BlogPost = { slug:string; title:string; excerpt:string; minutes:number; focus:string; question:string; published:'2026-09-02'; modified:'2026-09-02'; body:string[] };

const buildBody = (focus:string, rule:string, example:string, proof:string, owner:string) => [
  `${focus} should begin with a written operating definition, not an informal expectation. The working rule for this routine is that ${rule}. Put the definition beside the queue scope, permitted actions, and coverage window so a Philippines-based representative can recognize the event before acting. The definition should also name ${owner} as the person who resolves conflicts or approves a change.`,
  `Walk through the routine from the customer signal to the next accountable action. In one practical case, ${example}. The representative needs a clear trigger, the minimum facts required, a safe action, and a stop condition. If any required fact is missing, the record should say what is missing and where the work goes instead of hiding uncertainty in a broad status.`,
  `Design the record for the person who receives the work next. Capture the request, source, relevant time, action already taken, unresolved dependency, customer-facing promise, and named next owner. A queue movement or message sent is not proof of accepted ownership. Require acknowledgement when responsibility changes, especially when work crosses a shift or client-side decision window.`,
  `Use ${proof} to review the routine, but inspect the underlying records before drawing a conclusion. A fast completion can still be inaccurate, while a careful stop can be correct when identity, privacy, payment, legal, or policy authority is uncertain. Report routine cases, exceptions, exclusions, and missing evidence separately so managers can see what the result actually covers.`,
  `Protect customer information by limiting access and notes to what the approved next step requires. Do not copy unrelated history into handoff, calibration, or coaching records. If the request moves beyond the documented authority boundary, preserve the operational context and route the decision to ${owner}. The offshore team should never create an exception merely to keep a case moving.`,
  `Supervisors can test ${focus.toLowerCase()} with a small mixed sample: an ordinary case, an ambiguous case, a transfer, and an exception. Score observable actions such as correct identification, accurate notes, safe routing, promise clarity, and accepted ownership. Separate coaching issues from broken sources, unavailable approvers, unclear fields, access problems, and system defects.`,
  `Pilot one change at a time and keep the sample definition stable. Agree on a pause condition before launch, such as repeated missing owners, expired customer promises, unsupported decisions, or records that reviewers cannot reconstruct. After correcting the suspected control, repeat the same scenarios and compare the source records rather than relying only on a summary rate.`,
  `A dependable ${focus.toLowerCase()} routine ends with a documented decision, action owner, and review date. State what the sample showed, what it could not show, and which repair will be tested next. This creates a daily management habit that protects customer promises without turning a limited observation into a provider-wide performance claim.`,
];

const specs = [
  ['offshore-call-center-queue-entry-criteria','Offshore call center queue entry criteria for correctly routed customer work','Build a daily register that identifies the external decision, due point, customer update, and accountable owner for every blocked case.','Queue entry criteria','a blocked case remains active until its dependency, due point, update commitment, and owner are visible','a replacement request waits for warehouse confirmation while the next customer update is due that afternoon','dependency age, kept update commitments, ownership acceptance, and closure evidence','the client-side dependency owner'],
  ['call-center-urgent-request-triage','Call center urgent request triage with explicit evidence and authority','Define the facts that should travel with a transfer while avoiding unnecessary customer data and unsupported conclusions.','Urgent request triage','each transfer carries the verified need, completed checks, permitted disclosure, unresolved question, and receiving owner','a billing question moves to a specialist after identity checks and a documented account-status lookup','repeated questions, returned transfers, acceptance time, and missing-field reasons','the receiving queue owner'],
  ['philippines-call-center-weather-disruption-readiness','Philippines call center weather disruption readiness for customer queues','Prepare weather disruption coverage around named queues, available approvers, customer promises, backup paths, and explicit stop conditions.','Weather disruption readiness','disruption staffing is approved only when queue scope, decision coverage, escalation availability, and customer messaging align','a severe local weather changes supervisor availability while a US customer queue remains open','coverage gaps, unanswered escalations, promise changes, and backup activation','the coverage plan owner'],
  ['offshore-call-center-customer-language-preference-record','Offshore call center customer language preference records for consistent service','Record channel and contact permission in a form that is specific, current, limited, and usable by the next representative.','Customer language preference records','a language preference record identifies the permitted contact purpose, channel, scope, source, and effective time','a customer permits an order update by text but not general marketing messages','channel mismatches, permission corrections, customer objections, and successful approved contact','the privacy or communications owner'],
  ['call-center-abandoned-call-review-path','Call center abandoned call review paths for accountable follow-up','Give reviewers a defined alternative when a recording is unavailable without pretending the interaction was fully observed.','Abandoned call review paths','an abandoned call is logged as a coverage limitation and routed for an approved evidence review','a sampled call has CRM notes and timestamps but the audio file is absent','abandoned-call evidence, exclusion reasons, substitute evidence, and recurring system gaps','the quality and recording owner'],
  ['offshore-call-center-script-exception-routing','Offshore call center script exception routing before an improvised answer','Use effective dates, source ownership, and a short pre-contact check to prevent representatives from sending retired language.','Script exception routing','customer-facing scripts are usable only when their version, effective period, source owner, and exception route are clear','a policy update replaces a return message while an older saved reply remains accessible','retired-script use, corrections, customer recontact, and source conflicts','the approved content owner'],
  ['call-center-repeat-caller-context-review','Call center repeat caller context review before another handoff','Set bounded attempts, approved channels, waiting periods, and closure evidence when a customer cannot be reached.','Repeat caller context review','an repeat customer contact preserves the original promise and leads to a defined retry, alternate route, or justified closure','a scheduled callback reaches voicemail and the customer has approved email for service updates','attempt timing, channel authority, successful contact, repeat demand, and closure reasons','the callback policy owner'],
  ['philippines-call-center-client-calendar-alignment','Philippines call center client calendar alignment for time-bound decisions','Map offshore coverage against the real hours when client specialists can accept privacy, payment, policy, or technical decisions.','Client calendar alignment','each restricted decision has a receiving owner, available window, acknowledgement method, and after-hours customer message','a Manila night shift receives a refund exception after the client finance approver has signed off','acceptance latency, after-hours arrivals, overdue promises, and returned requests','the client escalation owner'],
  ['offshore-call-center-case-linking-standard','Offshore call center case linking standards that preserve separate commitments','Define when records may be linked or merged and when separate customer needs, permissions, or ownership must remain distinct.','Case linking standards','records are combined only after identity, request, authority, and open commitments are compared','two tickets share an order number but contain different delivery and payment questions','incorrect merges, repeated work, lost promises, and successfully linked histories','the case-governance owner'],
  ['call-center-queue-reassignment-log','Call center queue reassignment logs for visible ownership changes','Document who changed a route, status, script, priority, or closure and why the ordinary rule was insufficient.','Queue reassignment logs','every reassignment identifies the original rule, authorized decision maker, reason, customer impact, and review point','a supervisor extends a callback window during an incident rather than using the normal closure rule','reassignment reasons, repeated exceptions, customer corrections, and later policy changes','the operations governance owner'],
  ['offshore-call-center-due-today-review','Offshore call center due-today reviews before customer commitments expire','Review due and near-due customer commitments by wording, time zone, dependency, update status, and accepted next ownership.','Due-today reviews','shift close requires every due-today commitment to have a due point, current dependency, customer update state, and accepting owner','an unresolved delivery inquiry will cross shifts with a customer update due in two hours','overdue promises, acceptance gaps, reschedules, and completed customer updates','the incoming shift owner'],
  ['call-center-unclear-instruction-escalation','Call center unclear instruction escalation that prevents confident guessing','Capture the exact question, affected workflow, source consulted, urgency, and interim customer step for authorized policy review.','Unclear instruction escalation','an unanswered unclear instruction becomes a traceable request to a named authority rather than permission to infer a rule','a customer asks about an eligibility exception absent from the current approved knowledge source','question categories, answer latency, repeated uncertainty, corrections, and source updates','the authorized policy owner'],
] as const;

export const september2BlogPosts: September2BlogPost[] = specs.map(([slug,title,excerpt,focus,rule,example,proof,owner]) => ({slug,title,excerpt,minutes:10,focus,question:`How should an offshore call center manage ${focus.toLowerCase()}?`,published:'2026-09-02',modified:'2026-09-02',body:buildBody(focus,rule,example,proof,owner)}));
