export type September18BlogPost = {
  slug: string; title: string; excerpt: string; minutes: number; focus: string;
  question: string; published: '2026-09-18'; modified: '2026-09-18'; body: readonly string[];
};

type Topic = {
  slug:string; title:string; excerpt:string; focus:string; question:string;
  situation:string; record:string; boundary:string; example:string; measure:string;
  owner:string; source:string; service:string;
};

const topics: readonly Topic[] = [
  {slug:'offshore-call-center-seasonal-volume-readiness',title:'Offshore call center seasonal volume readiness: a buyer playbook',excerpt:'Turn a seasonal forecast into hiring, training, overflow, and rollback decisions that a provider and client can test together.',focus:'seasonal volume readiness',question:'How should a buyer prepare an offshore call center for a seasonal demand spike?',situation:'a promotion, renewal cycle, holiday, or weather event is expected to change contact volume',record:'the forecast version, interval assumptions, included queues, staffing response, training lead time, and the person who accepted the plan',boundary:'a forecast is a planning input, not a promise that every interval will behave as predicted',example:'A retailer expects delivery-status calls to double for three weeks, but keeps refunds and address changes with its internal team until the overflow group passes scored practice calls.',measure:'forecast error by interval, answer delay, abandonment, overflow use, repeat contacts, quality scores, and unresolved work at shift end',owner:'the client operations manager and provider workforce lead',source:'The Erlang-C model is useful only when its assumptions fit the queue; the U.S. National Institute of Standards and Technology guidance on contingency planning supports testing recovery choices rather than assuming the plan will work.',service:'/services/operations-support'},
  {slug:'call-center-accessibility-accommodation-routing',title:'Call center accessibility accommodation routing without guesswork',excerpt:'Give agents a respectful way to capture communication needs, offer approved options, and reach an accountable specialist.',focus:'accessibility accommodation routing',question:'How should a call center respond when a customer asks for a communication accommodation?',situation:'a customer says the normal voice, pace, language, or channel does not let them complete the interaction',record:'the customer-stated need, option offered, consent to change channels, verification state, promised response, and receiving owner',boundary:'frontline staff should not diagnose a condition, challenge a need, or invent an accommodation the service cannot deliver',example:'A caller asks to continue in writing because speech is difficult. The agent explains the approved secure-message option, confirms what can carry over, and records the handoff without labeling the customer.',measure:'completed accommodations, avoidable transfers, repeat explanations, dropped contacts, missed promises, complaints, and cases with no accepted owner',owner:'the accessibility program owner or designated service manager',source:'The Web Content Accessibility Guidelines from W3C provide an authoritative digital-accessibility reference, while local legal duties should be reviewed by qualified counsel for the customer geography.',service:'/services/customer-support'},
  {slug:'offshore-call-center-payment-call-boundary',title:'The payment-call boundary for an offshore call center',excerpt:'Separate payment assistance from restricted card-data handling, financial decisions, and unsafe note-taking.',focus:'payment-call boundaries',question:'What should an offshore call center agent do when a customer wants to pay by phone?',situation:'a customer asks an agent to take, repeat, store, change, or troubleshoot payment information',record:'the request type, identity-check result, approved payment path offered, transaction reference permitted by policy, failure reason, and next owner',boundary:'agents must not write card data into notes, request it over an unapproved channel, or imply a declined transaction has been reversed',example:'A customer begins reading a card number before the secure payment handoff. The agent interrupts politely, explains the protected route, and keeps the general call recording out of the restricted entry step.',measure:'secure-path completion, payment-related transfers, recording pauses, prohibited-data findings, failed handoffs, repeat contacts, and specialist response time',owner:'the client payment-process owner with security and compliance review',source:'PCI Security Standards Council materials are the primary reference for payment-card controls; the precise scope and implementation should be confirmed against the organization’s current PCI DSS obligations.',service:'/services/customer-support'},
  {slug:'call-center-ai-transcript-review',title:'Call center AI transcript review: where human checks still matter',excerpt:'Use automated transcripts as a searchable aid while preserving audio, uncertainty, and human review for material decisions.',focus:'AI transcript review',question:'How should a call center quality team review AI-generated transcripts?',situation:'speech recognition creates a transcript used for search, summaries, coaching, disposition suggestions, or quality review',record:'the audio reference, engine and configuration version, confidence or uncertainty signals, human corrections, downstream use, and reviewer decision',boundary:'a transcript is not an exact record when names, numbers, accents, crosstalk, or poor audio can change meaning',example:'An automated summary says the customer accepted a callback, but the audio shows the customer asked not to be called before Monday. The reviewer corrects the promise and flags the summary pattern.',measure:'material transcription errors, correction rate by call condition, false alerts, missed risk events, reviewer agreement, and downstream actions changed after audio review',owner:'the quality lead working with privacy, security, and the business owner of the decision',source:'NIST AI Risk Management Framework and its Generative AI Profile provide current risk-management references; product-specific accuracy claims still require testing on the organization’s own calls.',service:'/services/call-quality-monitoring'},
  {slug:'offshore-call-center-disaster-recovery-tabletop',title:'How to run an offshore call center disaster-recovery tabletop',excerpt:'Test people, queues, systems, customer messages, and decision rights before an outage forces improvisation.',focus:'disaster-recovery tabletop exercises',question:'How should an offshore call center run a practical continuity tabletop?',situation:'a site, carrier, CRM, identity provider, power source, or customer communication channel becomes unavailable',record:'the scenario, assumptions, participants, decisions, elapsed times, unavailable dependencies, customer impact, corrective actions, owners, and due dates',boundary:'a discussion exercise does not prove that backup capacity, access, or telecommunications will function under load',example:'The exercise removes the primary CRM during an evening shift. Agents can answer calls but cannot verify account details, so the team tests the safe holding message, urgent route, and reconciliation list.',measure:'time to declare, time to reach decision owners, work safely contained, backup capacity demonstrated, customer updates issued, and corrective actions closed',owner:'the provider continuity lead and the client incident owner',source:'NIST Special Publication 800-34 provides established contingency-planning guidance, and CISA continuity resources can help teams structure exercises and after-action work.',service:'/services/operations-support'},
  {slug:'call-center-repeat-contact-root-cause-review',title:'Call center repeat-contact root cause review that leads to action',excerpt:'Trace why customers return instead of treating every second contact as an agent failure or a single headline metric.',focus:'repeat-contact root cause review',question:'How should a call center investigate repeat customer contacts?',situation:'the same customer returns about the same need after an earlier interaction appeared complete',record:'the linked contacts, original request, promised action, owner, due time, system events, customer outcome, and reviewer’s evidence for the root-cause label',boundary:'matching a customer or topic does not prove the first agent caused the second contact',example:'A customer calls three times about a replacement. The first agent submitted it correctly, but a warehouse exception had no customer-update owner. Coaching the agent would not repair the missing exception route.',measure:'repeat contacts by cause, time between contacts, broken promises, unresolved dependencies, corrections, transfers, and recurrence after the process change',owner:'the queue owner who can change the workflow, supported by quality reviewers',source:'ISO 18295-1 describes customer contact centre requirements at a high level; internal source records remain necessary to establish what happened in a particular repeat-contact chain.',service:'/services/call-quality-monitoring'},
  {slug:'offshore-call-center-supervisor-span-planning',title:'Offshore call center supervisor span planning by work, not folklore',excerpt:'Set supervisor coverage around queue risk, coaching load, live decisions, schedules, and incident duties.',focus:'supervisor span planning',question:'How should a buyer assess the supervisor-to-agent span in an offshore call center?',situation:'a provider proposes a team structure or the live queue shows delayed approvals, weak coaching, or uneven support',record:'active agents by interval, queues covered, supervisor duties, approval volume, escalations, coaching commitments, absences, and backup coverage',boundary:'one ratio cannot prove that supervision is adequate because complexity, experience, channel mix, and decision rights differ',example:'Twelve experienced agents on a stable information queue may need fewer live interventions than eight new agents handling account exceptions across voice and chat.',measure:'approval wait, escalation response, coaching completion, review backlog, supervisor occupancy, missed breaks, unresolved incidents, and quality movement after coaching',owner:'the provider operations lead with acceptance by the client queue owner',source:'Use workforce records and the agreed operating model as primary evidence; industry ratios can be discussion prompts but should not be presented as universal standards.',service:'/services/operations-support'},
  {slug:'call-center-knowledge-search-failure-review',title:'Call center knowledge search failure: finding what agents cannot find',excerpt:'Review failed searches, misleading results, and unsafe workarounds so the knowledge base supports real calls.',focus:'knowledge search failure review',question:'How should a call center investigate failed knowledge searches?',situation:'an agent cannot find an approved answer quickly or chooses a result that does not match the customer’s request',record:'the search phrase, filters, results shown, article chosen, article version, call context, workaround, customer impact, and correction owner',boundary:'a zero-result search does not automatically mean content is missing; labels, permissions, indexing, spelling, or scope may be wrong',example:'Agents search for “move delivery” while the official article is titled “shipment address amendment.” The content exists, but customer language is absent from the title and synonyms.',measure:'zero-result searches, reformulations, time to answer, wrong-article use, escalations, unsafe workarounds, article changes, and recurrence after the fix',owner:'a named knowledge owner working with frontline agents and the process owner',source:'NIST quality-management principles support traceable information and controlled change; platform documentation should be used for product-specific indexing and permission behavior.',service:'/services/admin-support'},
  {slug:'offshore-call-center-vendor-governance-meeting',title:'An offshore call center vendor governance meeting that makes decisions',excerpt:'Replace status theatre with an evidence pack, named decisions, risk owners, and a short action ledger.',focus:'vendor governance meetings',question:'What should a useful offshore call center governance meeting cover?',situation:'client and provider leaders need to review service health, quality, staffing, changes, incidents, and unresolved commercial or operating risks',record:'the reporting period, metric definitions, exceptions, decisions requested, decision maker, action, owner, due date, and acceptance evidence',boundary:'the meeting should not turn unverified anecdotes into performance conclusions or use one average to hide queue-level failures',example:'Overall answer speed is on target, but the billing queue has a growing approval backlog. The meeting assigns an authority review instead of praising the blended average.',measure:'actions closed on time, decisions delayed, recurring risks, metric corrections, unresolved customer work, change outcomes, and items carried without an owner',owner:'the client service owner and provider account lead, with specialists invited for decisions they control',source:'ISO 18295-2 describes requirements for clients using customer contact centres; contracts, service schedules, and source-system records remain the controlling evidence for the relationship.',service:'/services/operations-support'},
  {slug:'call-center-disposition-taxonomy-migration',title:'Call center disposition taxonomy migration without losing history',excerpt:'Change outcome codes with a crosswalk, training, validation, and reporting cutover that keeps old records understandable.',focus:'disposition taxonomy migration',question:'How should a call center replace disposition codes safely?',situation:'the organization consolidates, renames, splits, or retires call outcomes in the CRM or contact-center platform',record:'old and new codes, definitions, effective date, crosswalk, unmapped cases, reporting treatment, training completion, validation result, and rollback owner',boundary:'renaming a code does not repair inconsistent agent decisions or make historic records more precise than they were',example:'“Resolved” becomes “answered—no follow-up” and “action completed.” Historical records stay under the old label, while the report marks the cutover rather than guessing which new code applies.',measure:'unmapped records, use of retired codes, correction rate, agent disagreement, report breaks, routing errors, and repeat contacts by old and new definitions',owner:'the CRM or reporting owner with sign-off from operations and quality',source:'Controlled vocabulary and data-governance practices should guide the change; the organization’s platform documentation is authoritative for field, API, and reporting behavior.',service:'/services/admin-support'},
  {slug:'offshore-call-center-abandoned-call-consent',title:'Offshore call center abandoned-call follow-up and consent',excerpt:'Decide when a missed caller may be contacted, what context can be used, and when the callback should stop.',focus:'abandoned-call follow-up consent',question:'How should an offshore call center follow up after an abandoned inbound call?',situation:'a caller disconnects before reaching an agent or before the purpose and contact preference are clear',record:'the source number, consent or policy basis, queue, abandon time, prior verified preference, attempts, safe message, outcome, and suppression request',boundary:'caller ID alone does not prove identity, permission to discuss an account, or permission for repeated outreach',example:'The queue permits one service callback to a previously verified number, but the agent reaches voicemail. The message names the company and return channel without exposing the suspected account issue.',measure:'callback connection, opt-outs, complaints, wrong-party contacts, repeat attempts, resolved needs, unsafe disclosures, and work left without a stop reason',owner:'the client channel owner with privacy and legal review for applicable calling rules',source:'The U.S. Federal Trade Commission and Federal Communications Commission publish calling-rule resources; requirements vary by purpose and geography, so qualified counsel should approve the operating rule.',service:'/services/customer-support'},
  {slug:'call-center-coaching-transfer-test',title:'Call center coaching transfer tests: did the behavior reach live calls?',excerpt:'Check whether a coached skill appears in later customer work instead of closing the action when the meeting ends.',focus:'coaching transfer tests',question:'How can a call center tell whether coaching changed live-call behavior?',situation:'a review finds a material gap and the agent completes explanation, practice, or side-by-side coaching',record:'the source example, expected behavior, practice evidence, transfer-test sample, selection window, result, confounding conditions, and next action',boundary:'attendance, quiz completion, or agreement with a coach does not prove that the behavior transfers under live queue pressure',example:'An agent practices confirming callback time zones correctly. The follow-up sample includes routine, overnight, and daylight-saving cases rather than only the easiest successful call.',measure:'target behavior in eligible calls, recurrence, new errors, customer consequence, reviewer agreement, and whether a script, tool, authority, or workload issue remains',owner:'the frontline supervisor with quality calibration and support from the process owner',source:'Use recorded calls and workflow events as primary evidence. Training frameworks can structure practice, but local observation is required to establish transfer to this queue.',service:'/services/call-quality-monitoring'},
];

function article(t: Topic): readonly string[] {
  return [
    `${t.question} Start with the operating decision, not a generic checklist. The trigger here is ${t.situation}. Write down what the frontline role may do, what must stop, and who can authorize an exception. That turns ${t.focus} into a queue rule that can survive a busy shift. It also gives a buyer something concrete to test during a pilot instead of accepting a broad assurance.`,
    `Define the record before training begins. At minimum, preserve ${t.record}. Put those fields in the system where the interaction is finished, not in a separate spreadsheet that the next shift may never see. Use plain labels and one worked example for each uncommon outcome. A field is useful only when the next owner can read it, understand the current state, and take the promised action without asking the customer to repeat material facts.`,
    `Keep the authority boundary visible: ${t.boundary}. Agents need a safe sentence for that boundary and a route that is available during every covered interval. “Ask a supervisor” is incomplete when no supervisor is named, the approval channel is unclear, or the customer receives no update time. The handoff should state what has been verified, what remains uncertain, what action is requested, and when the receiver accepted ownership.`,
    `Consider a realistic case. ${t.example} Walk through the ordinary path, an ambiguous path, and a high-risk exception. Include a failed tool, an unavailable owner, and a customer who changes the request. These variants show whether the written rule actually supports judgment. They also reveal hidden dependencies in access, schedules, scripts, and reporting before those dependencies become customer-facing failures.`,
    `For a Philippines-based offshore team, align the workflow across the customer’s time zone, the delivery team’s shift, and the client owner’s availability. State which decisions can wait for the next business day and which require immediate coverage. If the receiving owner is offline, use an approved holding response and an aging queue. Do not turn a time-zone difference into permission for an agent to make a decision outside the agreed role.`,
    `Training should use source records and observable actions. Give agents a short policy, representative examples, and practice cases with missing or conflicting facts. Ask them to explain why they selected an action, not merely which button they clicked. Supervisors should calibrate on the same cases and record disagreements. When experienced reviewers choose different outcomes, repair the definition or decision aid before treating the variation as an individual performance problem.`,
    `Quality review must sample the work that carries risk. Include normal contacts, transfers, long interactions, after-hours work, customer complaints, and cases where the safe answer was to stop. Reviewers should connect every finding to a timestamp, field, or system event and distinguish observed facts from interpretation. A polished call can still produce an unsafe record, while a difficult conversation can be handled correctly and deserve a pass.`,
    `Track ${t.measure}. Read the measures together rather than optimizing one number in isolation. Faster handling may hide repeat contacts, and fewer escalations may mean agents are acting beyond authority. Compare the same defined population before and after a change, retain the denominator, and inspect contrary cases. Small counts should be described as small counts rather than converted into a confident trend.`,
    `Ownership belongs with ${t.owner}. That owner should review recurring exceptions, approve changes, and set the next check date. Providers can propose fixes, but client-side decisions about customer promises, access, regulated work, pricing, refunds, or policy exceptions must remain with an authorized client representative. Record both the person who proposed the change and the person who accepted the resulting risk.`,
    `Use authoritative material carefully. ${t.source} A source can define a control area or planning method, but it cannot prove that one provider follows it. Ask for local evidence: configuration screenshots where appropriate, sampled records, training completion, access logs, exercise results, and accepted handoffs. Recheck time-sensitive requirements at the source before changing policy, and avoid turning general guidance into unsupported legal advice.`,
    `Launch the change narrowly. Choose one queue, one coverage window, a fixed start date, and a pre-set review sample. Keep a rollback option when the new path could strand customer work. During the first week, hold a short daily exception review: what happened, which rule applied, what evidence was missing, who owns the correction, and whether the customer needs an update. Expand only after the routine works across shifts and exceptions.`,
    `A buyer can use this approach during provider selection. Ask each provider to map the same scenario, identify the decision owner, show the handoff record, and explain how a supervisor would review it. Compare the evidence and operating choices instead of rewarding the most confident presentation. Call Center Offshore can help scope a narrow Philippines-based support workflow, document the controls, and prepare a quality review before more work is added. See ${t.service} for the related service path.`,
  ];
}

export const september18BlogPosts: readonly September18BlogPost[] = topics.map(t => ({
  slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:11,focus:t.focus,question:t.question,
  published:'2026-09-18',modified:'2026-09-18',body:article(t),
}));
