export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[] };

export const fleetServices: readonly FleetService[] = [
  { slug: 'inbound-customer-care', title: 'Inbound Customer Care', desc: 'Build a Philippines-based inbound customer care workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'technical-help-desk', title: 'Technical Help Desk', desc: 'Build a Philippines-based technical help desk workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'order-and-billing-support', title: 'Order and Billing Support', desc: 'Build a Philippines-based order and billing support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'appointment-scheduling', title: 'Appointment Scheduling', desc: 'Build a Philippines-based appointment scheduling workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'after-hours-answering', title: 'After-Hours Answering', desc: 'Build a Philippines-based after-hours answering workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'outbound-lead-qualification', title: 'Outbound Lead Qualification', desc: 'Build a Philippines-based outbound lead qualification workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'customer-retention-support', title: 'Customer Retention Support', desc: 'Build a Philippines-based customer retention support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'ecommerce-contact-center', title: 'Ecommerce Contact Center', desc: 'Build a Philippines-based ecommerce contact center workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'healthcare-scheduling-support', title: 'Healthcare Scheduling Support', desc: 'Build a Philippines-based healthcare scheduling support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'call-quality-monitoring', title: 'Call Quality Monitoring', desc: 'Build a Philippines-based call quality monitoring workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring call center work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [];
export const postsPerPage = 20;
