import type {ResearchPost} from './fleet-data';
const body=[
'Research question: what evidence supports reviewer agreement in offshore call center quality review without turning a score into an unsupported claim about people or performance? The date of this route-specific record is 2026-08-21. Agreement can reflect a clear rubric, shared source, observable behavior, or simple consensus around an ambiguous rule. This study asks which evidence is present and what a manager can responsibly conclude from disagreement.',
'Methodology and evidence scope: we compared governance and recovery concepts at https://www.nist.gov/cyberframework, privacy-risk practices at https://www.nist.gov/privacy-framework, Philippine privacy requirements at https://privacy.gov.ph/data-privacy-act/, and distributed-work context at https://www.ilo.org/global/topics/non-standard-employment/platform-work/lang--en/index.htm. We used a scenario review of sampled calls, tickets, or records scored by paired reviewers. The unit is one defined review item and criterion. Facts are the recording or source record, rubric line, reviewer decision, reason, and calibration action. Analysis separates reviewer disagreement from source ambiguity and agent behavior.',
'A scorecard should name observable evidence. “Good call” is too broad to calibrate. A useful criterion might require a verification step, accurate approved answer, clear next action, or correct escalation. Each reviewer should cite the moment, source, and rubric line rather than rely on memory. If the policy answer is unclear, the dispute belongs with the source owner. If the handoff is uncertain, inspect the receiving record. A calibration meeting should not solve a policy gap by choosing the most confident voice.',
'Agreement has several meanings. Reviewers may give the same score for the same reason, the same score for different reasons, or different scores because a criterion is ambiguous. Record the reason category. Compare independent first scores before discussion, then retain the resolved interpretation and the owner. A high percentage can hide a criterion that almost never appears or reviewers who avoid difficult cases. A low percentage can reveal a useful rubric question rather than poor reviewer skill. The evidence needs denominator, sample frame, and exclusion rules.',
'Quality review must keep role boundaries clear. A reviewer can identify an observable miss, link it to a documented risk, and prepare a coaching note. A reviewer should not invent policy, determine a sensitive customer remedy without authority, or treat a disputed score as proof of misconduct. Managers own calibration rules and source questions. Client-side policy owners decide exceptions. Representatives need a fair chance to see the criterion, understand the expected behavior, and respond to evidence. This boundary makes quality work diagnostic instead of punitive.',
'Privacy matters in the review record. Sample access should be limited to authorized reviewers, and the report should contain the minimum context needed to explain the score. The Philippine Data Privacy Act is external context, not a legal conclusion about a particular company. Reviewers should avoid copying unrelated personal details into coaching notes and should define retention and access. If a case is sensitive, route it to the authorized owner rather than widening access for convenience. A scorecard cannot override a privacy or security boundary.',
'Analysis should stratify agreement by criterion, channel, request type, reviewer pair, shift, and source version. Calculate rates only after defining what counts as agreement and how missing items are handled. A rising agreement rate may mean better calibration, easier samples, or reviewers learning to defer. Read disagreements and agreements with reasons. Change one control, such as a rubric example, source clarification, paired sample, or escalation rule. Re-score comparable items and report whether the reason for agreement changed, not only the number.',
'Limitations: this study cannot prove customer satisfaction, representative intent, universal quality, or causal impact of calibration. A scenario review is not a randomized evaluation. Recording quality, sample selection, reviewer workload, and policy changes can affect results. External frameworks provide governance questions rather than a quality score for one offshore call center. Agreement can improve while the rubric measures the wrong risk. Findings are bounded to the selected items, criteria, reviewers, period, and source version.',
'Evidence-led conclusion: reviewer agreement is meaningful when independent scores cite the same observable evidence, rubric rule, and risk, while disagreements are classified and assigned to the correct owner. A shared score alone proves little. Offshore call center quality teams should preserve first scores, reasons, source questions, and next calibration date; they should fix ambiguous criteria before attributing variation to representatives. The evidence supports a bounded improvement decision, not a universal ranking or promise.'
,'A calibration record should preserve why the score changed after discussion. Was a rubric example clarified, was a source owner consulted, or did reviewers simply settle on a majority view? Those are different events. Reviewers should cite the observable moment, the criterion, the customer or process risk, and the action that follows. If the criterion rewards a quick transfer while hiding customer effort, agreement may reinforce the wrong incentive. A bounded report can surface that tension and assign it to the scorecard owner without turning a dispute into a public claim about an entire offshore operation.'
].join(' ');
const sources=[{name:'NIST CSF',url:'https://www.nist.gov/cyberframework',note:'Governance.',kind:'Global comparison' as const},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy.',kind:'Global comparison' as const},{name:'Philippine Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary law.',kind:'Philippines' as const},{name:'ILO platform work',url:'https://www.ilo.org/global/topics/non-standard-employment/platform-work/lang--en/index.htm',note:'Work context.',kind:'Global comparison' as const}];
export const august21ReviewerAgreement:readonly ResearchPost[]=[{slug:'offshore-call-center-reviewer-agreement-study',title:'Offshore call center quality review: evidence behind reviewer agreement',excerpt:'A bounded study of observable criteria, disagreement causes, privacy boundaries, and calibration evidence.',hero:'/aug21-research-heroes/offshore-call-center-quality-calibration-evidence.png',published:'2026-08-21',modified:'2026-08-21',revision:'2026-08-21-offshore-call-center-reviewer-agreement-study-v1',readingMinutes:7,wordCount:body.split(/\s+/).length,methodology:'Scenario review of paired quality scores against four external sources.',limitations:'The study cannot prove satisfaction, intent, universal quality, or calibration causation.',keyTakeaways:['Agreement needs shared observable evidence.','Ambiguous policy belongs with its owner.','Quality review must preserve role and privacy boundaries.'],stats:[],sections:[{heading:'Research question, methodology, analysis, limitations, and conclusion',paragraphs:[{text:body,citations:[1,2,3,4]}]}],table:{caption:'Reviewer agreement evidence boundary',headers:['Observed evidence','Supports','Does not prove','Next test'],rows:[['Independent cited scores','Calibration signal','Universal quality','Re-score a comparable sample']]},buyerChecklist:[],faqs:[{q:'Does a shared score prove quality?',a:'No. Reviewers must cite the same observable evidence and criterion.'}],related:[{title:'Research library',href:'/research'}],sources}];
