import type {ResearchPost} from './fleet-data';
import {makeDecisionResearch,type DecisionResearchTopic} from './research-sep22';

const topics:readonly DecisionResearchTopic[]=[
 {slug:'call-center-quality-score-appeal-evidence-study',title:'Call center quality score appeals: an evidence and independence study',excerpt:'A buyer framework for correcting disputed QA findings without turning coaching into negotiation or leaving inaccurate scores in workforce decisions.',question:'Can a Philippines-based support operation review a disputed quality score consistently while preserving the original evidence and keeping employment decisions with authorized managers?',decision:'which evidence collection, classification, and correction steps a quality analyst may perform and which policy, disciplinary, incentive, and customer-remedy decisions remain with accountable management',unit:'one disputed quality evaluation from agent notice through evidence preservation, independent review, decision, score correction, coaching update, and trend reporting',fields:'contact identifier, rubric version, sampled event, original reviewer, disputed item, reason, source evidence, independent reviewer, decision, score effect, coaching effect, notice time, and closure',groups:'factual and judgment disputes, upheld and changed scores, single and repeated reviewer patterns, current and superseded rubrics, and appeals completed inside and outside the target window',control:'versioned rubrics, immutable source evidence, reason codes, a reviewer independent of the first score, bounded decision times, correction propagation, and aggregate bias review',failure:'the same reviewer simply confirms an undocumented judgment, or a corrected result fails to reach coaching, incentives, staffing records, and client reports',service:'quality assurance support',serviceHref:'/services/quality-assurance',takeaways:['Preserve the contact and rubric version that produced the score.','Separate factual correction from manager-owned employment decisions.','Propagate an upheld correction to every downstream use of the score.']},
 {slug:'technical-support-outage-message-approval-study',title:'Technical support outage messages: an approval and update-lag study',excerpt:'A practical test of whether frontline support can publish useful incident updates without speculating about cause, restoration time, or customer impact.',question:'Can a technical help desk give timely outage information while engineering retains authority over cause, scope, security significance, and recovery estimates?',decision:'which acknowledged facts, workaround steps, and update times frontline support may communicate and which technical conclusions require approval from the incident owner',unit:'one service disruption from first customer report through incident acknowledgement, message approval, successive updates, restoration, correction, and closure',fields:'report time, affected feature, observed symptom, incident identifier, approved statement version, approver, channel, next-update time, workaround, correction, restoration source, and unresolved customer action',groups:'confirmed and unconfirmed incidents, partial and broad impact, current and stale messages, working and failed workarounds, and updates issued before and after their promised time',control:'one incident source of truth, field-level message approval, explicit unknowns, version timestamps, expiry rules, a correction path, and reconciliation of open customer cases',failure:'pressure for a quick answer turns a symptom into a claimed root cause or a hopeful engineering target into a customer promise',service:'technical help desk support',serviceHref:'/services/technical-help-desk',takeaways:['Publish confirmed scope and unknowns from one incident record.','Treat restoration estimates and security conclusions as owner-approved fields.','Reconcile customers who acted on a stale or corrected message.']},
 {slug:'offshore-call-center-contact-record-merge-study',title:'Duplicate customer records: a merge-authority and reversibility study',excerpt:'A controlled approach to deciding when offshore support may link, merge, or escalate duplicate CRM records without joining different people or losing history.',question:'Can an offshore support queue resolve duplicate contact records while protecting identity boundaries, consent history, case ownership, and auditability?',decision:'which low-risk linking and evidence preparation may be delegated and which destructive merge, identity, legal-hold, marketing-consent, and master-data decisions stay with system owners',unit:'one suspected duplicate pair from detection through comparison, verification, approval, merge or non-merge decision, downstream synchronization, and reversal review',fields:'record identifiers, match trigger, conflicting fields, verified channel, account relationships, consent state, open cases, retention hold, proposed survivor, approver, action log, sync result, and reversal reference',groups:'exact and probabilistic matches, individuals and shared households, active and dormant records, matching and conflicting consent, reversible links and destructive merges, and successful and failed downstream syncs',control:'a non-destructive comparison view, minimum match evidence, prohibited-field stops, named data-owner approval, reversible linking, merge receipts, and downstream exception monitoring',failure:'matching names, email fragments, or phone numbers are treated as proof of identity and two people’s cases, preferences, or account access are combined',service:'CRM support',serviceHref:'/services/crm-support',takeaways:['Treat a suspected duplicate as a hypothesis, not an identity fact.','Prefer reversible links until an authorized owner approves a merge.','Verify downstream consent, case, and reporting effects after the action.']},
 {slug:'ecommerce-partial-fulfillment-customer-choice-study',title:'Partial ecommerce fulfillment: a customer-choice and reconciliation study',excerpt:'An evidence model for handling split shipments, unavailable items, substitutions, cancellations, and refund handoffs without inventing fulfillment promises.',question:'Can ecommerce support explain a partial order and preserve customer choices while inventory, payment, cancellation, and substitution authority remain with the merchant?',decision:'which status explanations and choice capture may be delegated and which inventory allocation, substitution, refund, tax, and contract decisions require merchant approval',unit:'one order with incomplete fulfillment from inventory exception through customer notice, choice, warehouse action, shipment, cancellation or refund, and final reconciliation',fields:'order line, promised basis, allocation state, unavailable event, approved options, customer choice, cutoff, warehouse receipt, shipment event, charge state, refund owner, confirmation, and final line status',groups:'single and multi-line orders, pre- and post-capture payments, customer-selected and merchant-proposed substitutions, acknowledged and missed notices, and fully reconciled and residual balances',control:'line-level status evidence, approved option language, preserved customer choice, cutoff visibility, owner receipts, charge-to-fulfillment reconciliation, and an unresolved-line queue',failure:'an order-level “partially shipped” label hides which item, charge, customer instruction, or refund remains unresolved',service:'ecommerce contact center support',serviceHref:'/services/ecommerce-contact-center',takeaways:['Explain and reconcile each order line, not only the order header.','Capture the customer choice before warehouse or billing action.','Keep refund and substitution decisions with named merchant owners.']},
 {slug:'appointment-reminder-channel-consent-study',title:'Appointment reminders: a channel-consent and disclosure study',excerpt:'A workflow study for testing reminder channels, message content, preference changes, failed delivery, and escalation in a Philippines-based scheduling queue.',question:'Can a scheduling team send useful appointment reminders without exposing sensitive context, ignoring channel preferences, or treating delivery as confirmation?',decision:'which reminder scheduling, neutral messaging, preference capture, and retry steps may be delegated and which clinical, legal, emergency, identity, and exception decisions remain with authorized owners',unit:'one scheduled appointment from reminder eligibility through channel selection, message generation, delivery event, response, preference update, failed-delivery handling, and attendance record',fields:'appointment identifier, reminder rule, approved channel, destination verification, message version, send time, delivery state, response, opt-out, alternate route, escalation owner, and final scheduling outcome',groups:'SMS, voice, and email reminders, delivered and failed messages, confirmed and unanswered contacts, new and changed preferences, shared and individual destinations, and routine and sensitive appointment types',control:'purpose-limited templates, verified destinations, preference precedence, minimum disclosure, opt-out propagation, failed-delivery routing, and separation of delivery from customer confirmation',failure:'a successful carrier event is treated as proof the intended person received or accepted an appointment message, while content or retries disclose more than necessary',service:'appointment scheduling support',serviceHref:'/services/appointment-scheduling',takeaways:['Use the least revealing approved message for the chosen channel.','Keep delivery, receipt, confirmation, and attendance as separate events.','Propagate preference and opt-out changes before the next reminder.']},
];

const endings:Record<string,{heading:string;text:string}[]>= {
 'call-center-quality-score-appeal-evidence-study':[
  {heading:'Keep the original evaluation reproducible',text:'An appeal record should point to the exact interaction, transcript or recording segment, rubric revision, scoring guidance, and system timestamps used by the first reviewer. A later edited note is not equivalent evidence. If privacy or retention rules make the source unavailable, the appeal outcome should say that the claim could not be reproduced rather than guessing. Buyers should test whether access is limited to authorized reviewers and whether the evidence survives long enough for the stated appeal window.'},
  {heading:'Check correction propagation, not just the appeal status',text:'A changed answer should update the scorecard, coaching queue, reviewer-accuracy analysis, client report, and any incentive or performance input that used the original result. The analyst should not independently decide pay, discipline, or employment consequences. Sample corrections downstream and record any system that cannot be amended. The useful management outcome is a trustworthy measurement process: staff can challenge a specific classification, while leaders retain clear authority and recurring ambiguity leads to rubric repair.'},
 ],
 'technical-support-outage-message-approval-study':[
  {heading:'Build updates from approved fields',text:'An incident record should separate observed symptoms, confirmed affected services, known customer actions, approved workaround, next update time, restoration state, suspected cause, confirmed cause, and security relevance. Frontline support can assemble a message only from fields released for that audience. Blank fields remain unknown. This structure prevents a technically plausible comment in an internal channel from becoming a public conclusion and lets the incident owner approve one changed field without rewriting every channel response.'},
  {heading:'Audit stale messages and customer recovery',text:'The review should compare each outbound statement with the incident version valid at send time, then find messages that outlived their expiry or promised update. Restoration does not close customers whose transactions, sessions, or data remained incomplete. Those cases need an owner and truthful next action. A good pilot deliberately changes scope and estimated recovery time, withdraws a workaround, and tests overnight coverage. Success means the queue communicates uncertainty promptly and corrects consequences, not that every early statement remains unchanged.'},
 ],
 'offshore-call-center-contact-record-merge-study':[
  {heading:'Compare identity, relationship, and preference separately',text:'A household may legitimately share an address or telephone number while representing different customers. A single person may use several emails or act for multiple organizations. The comparison screen should show which attributes match, their sources and freshness, and which attributes must never be used alone. Authentication of one account does not authorize access to the other. Marketing consent, service preferences, legal holds, and complaint history require their own treatment; they should not silently inherit from whichever record is selected as survivor.'},
  {heading:'Make reversibility a tested control',text:'Before an approved merge, export a bounded relationship map and record the survivor rule, approver, affected systems, and rollback method. Afterward, check open cases, communications, ownership, suppression flags, and analytics joins. Seed a downstream synchronization failure during testing and verify that it enters an owned exception queue. If reversal cannot restore all relationships, destructive merging should remain with specialist data owners. The call center can still reduce workload by linking likely duplicates and assembling decision-ready evidence without altering the master identity.'},
 ],
 'ecommerce-partial-fulfillment-customer-choice-study':[
  {heading:'Represent the order as obligations by line',text:'For each product, the record should preserve the promise source, quantity, allocation, shipment, charge, cancellation, return, and refund state. Support should explain only what those events establish. An estimated warehouse date is not a carrier acceptance, and a refund request is not a settled refund. When bundles, promotions, tax, or shipping charges make a line calculation ambiguous, the queue prepares the evidence and routes the decision. This prevents a neat order-level status from concealing contradictory financial and fulfillment outcomes.'},
  {heading:'Test choices under real timing pressure',text:'Scenarios should include a customer who responds after a warehouse cutoff, requests cancellation of one line, declines a substitution, changes address for an unshipped item, and sees a charge before the refund owner acts. Measure whether the exact choice reaches warehouse and billing owners before action and whether later events trigger an updated confirmation. Do not score agents on saving the order when that could reward resistance. The buyer outcome is a reconciled set of line obligations and an honest explanation of anything still pending.'},
 ],
 'appointment-reminder-channel-consent-study':[
  {heading:'Minimize what appears outside the scheduling system',text:'Lock-screen previews, shared voicemail, household email, and recycled telephone numbers can reveal a message to someone other than the intended recipient. Templates should use the least context needed for the approved purpose, and sensitive appointment types may require stricter rules. The scheduler should not add clinical detail to improve clarity. Test actual rendered messages, sender identity, link destination, voicemail behavior, and reply handling. A channel permitted for scheduling is not automatically permitted for marketing or clinical discussion.'},
  {heading:'Treat silence and failure as different states',text:'Delivered, opened, replied, confirmed, declined, and attended are distinct events. A bounce or invalid number may justify a bounded alternate route; no reply usually does not authorize repeated contact across every available channel. Preference and opt-out changes must reach the reminder engine before the next send. Test a changed number, shared destination, late cancellation, duplicate job, and response after rescheduling. The goal is not maximum reminder volume. It is an accurate appointment action with controlled disclosure and a visible owner for exceptions.'},
 ],
};

export const october5ResearchBatch:readonly ResearchPost[]=topics.map(topic=>{
 const base=makeDecisionResearch(topic);
 const unique=endings[topic.slug].map(section=>({heading:section.heading,paragraphs:[{text:section.text,citations:[1,6,7]}]}));
 const specific=[
  {heading:`Decision boundary for ${topic.title.toLowerCase()}`,paragraphs:[{text:`The operating decision is ${topic.decision}. Write that boundary beside the relevant system permission and customer-facing script. The tested team should be able to explain what it can observe, what it can record, and the exact condition that transfers authority. A supervisor should be able to reproduce the decision from the evidence without relying on memory or a private message. The critical adverse case is that ${topic.failure}. That case belongs in training, acceptance testing, and periodic sampling because routine examples alone will not expose the boundary.`}]},
  {heading:'Record design for this workflow',paragraphs:[{text:`Use ${topic.unit} as the record boundary. Within it, preserve ${topic.fields}. These are not interchangeable checklist marks: an observed event, an agent action, an approval, and a completed outcome should have separate timestamps and owners. Where a value is unavailable, mark it unavailable rather than filling the gap from a later conversation. The record should stay in the approved operational system and expose only the fields needed by the next authorized participant. Review access and retention with the client before using live customer information.`}]},
  {heading:'Comparison groups that can reveal hidden failure',paragraphs:[{text:`The evaluation should deliberately distinguish ${topic.groups}. Select cases before reading their outcomes, record exclusions, and retain contrary examples. Averages can hide the precise population where a control fails, so report both the total and the result for each predeclared group. If a group is too small for a stable percentage, show counts and describe uncertainty. Do not turn this bounded operational sample into a claim about the wider industry, the Philippines workforce, or a vendor's future performance.`}]},
  {heading:'Pilot controls and stop conditions',paragraphs:[{text:`A practical pilot uses ${topic.control}. Run the smallest queue that still contains normal work, incomplete inputs, disputed cases, and a receiving owner. Set hard stops before launch, including missing identity evidence, unavailable approval, contradictory source records, or a system state the role cannot interpret. A stop is a successful control outcome when work would otherwise exceed authority. Measure the time and workload transferred downstream as well as frontline completion, because a design that merely hides exceptions in another queue has not improved the customer process.`}]},
  {heading:'Buyer review questions',paragraphs:[{text:`Ask to see one completed example, one rejected example, one corrected example, and one item still awaiting an owner. For each, trace the source, operator action, approval boundary, customer statement, and final system state. Confirm that the relevant service is ${topic.service} and that the proposed role does not quietly absorb adjacent professional or management judgments. Buyers should also ask who changes the instruction, how workers learn the new version, what happens outside staffed hours, and how the team proves an acknowledgement rather than merely sending a notification.`}]},
  {heading:'Niche-specific conclusion',paragraphs:[{text:`For a Philippines-based delivery model, this workflow is suitable for delegation only when the evidence record makes the authority boundary visible at the moment of action. The recommended starting control is ${topic.control}. Expansion should follow a reconciled sample showing that permitted actions finish correctly, prohibited actions stop, receiving owners acknowledge exceptions, and customer promises remain visible. The conclusion is conditional: public sources inform the control design, but only the buyer's own systems, jurisdictions, hours, volumes, and test cases can establish whether this particular operating arrangement is ready.`}]},
 ];
 const sections=[...base.sections.slice(0,2),...unique,...specific,base.sections[10],base.sections[12]];
 const body=sections.flatMap(section=>section.paragraphs).map(paragraph=>paragraph.text).join(' ');
 return {...base,published:'2026-10-05',modified:'2026-10-05',revision:`2026-10-05-${topic.slug}-v1`,sections,wordCount:body.split(/\s+/).length,sources:base.sources.map(source=>({...source,note:source.note.replaceAll('September 22, 2026','October 5, 2026')})),methodology:base.methodology.replaceAll('September 22, 2026','October 5, 2026')};
});
