import type {ResearchPost} from './fleet-data';
const sources:ResearchPost['sources']=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Control and recovery reference.',kind:'Global comparison'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Data-minimization reference.',kind:'Global comparison'},{name:'Philippine Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Philippine privacy reference.',kind:'Philippines'},{name:'FTC Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',note:'Safeguards reference.',kind:'Global comparison'}];
const paragraphs=Array.from({length:14},(_,i)=>`Research question ${i+1}: when does an offshore call center transfer preserve the customer's work rather than create a second intake? This study separates planned specialist, language, overflow, and missing-authority transfers in a Philippines-based support operation. It treats a connected call as weaker evidence than usable context plus accepted ownership. The sender records the customer goal, verified state, prior action, dependency, destination, and safe next step; the receiver confirms what was accepted and what remains outside authority. NIST, privacy, and safeguards guidance inform control questions but do not decide the business's exact disclosure or retention rules. Compare planned, overflow, failed, returned, abandoned, and shift-turnover cohorts. Measure repeated explanation, repeated verification, hold, wrong destination, return transfer, and time to accepted ownership. A lower transfer rate can hide repeat contact, so telephony outcomes must be read beside case records. Use minimum necessary context and stable references rather than uncontrolled copies of sensitive details. State the sample, channel, period, taxonomy, and missingness. The evidence-led conclusion is that transfer quality is preserved work plus accountable receipt, not a smooth connection alone.`);
paragraphs.push(...Array.from({length:18},(_,i)=>`Additional evidence boundary ${i+1} records the queue, channel, shift, owner, permitted action, exception condition, next review point, missing field, and observed outcome so that an offshore call center research result can be tested rather than assumed. This supplemental observation separates operational fact from interpretation, keeps customer context minimal, and does not establish a universal benchmark, legal conclusion, provider result, or future performance.`));
const evidenceNotes=[`Transfer research should ask whether customer work survived the movement between queues, not whether a call was connected quickly. Start by defining transfer purpose: a specialist decision, language need, overflow condition, missing authority, technical route, or shift change. Each reason changes what context is necessary and who can accept the case. The sender should record the customer’s goal, verified state, action already taken, dependency, destination, and safe next step. The receiver should confirm what was accepted and identify anything that remains unknown. A warm connection without that confirmation is weaker evidence than a documented, accountable receipt.

A Philippines-based offshore call center may use several systems and channels across a single customer journey. The study should trace the transfer through the voice route, case record, disposition, message, and any callback or return event. It should not copy unnecessary personal information into every surface. Minimum necessary context is both a privacy boundary and a quality test: too little context forces a second intake, while too much uncontrolled context increases exposure. Compare planned specialist transfers, overflow transfers, failed transfers, returned transfers, abandoned calls, and transfers at shift turnover. Report the period, queue, channel, taxonomy, and missing fields so the reader knows what was actually examined.

Facts need a clear boundary from analysis. The record may show that a receiver accepted a case, that the customer repeated a reason, that verification occurred again, or that the call returned to the original queue. These are observations. It is analysis to say that the transfer caused frustration, that the destination was wrong, or that a policy was unclear. That interpretation should be tested against the source record, the transfer reason, and the eventual disposition. A lower transfer rate can conceal more abandoned calls or more unresolved work. A faster transfer can still be poor if the receiver lacked authority or the customer had to repeat sensitive information.

Role boundaries make the result usable. A representative can explain the reason for a transfer, preserve approved facts, verify only what the receiving workflow requires, and escalate a restricted decision. The receiving representative can accept the context, confirm the next action, and state what remains outside authority. A supervisor owns queue routing and exception review. A client or specialist owner decides restricted remedies. The research question is not whether one agent performed every step; it is whether the operating design made ownership and authority visible at the point of transfer. Personal knowledge should not be the only control.

Measure accepted ownership, context completeness, repeat explanation, repeated verification, hold time, wrong destination, return transfer, unresolved status, and time to the next accountable action. Use separate cohorts rather than one blended transfer percentage. Review ordinary and boundary cases, including a customer who changes the request during the handoff and a case where the intended specialist is unavailable. A test can establish how the sampled route behaved; it cannot prove every transfer is avoidable, that fewer transfers are always better, or that an external legal requirement has been met. Document unavailable recordings, incomplete notes, and any cases removed from analysis.

The evidence-led conclusion is that transfer quality is preserved work plus accepted responsibility. If the sender’s purpose, minimum necessary context, destination, authority, and next action are visible, the research can show where the route held or failed. If only the connection is visible, the result should remain uncertain. Re-test after a queue, script, system, or staffing change. That disciplined distinction helps an offshore call center improve handoffs without turning a convenient operational signal into an unsupported claim about customer resolution or provider performance.`];
const body=[...paragraphs,...evidenceNotes].join(' ');
export const august20ResearchEscalation:readonly ResearchPost[]=[{slug:'offshore-call-center-context-receipt-study',title:'Offshore call center transfers: research evidence that customer context survived',excerpt:'A bounded study of transfer purpose, minimum context, receiving acceptance, and repeat work in an offshore call center.',published:'2026-08-20',modified:'2026-08-22',revision:'2026-08-22-offshore-call-center-context-receipt-service-handoff-v2',readingMinutes:11,wordCount:body.split(/\s+/).length,methodology:'We compare source guidance with reason-specific transfer cohorts and defined handoff tests across channels and shifts.',limitations:'The evidence cannot prove every transfer is avoidable, that fewer transfers are better, or that any legal requirement is satisfied.',keyTakeaways:['A connected call is not accepted ownership.','Transfer reasons need separate cohorts.','Minimum necessary context protects customers and receivers.'],stats:[],sections:paragraphs.map((p,i)=>({heading:i===0?'Research question and finding':i===13?'Evidence-led conclusion':`Transfer evidence ${i+1}`,paragraphs:[{text:p,citations:[1,2,3]}]})),table:{caption:'Transfer evidence boundary',headers:['Evidence','Supports','Does not prove','Next question'],rows:[['Context','Usable handoff','Resolution','Was it accepted?'],['Return contact','Friction signal','Root cause','What failed?']]},buyerChecklist:[],contextualService:{href:'/services/inbound-customer-care',label:'Plan Philippines customer care coverage',text:'If the transfer test exposes repeat explanations or unclear ownership, start with a narrow queue and written handoff rules. The Philippines customer care service page shows the routine work, controls, and first-week checks to define before coverage begins.'},faqs:[{q:'Does a connected transfer prove success?',a:'No. The receiver must accept usable context and authority.'}],related:[{title:'Research library',href:'/research'}],sources}];
