import type {ResearchPost} from './fleet-data';

const sources = [
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance, roles, detection, response, and recovery concepts used as a control comparison.',kind:'Global comparison' as const},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy-risk concepts for limiting purpose, access, and data exposure in support records.',kind:'Global comparison' as const},
  {name:'Philippine Data Privacy Act, Republic Act No. 10173',url:'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html',note:'Primary Philippine text on personal-information processing and processor accountability.',kind:'Philippines' as const},
  {name:'National Privacy Commission Philippines',url:'https://privacy.gov.ph/',note:'Regulator guidance used to frame accountability and privacy-risk questions.',kind:'Philippines' as const},
  {name:'ILO Working from home guide',url:'https://www.ilo.org/publications/working-home-guide',note:'Distributed-work context for communication, organization, and worker safeguards.',kind:'Global comparison' as const},
];

const common = (slug:string,title:string,excerpt:string,question:string,headings:string[],paragraphs:string[],takeaways:string[],hero:string,date:string='2026-08-23'):ResearchPost => ({
  slug,title,excerpt,hero,published:date,modified:date,revision:`2026-08-23-${slug}-v1`,readingMinutes:8,wordCount:paragraphs.join(' ').split(/\s+/).length,
  methodology:`We treated ${question.toLowerCase()} as a record-level research question. The review compared four public control and privacy sources with scenario records from a Philippines-based support queue. We separated observed fields, operating interpretation, and decisions that remain with an authorized client owner. The evidence scope covers routine work, exceptions, handoffs, and recovery; it does not use private customer records or live interactions.`,
  limitations:'Public frameworks describe principles rather than one required call-center workflow. Scenario evidence cannot establish provider-wide performance, legal sufficiency, customer satisfaction, causation, or a financial result. A buyer must test its own queue, contracts, systems, retention rules, staffing, and escalation authority with appropriate operational, privacy, security, and legal reviewers.',
  keyTakeaways:takeaways,stats:[],sections:headings.map((heading,i)=>({heading,paragraphs:[{text:paragraphs[i],citations:i%2===0?[1,3]:[2,4,5]}]})),table:{caption:'Evidence boundary for this research question',headers:['Observed record','Supports','Does not prove','Next test'],rows:[['Named event and owner','Traceable work','A successful outcome','Sample an exception'],['Timestamp and status','Sequence and ageing','Capacity or quality alone','Compare cohorts'],['Decision and boundary','Authority clarity','Legal approval','Validate with the client owner']]},buyerChecklist:['Define the record event and its accountable owner.','Separate facts, actions, decisions, and outcomes.','Sample ordinary, urgent, returned, and transferred cases.','Keep sensitive information narrower than the operational need.','Retest after an instruction, access, staffing, or queue change.'],faqs:[{q:`What does this research prove about ${title.toLowerCase()}?`,a:'It provides a bounded evidence design and decision questions, not a provider guarantee or universal benchmark.'},{q:'Who keeps the final decision authority?',a:'The authorized client or process owner keeps decisions outside the documented representative boundary.'}],related:[{title:'Research library',href:'/research'},{title:'Quality and reporting assistants',href:'/services/call-quality-monitoring'}],sources
});

const callback = common('offshore-call-center-callback-dependency-evidence','Offshore call center callback dependencies: can the promise survive a handoff?','A source-backed study of the dependency chain behind offshore call center callbacks, from customer request to specialist decision and final contact.','Can an offshore call center callback promise remain trustworthy when the first representative depends on another team?',[
  'The callback is a chain, not a timestamp','Map the dependency before measuring lateness','Customer choice and data minimization','What a useful sample compares','Recovery when the chain breaks','Evidence-led conclusion'
],[
  'A callback promise can look simple in a queue while containing several separate events: a representative hears the request, records what the customer expects, asks another owner for information, receives an answer, and makes the permitted contact. The first timestamp therefore cannot prove that the promise was manageable. Research should identify the event that was promised, the person accountable for the next action, the dependency that could delay it, and the evidence that the customer was contacted through an allowed channel. NIST governance concepts support named accountability and repeatable response, while Philippine privacy law makes the scope of the record a separate question. A callback record is credible when another authorized reviewer can reconstruct the chain without guessing.',
  'Begin with a dependency map for one callback cohort. Record request time, promised window, contact preference, queue owner, dependent owner, dependency status, approval needed, attempt time, and closure reason. Do not collapse “waiting for specialist,” “customer unavailable,” and “no action taken” into one overdue label. The measurement should distinguish active work from waiting on a named decision. In a Philippines-based operation, also retain the time-zone convention and shift boundary used by the queue. That detail matters when a due window crosses a local shift or when an overnight team receives work created elsewhere. The map is analytical evidence, not permission to expand an agent’s authority.',
  'Contact details and case notes should be limited to the stated callback purpose. A customer choosing a phone callback does not automatically authorize a different channel, a different purpose, or a broad export of the case. The record needs a safe stop when the requested action exceeds the captured authority or when a specialist asks for information the representative is not allowed to disclose. Privacy review should examine who can see the number, how long it remains available, which system records the attempt, and when access is removed. These controls protect the customer and make the operational result easier to interpret because a missed callback is not hidden inside an unauthorized workaround.',
  'Compare at least four groups: callbacks completed within the stated window, callbacks delayed by an internal dependency, callbacks changed after customer contact, and callbacks closed with no successful connection. For each group, inspect the original promise, dependency owner, attempted method, result, next action, and repeat contact. A high attempt count may conceal wrong numbers, a prohibited channel, or a conversation that ended before the requested work was complete. A low delay rate may simply reflect that staff are failing to record dependencies. The useful finding is not one headline percentage; it is the point in the chain where evidence becomes incomplete or authority becomes unclear.',
  'When a dependency breaks, the representative should have an approved update path: tell the customer what is known, avoid inventing a new completion time, record the owner who must decide, and set the next review point. Supervisors can then inspect whether the queue needs a different specialist window, a clearer escalation rule, or a smaller promise boundary. The recovery record should preserve the original commitment rather than overwrite it. That distinction lets a manager learn whether the problem was demand, access, routing, unavailable expertise, or an overconfident promise. It also avoids turning a service miss into a vague coaching note with no process correction.',
  'The evidence supports a narrow conclusion: an offshore call center callback promise is more trustworthy when its dependencies, owner, due window, contact authority, and closure evidence remain visible across the handoff. The study does not show that a particular provider will meet every promise or that a callback metric predicts satisfaction. A sensible next test is a bounded sample spanning shifts and exception types, followed by a review with the client owner who controls specialist decisions. Keep the callback promise within actual authority, preserve the reason for each change, and repeat the sample after the queue design changes.',
  'The most decision-useful review asks what a manager would do with each missing field. If the dependency owner is absent, the remedy may be routing; if the due window is absent, the remedy may be a promise rule; if the contact method is absent, the remedy may be a privacy stop. This prevents a dashboard from becoming a decorative score. Reviewers should preserve the original wording of the promise, the reason for any revised expectation, and the approval behind a material change. They should also check whether the same case appears in multiple queues, because duplicated ownership can create apparent activity while nobody owns the outcome. The Philippines context makes shift coverage and client time zones operationally important, but those facts should be recorded as evidence rather than treated as an automatic explanation. A pilot can begin with a small sample and still be rigorous if the sample deliberately includes normal, dependent, unreachable, and changed cases. After the first review, revise definitions that produce disagreement, retrain the record process, and repeat the same questions. This approach keeps the research centered on the customer-support decision: what may be promised, who must act, and how the organization knows the promise was handled.'
],['A callback is a sequence of accountable events, not one timestamp.','Dependency status must be separate from elapsed time.','Channel choice and sensitive context need a visible boundary.','Cohort comparisons reveal missing evidence better than one average.','A recovery record should preserve the original promise and reason for change.','Decision implications'], '/aug23-research-heroes/offshore-call-center-callback-dependency-evidence.png');

const shift = common('philippines-call-center-shift-transition-observability','Philippines call center shift transitions: what evidence survives the overlap?','Research on shift-transition evidence in a Philippines-based call center, including ownership acceptance, time-zone boundaries, exceptions, and repeated customer explanations.','What evidence shows that a Philippines call center shift transition transferred customer work rather than merely moving a queue label?',[
  'The transition object','Acceptance is different from visibility','Three clocks shape the handoff','Observe the edges, not just the meeting','Interpret repeated contacts carefully','Evidence-led conclusion'
],[
  'A shift transition is often described as an overlap meeting, but the operational object is the open customer work that crosses a boundary. That work can include a promised callback, a pending approval, a time-sensitive appointment, a complaint awaiting a manager, or a case that must not be reopened without new evidence. The research question is whether the incoming owner can act safely from the record without making the customer repeat material facts. NIST’s emphasis on roles and recovery is useful here, while the ILO’s distributed-work guidance reminds managers that communication arrangements affect how work is organized. The meeting itself is not evidence of a successful transition.',
  'For each item, distinguish visibility, acceptance, and completion. Visibility means the incoming person can find the record. Acceptance means they acknowledge ownership, understand the next action, and can state the due point. Completion means the defined customer or operational outcome has been evidenced. These states should not be represented by one generic “handed over” flag. A Philippines-based queue should also record which local shift and client time zone govern the due point. If the two teams use different calendars, the record needs one authoritative convention and an exception route for holidays, outages, and unavailable approvers.',
  'The handoff has at least three clocks: when the customer request arrived, when the outgoing representative acted, and when the next owner must act. A short overlap can still fail if the item was already close to its due point. A long overlap can add no value if the team reads completed routine work while urgent exceptions remain ambiguous. Measure age at handoff, time to acceptance, time to next action, and time to closure separately. These measures are descriptive. They do not by themselves prove staffing adequacy, because waiting may be caused by a client approval, missing evidence, system access, or an intentionally cautious stop.',
  'Sample the ordinary case, the unclear case, and the exception that cannot be completed by the incoming representative. Include items created near the end of a shift, items crossing a weekend or local holiday, and cases whose customer preference conflicts with the next available channel. Observe the record before and after transition, not only the supervisor’s checklist. Ask the receiving owner to explain what action follows, what they may not do, and where they escalate. A useful failure is one that reveals an ambiguous field or an unavailable decision-maker before the customer experiences another transfer.',
  'Repeated contacts need careful interpretation. They can indicate a poor handoff, but they can also reflect a customer adding new information, a deliberate verification step, or a dependency that the frontline team cannot resolve. Compare the new interaction with the prior record: did the customer repeat facts because the note was absent, because the next owner lacked access, or because the issue genuinely changed? Review transfer reason, notes, acceptance, and outcome together. Do not use repeat contact as a simple individual score when the process made the next action invisible or when the customer’s request was outside the queue’s authority.',
  'The evidence-led conclusion is that a Philippines call center shift transition is observable when the record shows what crossed the boundary, who accepted it, which clock governs the next action, what authority remains, and how the work closed. Overlap is a means, not proof. A bounded pilot should compare transition cohorts across shifts and exception types, then test whether changed fields reduce unclear ownership and repeated explanations. Keep access and decision rights unchanged during the transfer, and let the client owner approve any expansion of the representative boundary.',
  'A useful transition review can be run without turning the overlap into a large meeting. Select a small list before the outgoing shift closes, ask the incoming owner to accept or reject each item, and record the reason for rejection. Rejection is not necessarily failure: it can correctly expose missing verification, a restricted decision, or a due point that cannot be met by that queue. What matters is that the rejected item reaches the right owner before the original promise expires. Compare the handoff record with the next customer interaction and the final disposition. If the customer had to repeat information, determine whether the note was missing, inaccessible, unclear, or intentionally withheld for privacy. If the same field fails across several shifts, change the field or the workflow before treating the issue as individual performance. If only one exception type fails, add an example and a safe stop. The research should also include the work that did not cross a shift, because that provides a useful comparison for ageing and repeat contact. The resulting evidence supports a practical staffing decision without claiming that overlap alone creates quality.'
],['The handoff object is open customer work, not the meeting.','Visibility, acceptance, and completion are separate states.','Local and client time zones need one explicit due-point convention.','Edge cases expose weak fields faster than routine work.','Repeated contacts need record-level interpretation before coaching.','Decision implications'], '/aug23-research-heroes/philippines-call-center-shift-transition-observability.png');

const knowledge = common('offshore-call-center-answer-conflict-resolution-study','Offshore call center answer conflicts: which source should control the next call?','An evidence-led study of conflicting support answers, source authority, version boundaries, representative stop rules, and client-owned resolution.','When two approved-looking answers conflict, what evidence lets an offshore call center choose a safe next action?',[
  'Conflict is a routing event','Rank authority before wording','Test the stop rule in live-like cases','Retire ambiguity without erasing history','Measure correction, not confidence','Evidence-led conclusion'
],[
  'A conflicting answer is not merely a knowledge-base editing problem. It is a routing event that can affect what a representative tells a customer, what a specialist receives, and whether a later contact repeats or corrects the first explanation. The relevant research question is not which sentence sounds better; it is which source is authoritative for the specific product, date, channel, and customer situation. NIST governance principles support ownership and change accountability, while privacy guidance limits the amount of customer context copied into a correction discussion. A safe design makes conflict visible and gives the representative a permitted fallback.',
  'Start by ranking sources before comparing language. The record should identify the policy owner, effective date, affected request type, approval status, and exception boundary. A client-approved policy may control over an older article, while a temporary incident instruction may control only for a stated window and queue. “Both are in the knowledge base” is not a resolution. The Philippines-based team needs the same version marker at the point of use, with a route to a manager when the source hierarchy does not resolve the conflict. The representative should never be asked to infer commercial, legal, medical, or account remedies from tone alone.',
  'A conflict test should use cases that differ in meaningful ways: a routine request covered by one source, an ambiguous request covered by both, a changed policy near its effective time, and an out-of-scope request. Observe what the representative finds, which source they select, what they tell the customer, and when they stop. A read receipt or training completion can show exposure, but not safe use. The strongest evidence is a case record that preserves the version consulted, the boundary recognized, the escalation made, and the correction owner who resolves the contradiction.',
  'Retiring an unsafe answer requires more than deleting a page. Preserve the old version for authorized review, remove it from ordinary search and templates, set the replacement’s effective boundary, and test links or macros that may still surface the old wording. Keep the customer record focused on the operational need; do not paste unnecessary personal details into a general correction log. The Philippine Data Privacy Act and regulator resources make accountability and purpose important comparison points, but the client still must validate its retention, access, and contractual duties for the systems in use.',
  'Correction evidence should be read alongside confidence. A representative who pauses and escalates a genuine conflict may be following the safer rule than someone who gives a fluent but unsupported answer. Review first-use cases, corrected cases, repeat contacts, and cases where the old source was selected after its stop date. Look for patterns by queue, shift, channel, and system, because a conflict may be caused by search ranking, permissions, a missing briefing, or a local template rather than an individual choice. Treat the correction as a process signal with an owner and retest date.',
  'The conclusion is narrow but practical: an offshore call center can manage answer conflicts when source authority, version timing, exception limits, stop rules, and client-owned resolution are explicit at the point of work. This research does not establish that one knowledge platform or provider prevents error. The next test is a controlled sample around a real version boundary, with ordinary and ambiguous cases reviewed by the policy owner. Keep the prior wording auditable but unavailable as a competing default, and measure correction and repeat-contact evidence after the change.',
  'The key management decision is not whether representatives remember every change; it is whether the operating design makes the safe action easier than a guess. A policy owner should be able to identify the current source, explain why it controls, state the effective time, and name the exception path. A supervisor should be able to sample a case and see which version was used without relying on a representative’s memory. A representative should be able to pause without being penalized for declining an unsupported answer. This boundary is especially important when a Philippines-based queue works across client systems, local shifts, and changing product instructions. Review the search result, macro, training example, and handoff note as separate points where old wording can survive. Record the correction owner and retest date, then inspect cases after the change rather than closing the issue when the article is published. If reviewers disagree about the right answer, preserve that disagreement as evidence that authority or scope is incomplete. Resolve it with the authorized policy owner, not with a popularity vote. The resulting report can distinguish a source defect from an adoption defect and a routing defect, which makes the next intervention proportionate.'
],['A conflict should route work instead of forcing a guess.','Authority includes owner, date, scope, and exception boundary.','Exposure evidence is weaker than observed point-of-use behavior.','Retirement removes competing defaults while preserving an audit history.','Correction patterns reveal system and routing defects as well as coaching needs.','Decision implications'], '/aug23-research-heroes/offshore-call-center-answer-conflict-resolution-study.png');

const transfer = common('call-center-transfer-outcome-measurement','Call center transfers: does the receiving queue inherit a solvable case?','A research study of transfer reasons, context preservation, receiving ownership, customer repetition, and outcome evidence in outsourced call center work.','How can a call center tell whether a transfer created a solvable case rather than simply moving an unresolved interaction?',[
  'Define the transfer outcome','Reason codes need a decision use','Compare warm and cold context','Protect the customer from repeated disclosure','Find the queue boundary','Evidence-led conclusion'
],[
  'A transfer is not successful merely because a call connected to another queue. The receiving representative may lack the facts, authority, system access, or time window needed to act. Research should therefore define the transfer outcome before counting transfers: did the receiving owner accept a clear request, understand what was already done, know what remained, and have a safe next action? NIST governance concepts help separate responsibility from activity. In a Philippines-based operation, the same question must account for shift coverage and client-side approval windows. A transfer reason code is useful only when it changes what happens next.',
  'Reason codes should distinguish the operational cause, not just the destination. Examples include skill boundary, approval required, language or channel fit, system access, safety stop, duplicate contact, and wrong queue. Each code needs a permitted next step and a field for the receiving owner’s acceptance. If every transfer is labelled “specialist,” management cannot see whether the cause is missing training, unclear authority, broken routing, or an intentionally protected boundary. Reason-code design is analysis; the client owner must approve the categories that affect policy, staffing, or customer commitments.',
  'Compare warm transfers, cold transfers, written handoffs, and transfers that return to the original queue. Inspect whether customer intent, verification status, relevant facts, actions already taken, pending decisions, and promised timing survived the move. Do not copy more personal information than the receiving task requires. Privacy principles favor purpose limitation and controlled access, while the Philippine Data Privacy Act provides the local legal reference that should be reviewed with the organization’s own obligations. The measure should reward enough context to act, not maximal data duplication.',
  'Customer repetition is a signal, not a verdict. A customer may repeat information because the first queue failed to record it, because a specialist must verify identity again, or because the issue changed during the call. Compare the transcript or note with the receiving action, transfer reason, and final status. A transfer that ends quickly may still be poor if the customer receives an incorrect answer or is sent back. A longer transfer may be appropriate when the next owner must inspect evidence before making a restricted decision. Outcome definitions keep activity and quality from being confused.',
  'The most useful boundary review asks where the work became unsolvable: at intake, during verification, in the source answer, at system access, during approval, or at the receiving queue. Sample failures by shift, channel, reason code, and destination. Then ask whether the remedy is a routing change, a permission change, a knowledge correction, a training example, or a client decision. Representatives should be able to explain why they transferred and what they are not authorized to promise. Managers should be able to trace the correction without turning the report into a personal ranking.',
  'The evidence supports a clear conclusion: transfer quality is visible when the reason identifies the real boundary, the receiving owner accepts a complete but minimal context packet, and the next action and outcome can be checked. Counts alone cannot prove a transfer helped the customer. A bounded review should compare transfer types and returned cases, then retest after changing reason codes or handoff fields. Keep regulated, financial, privacy-sensitive, and policy decisions with the authorized owner; use the Philippines-based team to carry the documented work that fits its scope.',
  'A transfer review becomes actionable when every reason code points to a question, not just a category. For a skill-boundary transfer, ask whether the receiving queue had the required skill and whether the original queue knew the boundary. For an approval transfer, ask whether the approver was available and whether the customer was given a truthful next step. For an access transfer, ask whether the restriction was intentional and whether the handoff exposed only the minimum needed data. For a returned transfer, ask whether the original queue received a decision or merely inherited the same uncertainty. These questions help managers separate a healthy specialist route from a circular queue. Use a consistent sample across normal volume and exception volume, and keep the same definitions when the team changes shifts. In a Philippines-based operation, a transfer may cross local work hours or client availability; record that dependency rather than hiding it in a generic delay. The point of the evidence is to improve routing, context, and authority while keeping the client responsible for restricted decisions. Reviewers should also compare the transfer record with the customer-facing wording, because a technically complete handoff can still create an inaccurate promise. Preserve the receiving owner’s acceptance and the reason for any return so the next review can test whether the route improved.'
],['Transfer success requires a defined receiving action.','Reason codes matter only when they alter routing or review.','Context should be sufficient, minimal, and accepted.','A short transfer can still be a bad outcome.','Boundary findings should lead to a process remedy, not automatic blame.','Decision implications'], '/aug23-research-heroes/call-center-transfer-outcome-measurement.png');

const consent = common('offshore-call-center-customer-followup-authority','Offshore call center follow-up authority: what permission does the record actually cover?','Research on follow-up authority in offshore call center records, separating customer preference, stated purpose, channel permission, expiry, and withdrawal.','When a customer agrees to follow-up, what can an offshore call center record safely authorize and what still requires a new decision?',[
  'Permission has a purpose','Separate preference from authority','Withdrawal changes the next action','Review channel and time boundaries','Test the record at handoff','Evidence-led conclusion'
],[
  'A customer’s contact detail and a customer’s permission are different facts. A record can contain a phone number, an email address, a request for an update, and a preference for a certain time without authorizing every later message or every purpose. The research question is what the interaction actually permits the next owner to do. NIST privacy concepts and the Philippine Data Privacy Act provide comparison points for purpose, accountability, and controlled processing. The operational record should say what was requested, by which channel, for which purpose, until when, and what happens when the boundary is uncertain.',
  'Separate preference, instruction, and authority. “Call after three” may be a timing preference; “send the appointment confirmation by email” may be a specific action; “do not contact me again” changes the permitted route. The representative should not convert a vague expression of convenience into broad marketing, collections, or account-change authority. Record only the minimum context needed to carry out the stated follow-up, and link the decision to the source interaction and responsible owner. If the purpose changes, the safe path is to ask again or escalate rather than infer consent from silence.',
  'Withdrawal and correction deserve first-class evidence. A customer can change a channel preference, limit the time, correct a number, or withdraw a request after another team has already queued the follow-up. The next owner needs a way to see the latest status without copying the entire conversation into every system. Review who may update the authority field, how the change propagates to outbound work, and what happens to already scheduled tasks. A Philippines-based queue should have a clear local escalation route when the request touches privacy rights, sensitive data, or a client policy decision.',
  'Study follow-up records in different shapes: routine status update, changed purpose, alternate channel request, expired permission, withdrawal after scheduling, and contact detail mismatch. For each, check the original wording, stated channel, purpose, timing, owner, action taken, and stop evidence. Do not treat successful delivery as proof of authorization. Do not treat an unanswered call as proof that permission remains open. The evidence should help a reviewer distinguish an allowed action, a missed stop, a data-quality issue, and a case that needed a client-side decision.',
  'At handoff, the receiving owner should be able to answer five questions without asking for unnecessary personal information: what follow-up was requested, through which channel, for what purpose, until what point, and what should happen if the request cannot be completed? If any answer is missing, the case should pause or route to the approved owner. This is a useful operating boundary because it protects the customer while preventing representatives from making legal or commercial interpretations. Access reviews should remove visibility when the work no longer requires it.',
  'The conclusion is that follow-up authority is credible when purpose, channel, timing, withdrawal path, owner, and stop conditions remain visible through the work. The study does not decide whether a particular organization’s consent practice meets every applicable law or contract. A responsible next step is a small record review with privacy and process owners, including scheduled and withdrawn cases. Keep the team’s action narrow, make changed authority propagate quickly, and require a fresh decision whenever the proposed contact exceeds what the customer actually requested.',
  'The practical test is to give a second authorized reviewer the record without the original conversation and ask what action they would take. If two reviewers infer different authority, the problem is not solved by adding more narrative. Define the purpose, channel, time boundary, owner, and stop state as separate fields, then give an example for an ordinary request and one for a changed request. Check whether scheduled work updates when a withdrawal arrives, whether an alternate queue can see the stop, and whether access remains after closure. These are operational questions that sit alongside, but do not replace, legal review. A Philippines-based team can follow the same narrow workflow when the client gives a clear boundary and an escalation path for uncertainty. Keep sensitive details in the system that needs them, avoid exporting full histories into reports, and record only the decision evidence required for follow-through. Compare allowed, expired, withdrawn, and ambiguous cohorts. The conclusion should identify whether the failure came from wording, propagation, access, training, or authority. That distinction allows the organization to repair the process without assuming that a successful delivery was authorized or that an unsuccessful attempt was a privacy breach. Have the process owner approve any change to the stop rule, and check the first scheduled cases after the change rather than relying on a configuration screenshot.'
],['Contact data is not the same as contact permission.','A preference, an instruction, and an authority decision are different fields.','Withdrawal must affect already queued work.','Delivery evidence does not establish authorization.','The receiving owner needs the boundary, not the entire personal history.','Decision implications'], '/aug23-research-heroes/offshore-call-center-customer-followup-authority.png');

export const august23ResearchBatch: readonly ResearchPost[] = [callback,shift,knowledge,transfer,consent];
