import type {ResearchPost} from './fleet-data';
const sources:ResearchPost['sources']=[
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Primary governance, protection, response, and recovery framework.',kind:'Global comparison'},
 {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Primary framework for privacy risk and data-processing outcomes.',kind:'Global comparison'},
 {name:'Republic Act No. 10173 — Data Privacy Act of 2012',url:'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html',note:'Official Philippine statutory text used for context, not legal advice.',kind:'Philippines'},
 {name:'National Privacy Commission Philippines',url:'https://privacy.gov.ph/',note:'Official regulator resources on privacy accountability.',kind:'Philippines'},
 {name:'ISO 18295-1:2017 overview',url:'https://www.iso.org/standard/64739.html',note:'International contact-centre requirements used as a comparison point.',kind:'Global comparison'},
];
type Spec={slug:string;title:string;excerpt:string;question:string;unit:string;fields:string;cohorts:string;finding:string;decision:string;limits:string;takeaways:string[]};
const make=(s:Spec):ResearchPost=>{const sections=[
 {heading:'Research question and evidence boundary',text:`${s.question} This September 4, 2026 report uses ${s.unit} as its unit of analysis. It proposes a bounded record review for a Philippines-based support operation and compares observations with five named governance, privacy, and contact-centre sources. Public frameworks help define questions; they do not prove what happened in a particular queue.`},
 {heading:'Record reconstruction method',text:`For each unit, preserve ${s.fields}. A reviewer should reconstruct the trigger, verified facts, permitted action, customer message, and accepted next owner without guessing. A timestamp or sent status proves activity only. Missing evidence remains a limitation rather than becoming a favorable result.`},
 {heading:'Comparison groups and counterexamples',text:`Compare ${s.cohorts}. Stratify by channel, shift, request type, source version, and need for client authority. Read the cases behind every count. A careful stop may protect a customer even when handling time rises; a quick closure can conceal an inaccurate promise. Differences suggest a test but do not establish causation.`},
 {heading:'Privacy and authority boundary',text:'Use only the operational context needed for the comparison and restrict records to authorized reviewers. Do not copy unrelated personal history into calibration files. Philippine law and regulator materials provide context, not a legal conclusion. Disclosure, payment, account, retention, safety, and exception decisions remain with the designated client or specialist owner.'},
 {heading:'Finding and controlled decision',text:`The evidence-led finding is narrow: ${s.finding} The supported next step is to ${s.decision}. Change one control, retain the definitions and sample frame, and repeat the comparison. Record counterexamples, exclusions, and unresolved questions rather than converting a limited study into a guarantee.`},
 {heading:'Limitations and conclusion',text:`${s.limits} This design cannot establish legal compliance, causation, satisfaction, capacity, financial impact, or provider-wide quality. Results depend on the selected period, queues, channels, definitions, and record completeness. Buyers should validate the boundary with their authorized owners.`},
 ];return {slug:s.slug,title:s.title,excerpt:s.excerpt,hero:'/offshore-call-center-agent.jpg',published:'2026-09-04',modified:'2026-09-04',revision:`2026-09-04-${s.slug}-v1`,readingMinutes:8,wordCount:sections.map(x=>x.text).join(' ').split(/\s+/).length,methodology:`A bounded scenario-record comparison using ${s.unit}, explicit cohorts, counterexamples, and five named primary or standards sources.`,limitations:s.limits,keyTakeaways:s.takeaways,stats:[],sections:sections.map((x,i)=>({heading:x.heading,paragraphs:[{text:x.text,citations:i===3?[2,3,4]:i===2?[1,5]:[1,2,5]}]})),table:{caption:'Evidence and decision boundary',headers:['Evidence','Supports','Does not prove','Next check'],rows:[[s.fields.split(',')[0],'Event identification','Correct outcome','Read the source record'],['Owner and acceptance','Accountability','Adequate staffing','Compare cohorts'],['Recorded boundary','Permitted action','Legal compliance','Validate with owner']]},buyerChecklist:['Define the event and owner.','Preserve source, time, dependency, and next action.','Sample routine and exception cases.','Keep exclusions visible.','Change one control and retest.'],faqs:[{q:`What does this report establish about ${s.title.toLowerCase()}?`,a:'A bounded evidence design and management test, not a benchmark, legal conclusion, or provider guarantee.'},{q:'Who owns decisions outside the workflow?',a:'The authorized client or specialist owner.'}],related:[{title:'Research library',href:'/research'},{title:'Call quality monitoring',href:'/services/call-quality-monitoring'}],sources};};
export const september4ResearchBatch:readonly ResearchPost[]=[
 make({slug:'offshore-call-center-acknowledgement-gap-study',title:'Offshore call center acknowledgement gaps: when does a handoff become owned?',excerpt:'A bounded study of sent, received, accepted, returned, and unowned work across offshore shifts.',question:'Which signals distinguish movement between queues from accepted ownership?',unit:'one case from first handoff attempt through accepted next action',fields:'handoff reason, verified need, sending owner, receiver, sent time, acknowledgement, due point, return reason, and customer update',cohorts:'accepted handoffs, delayed acknowledgements, specific returns, repeated bounces, and cases with no receiver',finding:'a queue change proves movement; ownership is defensible only when a capable receiver accepts the case and its due commitment.',decision:'pilot an explicit acceptance state and timed backup route for one queue',limits:'A system status may not show that a person understood the record, and a small sample may omit rare high-risk handoffs.',takeaways:['Sent and accepted are different events.','A return should name the missing requirement.','The customer promise must survive.']}),
 make({slug:'philippines-call-center-coverage-authority-overlap-research',title:'Philippines call center coverage-authority overlap: measuring reachable decision windows',excerpt:'Research on whether offshore hours overlap with the client owners needed for restricted decisions.',question:'How can a buyer test queue coverage separately from decision-authority coverage?',unit:'one restricted request from frontline stop through authorized response',fields:'Philippines shift, customer time zone, request class, stop, owner hours, sent time, acceptance, interim wording, and decision',cohorts:'requests inside and outside overlap, during holidays, and with or without a designated backup',finding:'round-the-clock intake does not establish round-the-clock authority; the measurable gap runs from restricted request to accepted decision route.',decision:'map restricted requests to real owner windows and test a backup acknowledgement period',limits:'Published schedules can differ from actual availability, and this study cannot determine contractual sufficiency.',takeaways:['Staffed hours and decision hours differ.','Interim language should not invent outcomes.','Holidays belong in the sample.']}),
 make({slug:'call-center-note-correction-propagation-research',title:'Call center note-correction propagation: does repaired information reach the next action?',excerpt:'An evidence study of material corrections, downstream notices, and customer-facing consequences.',question:'What evidence shows that corrected information reached decisions based on the original?',unit:'one material note error from detection through downstream acknowledgement',fields:'original note, error evidence, corrected fact, time, author, affected records, downstream owners, acknowledgement, and impact',cohorts:'corrections before action, after internal action, after customer contact, and without downstream acknowledgement',finding:'editing a source record does not prove the correction reached people, queues, or messages that used the old information.',decision:'add an affected-owner checklist and acknowledgement for material corrections',limits:'The review depends on traceable links between systems; missing logs can hide success and failure.',takeaways:['A corrected source is the first event.','Materiality sets the notice path.','Silent overwrites weaken reconstruction.']}),
 make({slug:'offshore-call-center-safe-hold-conversion-study',title:'Offshore call center safe-hold conversion: when should a live wait become a callback?',excerpt:'A comparison of hold duration, callback permission, context retention, ownership, and outcomes.',question:'Which evidence supports converting a long hold into an owned callback?',unit:'one live interaction from first hold through resumed service or callback completion',fields:'hold reason, start time, preference, callback permission, contact source, context, owner, promised window, and completion',cohorts:'short holds, customer-requested callbacks, agent-proposed callbacks, failed attempts, and shift-crossing holds',finding:'a callback reduces an unproductive wait only when permission, context, a realistic window, and accepted ownership travel together.',decision:'test a callback offer at one defined threshold with explicit acceptance',limits:'Duration does not capture the customer’s private cost of waiting, and no scenario study sets a universal threshold.',takeaways:['A callback is a new promise.','Permission matters.','The receiver accepts the window.']}),
 make({slug:'philippines-call-center-knowledge-link-resilience-research',title:'Philippines call center knowledge-link resilience: studying answer access failures',excerpt:'Research on broken links, conflicting cached guidance, safe stops, repair time, and corrections.',question:'How should an offshore operation measure inaccessible or conflicting knowledge at the point of work?',unit:'one customer question encountering an unavailable or contradictory source',fields:'question class, source URL, version, failure, alternate source, action, owner, customer wording, repair time, and correction',cohorts:'working links, broken links with an alternate, conflicting sources, access denials, and failures found after an answer',finding:'a published article is not operationally available when the assigned person cannot open, identify, and apply the correct version.',decision:'monitor point-of-work failures and provide one version-controlled escalation route',limits:'Simulated questions may not represent demand, and availability alone cannot show that guidance is understandable or correct.',takeaways:['Publication does not prove access.','Cached guidance needs a version boundary.','Late discoveries need correction.']}),
];
