import type {ResearchPost} from './fleet-data';

const sources:ResearchPost['sources']=[
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Primary framework for governance, protection, detection, response, and recovery controls.',kind:'Global comparison'},
 {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Primary framework for identifying and managing privacy risk.',kind:'Global comparison'},
 {name:'Republic Act No. 10173, Data Privacy Act of 2012',url:'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html',note:'Official Philippine statutory text used for operational context, not legal advice.',kind:'Philippines'},
 {name:'National Privacy Commission Philippines',url:'https://privacy.gov.ph/',note:'Official regulator material on privacy accountability and data protection.',kind:'Philippines'},
 {name:'ISO 18295-1:2017 overview',url:'https://www.iso.org/standard/64739.html',note:'International contact-centre requirements used as a comparison point.',kind:'Global comparison'},
];
type Study={slug:string;title:string;excerpt:string;question:string;unit:string;evidence:string;cohorts:string;finding:string;pilot:string;limits:string;takeaways:readonly string[]};
const make=(s:Study):ResearchPost=>{
 const sections=[
  {heading:'Research question and bounded scope',text:`${s.question} The unit of analysis is ${s.unit}. This September 9, 2026 report proposes a bounded operational review for a Philippines-based support team. It is not a provider benchmark, a legal opinion, or proof that one workflow caused an outcome.`},
  {heading:'Method and evidence',text:`Choose the queue, review window, and eligibility rules before sampling. Preserve ${s.evidence}. Trace each case from the first observable event to the defined end point. Record missing fields as missing, retain excluded cases, and have a second reviewer classify ambiguous records without seeing the first label.`},
  {heading:'Comparison and interpretation',text:`Compare ${s.cohorts}. Keep request type, channel, shift, customer promise, authority needs, and system availability visible. Counts describe the selected records only. Read representative cases and counterexamples before explaining a difference.`},
  {heading:'Privacy, authority, and inference limits',text:'Collect only the evidence needed for the stated review and restrict it to authorized reviewers. The Philippine law and regulator materials below provide context rather than a compliance conclusion. Client or specialist owners retain decisions about identity, disclosure, payment, safety, retention, and exceptions.'},
  {heading:'Bounded finding and pilot',text:`The limited operational proposition is that ${s.finding} Test it by ${s.pilot}. Change one control, keep definitions stable, and compare the next bounded sample with the baseline. Preserve contrary cases and unintended effects.`},
  {heading:'Limitations',text:`${s.limits} This design cannot establish causation, customer intent, legal compliance, staffing adequacy, financial impact, or organization-wide quality. Its usefulness depends on complete source records, stable definitions, a disclosed period, and careful reviewer judgment.`},
 ];
 const wc=sections.map(x=>x.text).join(' ').split(/\s+/).length;
 return {slug:s.slug,title:s.title,excerpt:s.excerpt,hero:'/offshore-call-center-agent.jpg',published:'2026-09-09',modified:'2026-09-09',revision:`2026-09-09-${s.slug}-v1`,readingMinutes:8,wordCount:wc,methodology:`Bounded record review using ${s.unit}, explicit cohorts, retained exceptions, blinded second review of ambiguous cases, and five named primary or standards sources.`,limitations:s.limits,keyTakeaways:s.takeaways,stats:[],sections:sections.map((x,i)=>({heading:x.heading,paragraphs:[{text:x.text,citations:i===3?[2,3,4]:i===2?[1,5]:[1,2,5]}]})),table:{caption:'Evidence and inference boundary',headers:['Record element','Supports','Does not prove','Review action'],rows:[[s.evidence.split(',')[0],'An observed event','Correct outcome','Read source record'],['Accepted owner','Visible responsibility','Adequate capacity','Trace acknowledgement'],['Recorded result','A bounded status','Customer intent','Check counterexamples']]},buyerChecklist:['Define the queue, period, and eligible unit.','Preserve events, times, promises, and ownership.','Separate missing evidence from negative results.','Review ambiguous cases independently.','Change one control and repeat the sample.'],faqs:[{q:`What does this study establish about ${s.title.toLowerCase()}?`,a:'It offers a bounded review design and testable operational proposition, not a universal benchmark, causal result, or legal conclusion.'},{q:'Who decides exceptions outside the frontline routine?',a:'The authorized client, policy, privacy, security, or specialist owner retains that decision.'}],related:[{title:'Research library',href:'/research'},{title:'Call quality monitoring',href:'/services/call-quality-monitoring'}],sources};
};
export const september9ResearchBatch:readonly ResearchPost[]=[
 make({slug:'call-center-after-call-work-completeness-study',title:'After-call work completeness in call centers: a source-record study',excerpt:'A bounded method for testing whether notes preserve the facts, promises, and ownership needed for the next action.',question:'Which missing after-call fields are associated with an unusable handoff or repeated customer explanation?',unit:'one completed customer contact and its first downstream use',evidence:'source interaction, structured fields, narrative note, disposition, promise, due time, unresolved action, assigned owner, and downstream correction',cohorts:'records completed promptly or later, structured or free-text notes, routine or exception cases, usable or returned handoffs, and contacts followed by repeat explanation',finding:'note length is a poor substitute for a timely record containing the customer need, outcome, promise, and next owner.',pilot:'requiring five minimum handoff fields in one queue and comparing completeness, corrections, and repeat explanation before and after the change',limits:'Reviewers may disagree about whether a note was sufficient, and downstream users may rely on knowledge or conversations that the case system does not preserve.',takeaways:['Measure whether the next person can act.','Keep missing facts visible.','Separate documentation delay from workflow complexity.']}),
 make({slug:'offshore-call-center-shared-inbox-ownership-study',title:'Shared-inbox ownership in offshore call centers: tracing claims to customer outcomes',excerpt:'A study design for comparing claimed messages, duplicate replies, abandoned drafts, reassignment, and accepted ownership.',question:'Does a visible claim reliably connect an inbound message to one accountable response owner?',unit:'one inbound shared-inbox thread from arrival to response or the end of its promised window',evidence:'arrival time, claim event, owner, draft activity, internal note, reassignment, accepted receiver, response time, duplicate reply, and customer outcome',cohorts:'unclaimed threads, single-owner claims, reassigned work, abandoned claims, concurrent drafts, duplicate replies, and responses completed inside or outside the promised window',finding:'a claim improves visibility only when it has a due point, an active owner, and an accepted route for reassignment.',pilot:'adding claim expiry and explicit acceptance to one inbox, then tracing duplicate replies, idle claims, and response outcomes for two comparable periods',limits:'Draft activity may be unavailable, automated replies can distort response timing, and an inbox record cannot show whether the customer read or understood a message.',takeaways:['Connect claims to deadlines.','Require accepted reassignment.','Audit duplicate replies separately from slow replies.']}),
 make({slug:'philippines-call-center-weather-continuity-study',title:'Weather continuity in Philippine call centers: testing handoffs without blaming staff',excerpt:'A bounded comparison of safety check-ins, coverage decisions, accepted handoffs, and customer promises during severe weather.',question:'Which continuity controls preserve customer work when a Philippine shift is affected by a severe-weather event?',unit:'one time-bound queue item due during the declared disruption window',evidence:'alert window, staffing forecast, safety check-in, queue demand, customer promise, backup assignment, acceptance time, system access, attempt, and outcome',cohorts:'unaffected and affected shifts, planned and unplanned backup, accepted and unaccepted handoffs, remote and site coverage under approved access, and promises met or missed',finding:'continuity performance should be judged through safe coverage and accepted work, not individual attendance viewed without local hazard and access context.',pilot:'creating a time-bound promise register and backup-acceptance check for one affected window, then comparing ownership and missed commitments with the prior routine',limits:'Weather severity and infrastructure effects vary by location; a small number of events limits comparison, and workforce records may omit personal safety circumstances.',takeaways:['Put employee safety first.','Trace each customer promise to an accepted owner.','Review external disruption separately from individual performance.']}),
 make({slug:'call-center-language-assistance-continuity-study',title:'Language-assistance continuity in call centers: a consent and handoff review',excerpt:'A record-review method for studying language choice, interpreter joins, repeated verification, material confirmations, and ownership.',question:'When language assistance joins a contact, is verified context preserved without expanding disclosure or confusing decision ownership?',unit:'one customer interaction in which language assistance is requested, offered, joined, declined, or unavailable',evidence:'customer language choice, consent, assistance route, join time, verified fields, disclosed context, material read-backs, decision owner, unresolved question, and final outcome',cohorts:'customer-requested and agent-offered assistance, joined and unavailable support, direct and relayed confirmations, routine and sensitive requests, and contacts with or without repeated verification',finding:'successful language access requires customer choice, minimum necessary context, explicit material confirmations, and an unchanged decision owner.',pilot:'using a structured assistance handoff in one queue and independently reviewing consent, repeated explanation, key read-backs, and completion across two samples',limits:'Records may not capture interpretation accuracy, dialect fit, customer comfort, or unspoken misunderstanding, and outcomes can differ with request complexity.',takeaways:['Record the customer’s language choice.','Limit shared context to what is needed.','Keep the organization’s decision owner explicit.']}),
 make({slug:'offshore-call-center-duplicate-case-linkage-study',title:'Duplicate-case linkage in offshore call centers: distinguishing repeats from collisions',excerpt:'A bounded study of repeat contacts, search failures, mistaken merges, linked histories, and active customer promises.',question:'Can case matching reduce duplicate work without merging different customers or concealing separate requests?',unit:'one newly created case flagged as a possible match to an earlier record',evidence:'safe match fields, request description, account reference, contact times, channels, prior status, current owner, active promise, link or merge action, and later correction',cohorts:'true repeat contacts, separate requests from one customer, different customers sharing a contact field, linked records, mistaken merges, search failures, and delayed-index cases',finding:'duplicate detection is safest when it treats similarity as a review signal and preserves separate identities, histories, owners, and promises until the match is confirmed.',pilot:'showing agents a small set of approved match fields and a link-without-merge option, then comparing confirmed repeats, collisions, corrections, and unresolved promises',limits:'Identity fields may be incomplete or outdated, cross-channel matching can fail, and later corrections may understate mistaken merges that were never reported.',takeaways:['Treat similarity as a signal, not proof.','Preserve histories until the match is confirmed.','Keep every active promise visible.']}),
];
