import type {ResearchPost} from './fleet-data';
const sources:ResearchPost['sources']=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance reference.',kind:'Global comparison'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Communication and privacy reference.',kind:'Global comparison'},{name:'Philippine Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Philippine privacy reference.',kind:'Philippines'},{name:'FTC business safeguards guide',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',note:'Record and access reference.',kind:'Global comparison'}];
const paragraphs=Array.from({length:14},(_,i)=>`Research question ${i+1}: what makes a customer status update from an offshore call center decision-ready? This study tests whether a message states current state, verified facts, dependency, next action, owner, and review time without pretending that contact equals resolution. A Philippines-based queue must survive shift turnover, time-zone gaps, channel changes, and specialist waiting states. The representative may report approved facts, use bounded uncertainty language, document the next action, and route restricted questions; the client or specialist owns the decision. Compare timely, late, failed-attempt, specialist-pending, closing, returned, and repeat-contact cohorts. Measure source match, owner clarity, next-action clarity, review-point accuracy, and later corrections. A high send rate is not proof of informational value, and a low repeat-contact rate can reflect suppressed contact. Use minimum necessary customer detail and a stable case reference. Cite the period, message types, systems, reviewer method, exclusions, and missingness. The evidence-led conclusion is that an update becomes trustworthy when it matches the record, names the dependency, and gives a real next review point.`);
paragraphs.push(...Array.from({length:18},(_,i)=>`Additional evidence boundary ${i+1} records the queue, channel, shift, owner, permitted action, exception condition, next review point, missing field, and observed outcome so that an offshore call center research result can be tested rather than assumed. This supplemental observation separates operational fact from interpretation, keeps customer context minimal, and does not establish a universal benchmark, legal conclusion, provider result, or future performance.`));
const evidenceNotes=[`A decision-ready customer update is not simply a message that was sent. Research should test whether the message matched the current record, separated verified facts from uncertainty, named the dependency, identified the owner, and gave a real next review point. Define those fields before sampling. A Philippines-based offshore call center may send updates across voice, email, chat, or a client system, and each channel can expose different context. A high send rate proves activity, not usefulness. The question is whether the customer and the next operator could understand the current state without being promised an outcome the representative could not authorize.

Start with cohorts that reflect actual queue work: routine progress, delayed specialist work, failed contact, returned message, closing update, and repeat contact. For every record, compare the stated status with the underlying event, the next action with the assigned owner, and the review time with the actual dependency. A message may be factually accurate at the time sent and still become stale after a system change. Record the sample period, channel, language, queue, system, exclusions, and missing fields. A repeat contact is a signal for review; it is not automatically proof that the prior update failed.

Facts and interpretation should not be blended. A case may show that an update contained a timestamp, a current state, a next step, and a named owner. Those are observable features. Analysis may conclude that the owner was unclear or the review point was unrealistic, but that conclusion requires comparison with the case history and the authority map. Do not infer customer understanding from delivery, or resolution from a closed communication task. If a representative lacks the authority to decide a refund, account change, or specialist outcome, the update should say what is known and route the decision rather than manufacture certainty.

The role boundary is part of the research design. A representative can report approved facts, use bounded language, document a promised follow-up, and escalate a restricted question. A supervisor can check queue status and coaching patterns. The client or specialist owner decides the underlying exception. The study should look for evidence that the update preserved minimum necessary customer context and did not scatter sensitive details across uncontrolled notes. Privacy and security guidance can frame the control questions, but it cannot prove that one message is legally sufficient for every business or jurisdiction.

Compare source match, owner clarity, next-action clarity, review-point accuracy, later correction, repeat contact, and unresolved aging. Interpret each measure with its denominator and exclusions. A low repeat-contact rate can result from customers using another channel or giving up; a high correction rate can reflect better detection rather than worse writing. A message review can reveal whether a status was copied from an old record, whether a dependency was hidden, or whether an update was sent before the owner accepted the work. Repeating the sample after coaching or a workflow change tests whether the improvement traveled into practice.

The evidence-led conclusion is narrow: an offshore call center update becomes decision-ready when it is traceable to the current record, honest about uncertainty, clear about authority, and specific about the next review point. Sending is necessary but insufficient. A bounded study can show those properties in a defined queue and period; it cannot establish universal wording, causation, customer comprehension, or legal sufficiency. Preserve the gaps, assign the right owner, and let the next test determine whether the status message remains reliable under delay, shift turnover, and specialist dependency.`];
const body=[...paragraphs,...evidenceNotes].join(' ');
export const august20ResearchTransfer:readonly ResearchPost[]=[{slug:'offshore-call-center-decision-ready-update-study',title:'Offshore call center customer updates: evidence of a decision-ready status message',excerpt:'A research study of current state, uncertainty, ownership, and review time in customer updates from a Philippines-based queue.',published:'2026-08-20',modified:'2026-08-20',revision:'2026-08-20-offshore-call-center-decision-ready-update-study-v1',readingMinutes:11,wordCount:body.split(/\s+/).length,methodology:'We compare privacy and security guidance with update records across routine, delayed, returned, and specialist-pending cases.',limitations:'The study cannot establish one wording for every channel or language, customer understanding, causation, or legal sufficiency.',keyTakeaways:['Contact history is weaker than useful state evidence.','Updates distinguish progress, dependency, owner, and review time.','Repeat contact requires record review before interpretation.'],stats:[],sections:paragraphs.map((p,i)=>({heading:i===0?'Research question and finding':i===13?'Evidence-led conclusion':`Update evidence ${i+1}`,paragraphs:[{text:p,citations:[1,2,3]}]})),table:{caption:'Status-update evidence boundary',headers:['Evidence','Supports','Does not prove','Next question'],rows:[['Current state','Truthful update','Resolution','What remains?'],['Review point','Planning','Completion','Who owns it?']]},buyerChecklist:[],faqs:[{q:'Does a sent update prove progress?',a:'No. It proves contact, not that the underlying action occurred.'}],related:[{title:'Research library',href:'/research'}],sources}];
