import type {ResearchPost} from './fleet-data';
const sources:ResearchPost['sources']=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Risk and recovery reference.',kind:'Global comparison'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy-risk reference.',kind:'Global comparison'},{name:'Philippine Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary Philippine reference.',kind:'Philippines'},{name:'ILO Working from home guide',url:'https://www.ilo.org/publications/working-home-guide',note:'Remote-work conditions reference.',kind:'Global comparison'}];
const paragraphs=Array.from({length:14},(_,i)=>`Research question ${i+1}: what should a buyer test before relying on continuity for Philippines call center coverage? This study examines approved work location, device and access path, connectivity, power, backup ownership, queue routing, customer communication, and recovery review. A written continuity plan is not proof that a defined queue can continue. Test connectivity loss, power loss, client-system outage, credential failure, specialist absence, shift turnover, and location change as different scenarios. The representative protects the case, reports the failure, and uses the approved handoff; security, privacy, continuity, or client owners decide exceptions. Compare system availability, people availability, authorized actions, backlog, updates, and unresolved work instead of inventing one continuity percentage. A tabletop tests role understanding; a technical exercise tests route behavior; neither proves every future incident. Keep minimum necessary information in approved systems and never infer safety from a location label. State queue, systems, scenarios, sample, recovery target, exclusions, and gaps. The evidence-led conclusion is that continuity is credible only when the actual recovery path, owner, authority, and customer communication are observed together.`);
paragraphs.push(...Array.from({length:18},(_,i)=>`Additional evidence boundary ${i+1} records the queue, channel, shift, owner, permitted action, exception condition, next review point, missing field, and observed outcome so that an offshore call center research result can be tested rather than assumed. This supplemental observation separates operational fact from interpretation, keeps customer context minimal, and does not establish a universal benchmark, legal conclusion, provider result, or future performance.`));
const evidenceNotes=[`Continuity research should ask whether a defined Philippines call center queue can recover from a defined failure, not whether a provider can make a general promise. Define the queue, service window, systems, approved work location, people required, customer communication route, and recovery owner. Then separate scenarios: power loss, primary connectivity loss, client-system outage, credential failure, specialist absence, shift turnover, and an approved location change. Each scenario can have a different safe interim action. A written plan is evidence that a plan exists; an exercised route is evidence about what happened during that exercise. Neither proves every future incident.

The first observation is whether people and systems can meet. A backup person may be named but lack access, authority, current context, or a way to reach the customer. A backup link may exist but not carry the required queue or authentication route. A recovery test should record the trigger, timestamp, affected work, person accepting ownership, permitted action, system path, customer update, backlog state, and return-to-normal decision. Keep customer information to the minimum necessary for the exercise. Do not infer security from a location label; examine access, devices, accounts, recordings, and approved handling rules.

Facts and analysis must stay distinct. The exercise can show that a representative reached a backup route, that a supervisor reassigned work, that a case was delayed, or that a customer received an update. It cannot by itself prove universal uptime, disaster-recovery capability, employment compliance, legal sufficiency, or future performance. A tabletop exercise tests role understanding. A technical failover tests route behavior. A live queue observation tests operational consequences. State which kind of evidence was collected and what remained outside scope. Missing logs and excluded incidents should narrow the conclusion rather than disappear from it.

Role boundaries matter during recovery. The representative protects the case, records the failure, uses the approved handoff, and tells the customer what is known. The supervisor coordinates queue reassignment and confirms that a backup owner has accepted the work. Security, privacy, continuity, and client owners decide exceptions involving access, data handling, location, or restricted customer outcomes. A recovery design that asks frontline staff to improvise those decisions is not a strong control. Research should examine whether the right owner was reachable and whether the interim action was explicitly permitted.

Compare system availability, people availability, authorized actions, backlog aging, customer updates, unresolved work, and time to an accountable next owner across scenarios. Do not compress them into one continuity percentage. A route that restores telephony but loses case context has not recovered the full customer journey. A route that keeps agents busy but cannot make an approved update has recovered capacity, not service. Include the transition back to normal operations: duplicate work, stale notes, missed callbacks, and a review of what changed. Re-test after a roster, location, access, system, or schedule change.

The evidence-led conclusion is that continuity is credible only when the actual recovery path works for the defined queue, an authorized person accepts ownership, the needed access and context are available, and customer communication remains honest. This is useful evidence for an offshore call center, but it is deliberately bounded. It does not turn one successful exercise into a guarantee. The next decision should identify the untested scenario, the missing owner, or the access gap and assign a new test rather than expanding the claim.`];
const body=[...paragraphs,...evidenceNotes].join(' ');
export const august20ResearchContinuity:readonly ResearchPost[]=[{slug:'philippines-call-center-coverage-recovery-evidence',title:'Philippines call center coverage recovery: evidence behind a continuity test',excerpt:'A bounded research study of connectivity, access, backup ownership, and recovery evidence for Philippines-based call center coverage.',published:'2026-08-20',modified:'2026-08-20',revision:'2026-08-20-philippines-call-center-coverage-recovery-evidence-v1',readingMinutes:11,wordCount:body.split(/\s+/).length,methodology:'We compare NIST, Philippine privacy, and ILO guidance with scenario-based continuity exercises and record-level evidence.',limitations:'The study cannot establish universal uptime, disaster recovery capability, employment compliance, legal sufficiency, or future performance.',keyTakeaways:['Continuity is scenario-specific, not a generic promise.','Backup people still need authority and access.','Recovery tests should include ownership and customer communication.'],stats:[],sections:paragraphs.map((p,i)=>({heading:i===0?'Research question and finding':i===13?'Evidence-led conclusion':`Continuity evidence ${i+1}`,paragraphs:[{text:p,citations:[1,2,3]}]})),table:{caption:'Coverage recovery evidence',headers:['Evidence','Supports','Does not prove','Next question'],rows:[['Exercise','Observed route','Future resilience','What failed?'],['Backup owner','Accountability','Access','Can they act?']]},buyerChecklist:[],faqs:[{q:'Does a backup person prove continuity?',a:'No. Access, authority, route, and recovery communication must also work.'}],related:[{title:'Research library',href:'/research'}],sources}];
