import type {ResearchPost} from './fleet-data';
const body=[
'Research question: when a customer moves between phone, chat, email, and back-office work, what evidence shows that an offshore call center preserved context? The date of this route-specific record is 2026-08-21. A channel change can be a customer choice, a specialist requirement, or a system-induced detour. Treating every transfer as failure is as misleading as treating every connected handoff as success. This study examines the information and ownership that survive the switch.',
'Methodology and evidence scope: we compared governance and recovery concepts at https://www.nist.gov/cyberframework, privacy minimization at https://www.nist.gov/privacy-framework, Philippine privacy requirements at https://privacy.gov.ph/data-privacy-act/, and distributed-work responsibility context at https://www.ilo.org/global/topics/non-standard-employment/platform-work/lang--en/index.htm. We then reviewed hypothetical channel sequences using one case as the unit. Facts are original channel, reason for change, consent or customer choice where relevant, receiving owner, context transferred, verification step, next action, and closure. Analysis distinguishes useful verification from needless repetition.',
'Continuity is not the same as copying every note. The receiving representative needs the customer’s purpose, current decision, approved next step, relevant constraints, and owner. Unnecessary personal details should not travel merely because a system allows them. A short structured summary can be safer and more useful than a transcript. The sending role should state what has been verified and what remains unresolved. The receiving role should acknowledge ownership and identify any missing fact before promising progress.',
'A sequence review should distinguish a deliberate choice from a forced detour. Ask whether the original channel offered a clear next step, whether the receiving channel was named before the switch, and whether the customer had to restate the purpose or only complete a normal verification step. If chat becomes phone, inspect whether the customer understood why. If frontline work becomes back office, inspect whether the back-office owner returned a usable decision. These events prevent a dashboard from calling every switch the same thing.',
'Handoff evidence includes timestamp, source channel, target channel, reason, owner acceptance, summary, verification status, expected wait, and escalation route. A transfer accepted by a queue is weaker evidence than an accountable receiving owner. A summary pasted into a ticket is not proof that the receiver read it. Sample accepted and rejected handoffs and compare the first receiving note with the original request. When the receiver corrects the summary, preserve the correction as evidence rather than silently replacing history.',
'Channel boundaries create distinct risks. Email may make a promise appear asynchronous while the customer expects a same-day answer. Chat may lose context when an agent changes shift. Phone may require verification that the prior channel did not. Back-office work may need a decision authority unavailable to frontline staff. Define each role’s authority and escalation path. Representatives can explain the handoff, capture the minimum context, and route uncertainty. They should not disclose more data, change a policy decision, or claim that a specialist approved something without evidence.',
'Analysis should use comparable cohorts: voluntary versus required switches, channel pair, request type, shift, and specialist dependency. Track repeat explanations, abandoned transfers, time to acceptance, missing summaries, and unresolved next actions only after definitions are stable. A shorter average handoff can hide more repeat contact if context was dropped. Test one control, such as a structured summary, named acceptance, or customer-visible wait estimate. Re-read a sample after the change and report both the observed improvement and remaining uncertainty.',
'Limitations: this study cannot prove satisfaction, universal continuity, legal compliance, or that a repeat explanation was caused by the channel switch. The hypothetical sequence is not a production dataset. Frameworks provide control questions, not performance scores for one offshore operation. Records may omit customer intent, accessibility needs, or an unlogged conversation. The conclusion is therefore limited to defined route events, available fields, and the period under review.',
'Evidence-led conclusion: channel continuity is supported when the customer’s purpose, safe context, owner, verification state, expected next action, and return path survive a deliberate or necessary switch. It is not proven by a transfer count or a copied transcript. Offshore call center managers should test the weakest pair of channels, retain the original and receiving evidence, and keep role boundaries explicit. The result can guide one controlled improvement without pretending every handoff has the same cause or effect.'
,'A continuity study should preserve the customer’s original purpose while allowing a normal verification step. Do not call every authentication request a failure to transfer, and do not call every repeated explanation a harmless detail. Inspect whether the receiving role had the authority and tools to act. If not, the route needs a named escalation rather than another blind handoff. A useful report identifies the channel pair, route reason, missing field, owner, and next test. That structure helps a manager repair a boundary without promising that every customer will experience every switch identically.'
,'A route-level continuity study should preserve the customer’s original purpose separately from each representative’s activity. Compare the source channel, reason for change, context summary, verification, receiving owner, and next usable action in sequence. If one field is absent, report the absence plainly and assign a repair. Do not infer continuity from a transfer count, copied transcript, or quiet customer. The strongest evidence is specific enough for another reviewer to reproduce the finding, while the conclusion remains limited to the sampled channel pair and period.'
,'A second reviewer should be able to trace every continuity finding back to the original and receiving channel records.'
].join(' ');
const sources=[{name:'NIST CSF',url:'https://www.nist.gov/cyberframework',note:'Governance.',kind:'Global comparison' as const},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy.',kind:'Global comparison' as const},{name:'Philippine Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary law.',kind:'Philippines' as const},{name:'ILO platform work',url:'https://www.ilo.org/global/topics/non-standard-employment/platform-work/lang--en/index.htm',note:'Work context.',kind:'Global comparison' as const}];
export const august21ChannelContinuity:readonly ResearchPost[]=[{slug:'offshore-call-center-channel-handoff-continuity-study',title:'Offshore call center channel handoffs: evidence that customer context survived',excerpt:'A bounded study of context, ownership, verification, and next actions across support channels.',hero:'/aug21-research-heroes/offshore-call-center-channel-switching-research.png',published:'2026-08-21',modified:'2026-08-21',revision:'2026-08-21-offshore-call-center-channel-handoff-continuity-study-v1',readingMinutes:7,wordCount:body.split(/\s+/).length,methodology:'Scenario review of channel sequences against four external sources.',limitations:'Hypothetical route evidence cannot prove satisfaction or universal continuity.',keyTakeaways:['A switch can be chosen or forced.','Context must be sufficient, not maximal.','Receiving ownership must be observable.'],stats:[],sections:[{heading:'Research question, methodology, analysis, limitations, and conclusion',paragraphs:[{text:body,citations:[1,2,3,4]}]}],table:{caption:'Handoff evidence boundary',headers:['Observed evidence','Supports','Does not prove','Next test'],rows:[['Owner acceptance','Receiving accountability','Resolution','Sample a channel pair']]},buyerChecklist:[],faqs:[{q:'Does a transfer count prove continuity?',a:'No. Continuity requires route-specific context, ownership, and next-action evidence.'}],related:[{title:'Research library',href:'/research'}],sources}];
