import type {ResearchPost} from './fleet-data';

type Topic={slug:string;title:string;excerpt:string;question:string;decision:string;unit:string;fields:string;groups:string;control:string;failure:string;service:string;serviceHref:string;takeaways:readonly string[]};

const sources:ResearchPost['sources']=[
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'National Institute of Standards and Technology primary framework; checked September 18, 2026. Used for governance, access, detection, response, and recovery concepts.',kind:'Global comparison'},
 {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'NIST primary privacy-risk framework; checked September 18, 2026. Used to distinguish necessary processing from avoidable data exposure.',kind:'Global comparison'},
 {name:'Republic Act No. 10173: Data Privacy Act of 2012',url:'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html',note:'Official Philippine statutory text; checked September 18, 2026. Used as operational context, not legal advice.',kind:'Philippines'},
 {name:'National Privacy Commission: Data Privacy Act resources',url:'https://privacy.gov.ph/data-privacy-act/',note:'Official Philippine regulator resource; checked September 18, 2026. Used for accountability and data-protection context.',kind:'Philippines'},
 {name:'ISO 18295-1:2017 — Customer contact centres',url:'https://www.iso.org/standard/64739.html',note:'Official ISO standard overview; checked September 18, 2026. Used as a customer-contact-centre requirements comparison.',kind:'Global comparison'},
 {name:'FTC: Complying with the Telemarketing Sales Rule',url:'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule',note:'Official U.S. Federal Trade Commission business guidance; checked September 18, 2026. Relevant where a workflow includes outbound telemarketing.',kind:'Global comparison'},
 {name:'FCC: Telephone Consumer Protection Act resources',url:'https://www.fcc.gov/general/telemarketing-and-robocalls',note:'Official U.S. Federal Communications Commission resource; checked September 18, 2026. Relevant where calls or texts fall within U.S. calling rules.',kind:'Global comparison'},
];

const topics:readonly Topic[]=[
 {slug:'offshore-call-center-crm-access-minimization-study',title:'CRM access for offshore support teams: a minimum-permission study',excerpt:'A buyer-focused method for testing whether each support role can complete assigned work without broad, standing access to customer records.',question:'What is the smallest CRM permission set that lets a Philippines-based support role complete its defined queue safely?',decision:'whether to approve a proposed role profile before launch, reduce existing permissions, or retain a client-side action for sensitive cases',unit:'one eligible customer case and the sequence of CRM actions required to move it to an approved outcome',fields:'role, queue, record type, data viewed, action attempted, permission result, escalation, temporary grant, approver, and final outcome',groups:'routine cases, exception cases, read-only tasks, write actions, export attempts, and actions reserved for a client owner',control:'a role-to-action matrix with deny-by-default permissions, named exception ownership, and a scheduled access review',failure:'agents receive broad administrator-style access because individual actions were never mapped',service:'inbound customer care',serviceHref:'/services/inbound-customer-care',takeaways:['Map permissions to actions, not job titles.','Test denied and exceptional actions before launch.','Keep approval and access changes traceable.']},
 {slug:'call-center-time-zone-coverage-design-research',title:'Time-zone coverage for outsourced support: testing promises before staffing',excerpt:'A decision model for matching customer demand, response promises, handoffs, breaks, and supervisor availability across time zones.',question:'Which staffed hours and handoff rules are needed to meet a stated customer promise without implying continuous coverage that does not exist?',decision:'whether the proposed schedule, overlap, and escalation coverage are sufficient for the queue and its advertised response window',unit:'one customer contact or open promise that enters, remains open, or becomes due during a defined coverage boundary',fields:'customer zone, arrival time, promised response, staffed interval, skill availability, break coverage, supervisor availability, handoff acceptance, and outcome',groups:'in-hours and boundary contacts, ordinary and urgent requests, weekdays and holidays, accepted and unaccepted handoffs, and daylight-saving transitions',control:'a coverage map tied to observed arrivals, explicit promise windows, receiver acknowledgement, and an after-hours customer message',failure:'buyers purchase seat hours without testing when demand arrives or who owns work at the edge of a shift',service:'after-hours answering',serviceHref:'/services/after-hours-answering',takeaways:['State the customer promise before calculating seats.','Test shift boundaries and calendar changes.','Require the receiving owner to accept open work.']},
 {slug:'offshore-call-center-order-billing-authority-study',title:'Order and billing support authority: an exception-boundary study',excerpt:'A source-record review for deciding which order changes, credits, refunds, and billing explanations an offshore team may handle.',question:'Which order and billing actions can a support role complete from written rules, and which require a named client-side decision?',decision:'whether to delegate, limit, or retain each action based on evidence required, financial exposure, reversibility, and approval authority',unit:'one order or billing request from intake through verification, decision, system action, customer communication, and closure',fields:'request type, verification state, order status, amount, policy basis, exception reason, approver, action, notification, reversal, and outcome',groups:'standard and exceptional requests, reversible and irreversible actions, approved and unapproved credits, and completed and disputed outcomes',control:'an authority table that joins action thresholds, required evidence, hard stops, approval receipts, and customer-facing language',failure:'a vague instruction to use judgment conceals who may commit funds or change a customer obligation',service:'order and billing support',serviceHref:'/services/order-and-billing-support',takeaways:['Separate explanation from financial authority.','Record the rule and approval behind each exception.','Audit reversals and disputes, not activity alone.']},
 {slug:'call-center-outbound-suppression-evidence-research',title:'Outbound calling suppression evidence: a pre-dial control study',excerpt:'A bounded method for testing whether campaign lists, consent evidence, suppression signals, time rules, and outcomes remain connected.',question:'Can an outbound support workflow stop an ineligible contact before a dial or message while preserving evidence for review?',decision:'whether a proposed lead-qualification workflow has sufficient pre-dial controls and escalation before it is assigned to an offshore team',unit:'one proposed outbound contact attempt, including list source, eligibility decision, dial or message event, disposition, and subsequent suppression',fields:'source, purpose, jurisdiction, permission basis, internal suppression, applicable list check, local time, channel, attempt, revocation, and final disposition',groups:'eligible and blocked records, recent and stale evidence, voice and text channels, first and repeated attempts, and explicit revocations',control:'a pre-dial eligibility gate with versioned rules, synchronized suppression, local-time checks, and a stop path workers cannot override',failure:'a clean-looking campaign list is treated as proof of permission even though eligibility can change after list creation',service:'outbound lead qualification',serviceHref:'/services/outbound-lead-qualification',takeaways:['Make eligibility a pre-dial decision.','Synchronize revocations and internal suppression quickly.','Do not infer consent from a purchased record.']},
 {slug:'virtual-assistant-vendor-exit-readiness-study',title:'Virtual assistant vendor exit readiness: a continuity and access study',excerpt:'A practical research method for testing whether work, knowledge, customer promises, credentials, and records can transfer cleanly at exit.',question:'Can a buyer end or change a Philippines-based support arrangement without losing work history, leaving access open, or abandoning customer commitments?',decision:'whether the operating model is portable enough to launch or renew, and which exit controls must be added before dependency grows',unit:'one active workflow, account, queue, knowledge asset, or customer promise included in a defined transition scope',fields:'owner, system, credential type, data location, export format, open work, due promise, receiving owner, revocation event, and validation result',groups:'client-owned and vendor-managed systems, documented and tacit knowledge, active and dormant access, open and closed work, and reversible and irreversible dependencies',control:'an exit register with client ownership, export tests, knowledge acceptance, promise transfer, access revocation, and a post-exit validation owner',failure:'transition planning begins only after notice, when ownership and export constraints are hardest to correct',service:'appointment scheduling',serviceHref:'/services/appointment-scheduling',takeaways:['Test portability before dependency grows.','Transfer open promises, not only files.','Verify access removal after the final handoff.']},
];

function make(t:Topic):ResearchPost{
 const paragraphs=[
  `This report asks: ${t.question} The buying decision is ${t.decision}. That framing matters because an outsourced role is not a generic seat. It is a bounded set of actions, information, hours, and escalation duties. A buyer should first describe the customer outcome and the decisions that remain with the client. Only then can staffing, training, access, and quality checks be evaluated against the work that will actually enter the queue.`,
  `The unit of analysis is ${t.unit}. Reviewers should not substitute a monthly average, a vendor presentation, or an employee-level score for that unit. Those summaries can hide the exact boundary that failed. The minimum evidence fields are ${t.fields}. Preserve missing fields as missing; do not fill gaps with assumptions or treat a later note as proof that an earlier control occurred.`,
  `The proposed comparison separates ${t.groups}. Set those groups before reading outcomes. This reduces the temptation to redefine a successful case after the result is known. Sample across ordinary work and credible exceptions, because a workflow that succeeds only when every input is complete is not ready for live customer work. Keep dates, systems, exclusions, and selection rules beside the findings so another reviewer can reproduce the slice.`,
  `The baseline failure mode is that ${t.failure}. The useful question is not whether a policy exists, but whether the source record shows the policy changing the next action. Evidence should connect the triggering condition, the permitted response, any stop, the receiving owner, and the customer-facing result. A checklist completed after closure cannot replace time-stamped operational evidence from the system where the work occurred.`,
  `A defensible pilot uses ${t.control}. Run the pilot in one named queue for a fixed period and define success and stop conditions in advance. Include a small set of seeded or historical edge cases where this can be done without affecting customers. Compare the same fields before and after the change, and examine contrary cases rather than reporting only the average. If the control moves work to another team, that downstream work belongs in the result.`,
  `Facts in this study are limited to recorded events and the cited public sources. Analysis links those facts to a buyer decision. The operational inference is that a narrower, observable control is easier to supervise than broad discretion. That remains an inference until the buyer tests it in the relevant systems, channels, schedule, and request mix. No source here proves a provider's performance, a worker's intent, legal compliance, or a universal benchmark.`,
  `For Philippines-based delivery, privacy and accountability must be translated into specific work instructions. Identify which system is authoritative, which fields are necessary, where notes may be stored, and who handles a request that exceeds the role. Avoid copying sensitive information into chat, spreadsheets, or personal notes merely to make a handoff convenient. The Data Privacy Act and National Privacy Commission resources provide context; the buyer should obtain qualified advice for its actual jurisdictions and processing arrangement.`,
  `Quality review should measure the decision path as well as the final disposition. A correct-looking outcome may have used unsupported access or skipped required approval, while an escalation may be the safest successful result. Review a stratified sample, have a second reviewer independently classify ambiguous cases, and report agreement. Reconcile definitions before using the result for coaching, staffing, vendor comparison, or commercial decisions.`,
  `Implementation should begin with a written role brief, examples of acceptable and unacceptable action, test credentials, and a named escalation owner. Supervisors need a live view of stops, overdue acknowledgements, and unresolved customer promises. Frontline workers should have calm language for explaining the next step without inventing an answer or guaranteeing a result. Changes to rules, systems, or staffing should trigger a new test because earlier evidence may no longer describe the workflow.`,
  `The buyer decision should be recorded as approve, approve with conditions, redesign, or retain with the client. Attach the evidence window, exceptions, unresolved questions, and retest date. A positive pilot supports only the tested scope. Expansion to another channel, geography, product, or risk level requires a new boundary review. A failed pilot is useful when it identifies the exact permission, handoff, capacity, or instruction that must change before customers depend on it.`,
  `Limitations are material. System logs may omit conversations, manual work, failed integrations, or activity in third-party tools. A small sample can reveal control defects but cannot estimate rare-event frequency reliably. Reviewer knowledge may influence classification. Regulations and platform behavior can change. Customer outcomes can also reflect product, fulfillment, pricing, or policy decisions outside the support team's control. State these constraints next to every conclusion instead of hiding them in a footnote.`,
  `For a sourcing conversation, ask the provider to demonstrate the workflow using representative cases and a non-production environment where possible. Confirm what the frontline role can see and change, how exceptions reach the client, how acknowledgement is captured, and what evidence remains after closure. Connect the test to ${t.service} rather than a generic outsourcing claim. The result should be a launch condition and review routine, not a promise that every future case will behave like the sample.`,
  `Source quality also needs a boundary. The cited frameworks, statute, regulator pages, and standards overview explain principles and requirements; they do not contain measurements of this buyer's queue. Record the title, publisher, URL, and checked date so a later reviewer can see what informed the method. If a source changes or a link disappears, preserve the interpretation used and recheck the affected control. Marketing claims, unsourced benchmarks, and search-result summaries should not be promoted into facts merely because they appear consistent with the proposed design.`,
  `Governance continues after launch. Assign a client owner for policy, a delivery owner for daily execution, a security or privacy contact for protected information, and a receiving owner for exceptions. Decide which changes require prior approval and which may be made within the role. Review open exceptions and missing evidence at a fixed cadence. Trend data can identify where to investigate, but record reading is still needed before attributing a problem to training, staffing, technology, or individual performance.`,
  `Commercial evaluation should follow the same evidence boundary. Ask what is included in the stated service, which systems and licenses the buyer supplies, how backup coverage works, and who bears work created by escalations or rework. Compare providers against the same representative scenarios, not different demonstrations chosen by each seller. Price, staffing ratio, and stated experience matter, but none replaces proof that the proposed team can follow the exact authority, access, handoff, and review design the buyer intends to operate. Record unanswered commercial assumptions beside the operational decision for later review.`,
 ];
 const headings=['Decision and scope','Unit and evidence fields','Comparison design','Failure mode to test','Controlled pilot','Facts, analysis, and inference','Philippines privacy context','Quality review','Operating design','Decision rule','Limitations','Buyer application','Source evaluation','Ongoing governance','Commercial comparison'];
 return {slug:t.slug,title:t.title,excerpt:t.excerpt,hero:'/offshore-call-center-agent.jpg',published:'2026-09-18',modified:'2026-09-18',revision:`2026-09-18-${t.slug}-v1`,readingMinutes:11,wordCount:paragraphs.join(' ').split(/\s+/).length,methodology:`A bounded source-record study of ${t.unit}. Eligibility, comparison groups, required fields, exclusions, reviewer disagreement, success conditions, and stop conditions are defined before outcome review. Public sources were checked on September 18, 2026.`,limitations:'The method depends on the completeness of operational records and the stability of the tested workflow. It cannot establish legal compliance, causation, provider-wide performance, employee intent, or results outside the stated sample.',keyTakeaways:t.takeaways,stats:[],sections:headings.map((heading,i)=>({heading,paragraphs:[{text:paragraphs[i],citations:i===6?[2,3,4]:i===7?[1,5]:i===11?[1,2,5]:[1,2,5]}]})),table:{caption:'Evidence boundary for the buying decision',headers:['Evidence','Supports','Does not prove','Buyer action'],rows:[[t.fields.split(',')[0],'A recorded event','A complete process','Check the source record'],['Accepted escalation','Named receipt','Correct decision','Trace the outcome'],['Pilot comparison','A bounded difference','Universal performance','Retest before expansion']]},buyerChecklist:['Define the customer outcome and retained client decisions.','Name the unit, sample period, eligibility rules, and exclusions.','Test routine, ambiguous, denied, and exception cases.','Preserve missing data and reviewer disagreement.','Record a launch decision, conditions, owner, and retest date.'],faqs:[{q:'Does a successful pilot prove the provider will always perform?',a:'No. It supports only the tested workflow, sample, systems, dates, and conditions. Continue monitoring and retest material changes.'},{q:'Is this report legal advice?',a:'No. It is an operational research framework. Obtain qualified advice for the jurisdictions, data, channels, and contractual arrangement involved.'}],related:[{title:`Explore ${t.service}`,href:t.serviceHref},{title:'Research library',href:'/research'}],contextualService:{heading:`Apply the evidence to ${t.service}`,text:'Turn the tested scope, authority limits, escalation path, and review fields into a role brief before sourcing.',label:`Review ${t.service}`,href:t.serviceHref},sources};
}

export const september18ResearchBatch:readonly ResearchPost[]=topics.map(make);
