import type {ResearchPost} from './fleet-data';

const sources: ResearchPost['sources'] = [
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance, protection, detection, response, and recovery concepts used to examine ownership and evidence.',kind:'Global comparison'},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy risk concepts used for purpose limits, access decisions, and customer-data handling.',kind:'Global comparison'},
  {name:'Philippine Data Privacy Act, Republic Act No. 10173',url:'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html',note:'Primary Philippine law used to frame processor accountability and personal-information safeguards.',kind:'Philippines'},
  {name:'National Privacy Commission implementing rules',url:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/',note:'Philippine regulator text on accountability, security, processing, and data-subject rights.',kind:'Philippines'},
  {name:'ILO Working from home report',url:'https://www.ilo.org/publications/major-publications/working-home-invisibility-decent-work',note:'Work-organization context for distributed teams, communication, and worker safeguards.',kind:'Global comparison'},
];

type Draft = {slug:string;title:string;excerpt:string;hero:string;question:string;methodology:string;limitations:string;takeaways:string[];sections:{heading:string;text:string;citations:number[]}[]};

const closingAnalysis: Record<string,{heading:string;text:string}> = {
  'offshore-call-center-customer-silence-closure-research': {heading:'What managers should inspect after changing the rule',text:'After a closure-rule change, reviewers should trace cases that remained open beyond the new window as carefully as cases that closed. The open group may reveal missing client decisions, unreachable channels, or promises whose owners were never recorded. The closed group should be sampled for later returns through phone, chat, or email, using an approved case link rather than customer details in the research file. Compare whether the next representative could see the prior question and resume from the correct boundary. Ask the client owner to review cases where the customer was silent but an internal action remained due. If the revised rule reduces queue age by removing those cases from view, the apparent improvement is not supported. A useful retest shows fewer ambiguous statuses while preserving unresolved obligations, permitted contact limits, and a practical route back into service.'},
  'philippines-call-center-escalation-acknowledgement-latency': {heading:'Read the tail cases before changing coverage',text:'The slowest acknowledged escalations deserve record-level review, but so do fast acknowledgements with no later action. Compare what the receiving owner accepted, when the customer next heard from the team, and whether the decision actually answered the question sent. If delays cluster outside client hours, a manager might test a backup acknowledgement owner or narrower overnight promise. If they cluster around one request type, the problem may be an unclear packet or authority boundary rather than general capacity. Preserve cases excluded from the calculation and explain why. That makes the result auditable when systems miss timestamps or ownership changes outside the normal route. The next operating decision should name one owner, one changed checkpoint, and one retest date. The evidence does not support expanding frontline authority simply because a specialist queue acknowledges work slowly.'},
  'call-center-partial-verification-safe-stop-research': {heading:'Measure the customer path after the stop',text:'The review should follow what happens after the representative declines the protected action. Check whether the customer receives an approved explanation, reaches the alternate route, abandons the request, or returns through another queue. A repeat contact may show that the stop message was unclear, that the alternative was unavailable, or that the customer tried a different request; it does not prove the control was wrong. Compare the source version and escalation availability across those outcomes. If staff create informal workarounds, document the process pressure without publishing the workaround detail. The authorized owner can then decide whether to improve access, instructions, accessibility support, or coverage while retaining the verification boundary. A later sample should test the same checkpoint categories. The strongest result is consistent safe handling with an attainable next step, not completion at any cost.'},
  'offshore-call-center-hold-to-callback-conversion-study': {heading:'Audit the queue that disappears from hold reports',text:'Managers should reconcile the callback queue with the live queue for the same sample window. Every accepted conversion should appear with an owner and final disposition, including failed connections and customer-requested reschedules. Check whether callbacks created near shift end remain visible to the incoming Philippines team and whether client-controlled dependencies carry a truthful update point. Sample customers who contacted the business again before the callback because these records test whether the promise was findable across channels. Review declined offers too, since they show whether customers had a usable choice instead of being pushed out of the live queue. Do not treat a lower live abandonment rate as proof of improvement if converted work later expires or closes without contact. The retest should preserve request mix and time bands, then compare complete chains rather than isolated telephony events. A conversion policy is measurable only when work remains observable after the customer leaves the live hold path.'},
  'call-center-post-closure-correction-propagation': {heading:'Test whether the correction stops recurring',text:'After the affected-record review, select a later sample from the same request types and search paths. Check which source representatives opened, whether cached macros still contain old language, how exceptions were routed, and whether the customer-facing answer matches the corrected boundary. Include cases where the new answer should not apply, because over-correction can create another error. Record disagreements between reviewers and return them to the source owner instead of averaging them away. If another closed case surfaces with the old answer, determine whether it predates the effective time, escaped the original scope, or reflects continued availability. Those causes require different repairs. The correction can close operationally when the old source is controlled, defined affected work has an owner, approved follow-up is evidenced, and the retest no longer finds unexplained use.'},
};

const make = (draft:Draft):ResearchPost => ({
  slug:draft.slug,title:draft.title,excerpt:draft.excerpt,hero:draft.hero,published:'2026-09-03',modified:'2026-09-03',revision:`2026-09-03-${draft.slug}-v1`,readingMinutes:9,
  wordCount:[...draft.sections,closingAnalysis[draft.slug]].map(section=>section.text).join(' ').trim().split(/\s+/).length,
  methodology:draft.methodology,limitations:draft.limitations,keyTakeaways:draft.takeaways,stats:[],
  sections:[...draft.sections,{...closingAnalysis[draft.slug],citations:[1,2,3]}].map(section=>({heading:section.heading,paragraphs:[{text:section.text,citations:section.citations}]})),
  table:{caption:'Evidence boundaries for the research question',headers:['Observed record','What it supports','What it cannot prove','Owner decision'],rows:[['Source event and time','A reconstructable sequence','Customer intent by itself','Define the next authorized action'],['Status, reason, and owner','Documented accountability','Quality or compliance alone','Review the exception'],['Outcome and correction','A bounded operating finding','A provider-wide result','Retest after one change']]},
  buyerChecklist:['Write the research question before selecting records.','Keep observed fields separate from interpretation.','Include ordinary cases, exceptions, and counterexamples.','Limit personal information in the research extract.','Name the client owner for decisions outside representative authority.','Repeat the same comparison after changing one control.'],
  faqs:[{q:`What does this research establish about ${draft.title.toLowerCase()}?`,a:'It establishes a bounded evidence design and operating questions. It does not establish legal compliance, customer satisfaction, or provider-wide performance.'},{q:'Who makes decisions outside the documented representative boundary?',a:'The authorized client, privacy, security, legal, or specialist owner keeps those decisions.'}],
  related:[{title:'Research library',href:'/research'},{title:'Call quality monitoring',href:'/services/call-quality-monitoring'}],sources,
});

const silence = make({
  slug:'offshore-call-center-customer-silence-closure-research',title:'Offshore call center customer silence: when is closure supported by evidence?',excerpt:'Research on unanswered follow-ups, closure reasons, promised windows, channel limits, and the evidence needed before an offshore support case is closed.',hero:'/sep3-research-heroes/offshore-call-center-customer-silence-closure-research.png',question:'When a customer stops responding, which records support closing an offshore call center case without confusing silence with resolution?',
  methodology:'We examine one case from the last customer interaction through closure. The comparison uses simulated records across phone, email, and chat, then tests their fields against five public governance, privacy, and work-organization sources. Observations, operating interpretations, and client decisions are reported separately.',
  limitations:'Silence has many possible causes. Scenario records cannot reveal customer intent, prove satisfaction, establish legal sufficiency, or estimate provider performance. Channel rules, contracts, request risk, accessibility needs, and retention duties vary by organization.',
  takeaways:['Customer silence is an observed absence, not a resolved outcome.','Closure needs a named rule, elapsed window, attempt record, and reopen path.','Channel permission limits which follow-up attempts count as appropriate.','High-risk or promised work may require client review before closure.'],
  sections:[
    {heading:'The research question starts after the last reply',citations:[1,3],text:'This September 3, 2026 study asks: when a customer stops responding, which records support closing an offshore call center case without confusing silence with resolution? The unit of analysis is one open customer request from the final two-way interaction through the closure decision. We observe the last confirmed need, promised next step, permitted contact channel, attempt history, elapsed time, dependency status, closure reason, owner, and reopen route. A missing response is a fact about the record. It does not show that the issue disappeared, that the customer understood the last message, or that the requested work finished. The study therefore treats silence as an event that starts a review window, not as a favorable disposition. That boundary matters in Philippines-based support queues where another shift or client-side owner may still hold a promised action.'},
    {heading:'Build cohorts around the promise, not the inbox state',citations:[1,5],text:'The useful comparison separates cases with no outstanding promise from cases awaiting a customer answer, a specialist decision, or an agent callback. Within each group, compare ordinary questions, time-sensitive requests, sensitive requests, and records that crossed a shift. The open or closed label alone is too coarse. A customer may be silent because the team asked a clear question, used an unavailable channel, sent a message outside the stated window, or failed to complete its own next step. Review the wording and timing of the last outbound contact alongside the original commitment. If the agent promised another update regardless of reply, customer silence does not cancel that promise. If work cannot proceed without a missing fact, the record should say exactly what is missing and which approved rule governs the waiting period.'},
    {heading:'Contact attempts need purpose and channel boundaries',citations:[2,3,4],text:'Count only attempts that fit the stated service purpose and the organization\'s approved contact rules. Possessing a phone number or email address does not by itself authorize every follow-up method. The research extract should record the channel used, purpose, attempt time, delivery evidence if available, and any customer preference or stop request. It should not copy full messages or unrelated personal data into a general report. NIST privacy concepts and Philippine privacy law help frame minimization and accountability, but they do not supply one universal attempt count. The client privacy and process owners must decide when another attempt is appropriate. A reviewer should also distinguish technical delivery failure from customer nonresponse. A bounced email, disconnected number, or failed chat notification is evidence that the attempted route may not have reached the customer.'},
    {heading:'Closure reasons should survive a second review',citations:[1,4],text:'A defensible closure reason lets another authorized reviewer reconstruct why work stopped. "No response" is incomplete unless the record also shows what answer was needed, when it was requested, which permitted attempts occurred, what promise remained, and what rule allowed closure. Sample records should include cases reopened soon after closing, because they test whether the original reason and context were usable. Reviewers should ask whether the next agent could resume without forcing the customer to repeat the whole request. They should also check whether a specialist task remained open after the frontline case closed. Split ownership can produce a clean-looking queue while a promised decision is still pending elsewhere. The finding belongs to the workflow, not automatically to the individual representative who applied the available status.'},
    {heading:'Exceptions reveal where closure authority ends',citations:[1,2,3],text:'Some silent cases should leave the routine queue without being declared resolved. Examples include a safety concern, disputed account action, privacy request, scheduled appointment change, unresolved payment issue, or a commitment controlled by a client specialist. The research does not decide the correct handling for those categories. It tests whether the record identifies the exception and reaches the authorized owner before the closure window expires. Compare accepted escalations with cases returned for missing information. A justified return can expose an unclear intake field; an unexplained return can create circular ownership. Managers should avoid turning reopen volume into an individual score until they know whether the closure rule, channel access, or client response path caused the repeat contact. One concrete repair is more testable than a broad coaching instruction.'},
    {heading:'Retest one closure rule with the definitions unchanged',citations:[1,5],text:'Select one repair, such as a clearer waiting status, an explicit promise field, a channel-failure reason, or a client review trigger. Keep the original sample definition and compare a later cohort after the change. Measure how often reviewers can identify the pending need, last permitted attempt, accountable owner, and reopen action without consulting an unstructured conversation history. Read the counterexamples. Fewer reopenings may reflect better closure, but they may also reflect customers giving up or a harder reopen path. More open cases may indicate honest visibility rather than weaker productivity. The evidence-led conclusion is narrow: closure after customer silence is supportable when the record preserves the unresolved need, applicable rule, permitted attempts, outstanding promises, owner, and safe return path. The organization must decide its own legal, contractual, and service thresholds.'},
  ]
});

const acknowledgement = make({
  slug:'philippines-call-center-escalation-acknowledgement-latency',title:'Philippines call center escalations: how long until ownership is acknowledged?',excerpt:'A record-level study of escalation acknowledgement, decision windows, shift boundaries, and customer updates in Philippines-based support.',hero:'/sep3-research-heroes/philippines-call-center-escalation-acknowledgement-latency.png',question:'What does acknowledgement latency reveal about escalations passed from a Philippines call center to an authorized decision owner?',
  methodology:'We trace simulated escalation packets from frontline send time to receiving-owner acknowledgement, decision, and customer update. Matched cohorts vary by shift, urgency, request type, and client availability. Public sources provide control comparisons rather than performance benchmarks.',
  limitations:'The study cannot establish a universal acknowledgement target, adequate staffing, causation, compliance, or customer satisfaction. Timings depend on queue scope, time zones, urgency definitions, systems, and client-side availability.',
  takeaways:['Sent time and accepted ownership are different events.','Acknowledgement latency needs an urgency rule and available owner for interpretation.','A customer update may be due before the restricted decision is ready.','Returned escalations should preserve a reason and a new owner.'],
  sections:[
    {heading:'Define the two clocks before measuring delay',citations:[1,5],text:'This September 3, 2026 research asks what acknowledgement latency reveals when a Philippines call center passes an escalation to an authorized decision owner. The unit is one restricted customer request from the frontline stop through receiving-owner acknowledgement. The first clock measures when the escalation was sent. The second measures when a qualified owner accepted responsibility for the next action. Neither clock is the final resolution time. A message appearing in a shared queue proves delivery to a system, not ownership by a person. The record needs the request category, urgency, reason for stopping, source evidence, customer promise, sent time, destination, acknowledgement time, accepted owner, and due point. Without those fields, a fast average can hide unowned cases while a slower result can reflect a deliberate review of sensitive work.'},
    {heading:'Match cases by the decision they require',citations:[1,3],text:'Compare like with like. A routine supervisor clarification should not share a latency benchmark with a privacy request, disputed financial action, safety concern, or technical change controlled by another team. Build cohorts by decision type, stated urgency, channel, Philippines shift, client time zone, and whether the receiving owner was scheduled to be available. Include cases returned to the frontline team and cases rerouted to a second specialist. The method records what happened and tests the operating definition; it does not assume that a longer interval caused a poor customer outcome. Review the packet itself. A late acknowledgement may expose coverage, but it may also begin with an escalation that lacks the question, verified context, or requested decision needed for safe acceptance.'},
    {heading:'The packet must state a question an owner can accept',citations:[1,2],text:'An escalation is easier to acknowledge when it asks for a specific decision. "Please advise" forces the recipient to reconstruct the case and may conceal what the representative has already promised. A useful packet states the customer need, actions completed, evidence checked, boundary reached, exact decision requested, customer update due, and minimum necessary context. Sensitive information should remain in the approved system rather than being copied into broad notification channels. The receiving owner should accept, reject with a reason, or reroute with a named destination. Silence from the destination is not an acknowledgement. A reaction icon or automated receipt may confirm transport, but it does not show that someone with authority owns the decision. The research records these states separately so tooling activity cannot substitute for accountable work.'},
    {heading:'Shift overlap changes availability, not authority',citations:[3,5],text:'Philippines-based teams often operate across client time zones, but overlapping hours do not expand the representative\'s authority. Record the local shift, the client owner\'s available decision window, weekends or holidays that affect the route, and the approved fallback for urgent cases. Then compare escalations arriving inside and outside those windows. An overnight team may provide prompt intake and a truthful interim update while the restricted decision waits for the client owner. That is different from leaving the customer without an owner. The customer-facing message should distinguish what is known, what is pending, who must decide, and when the next update is due. It should not invent a resolution estimate merely to make the queue appear responsive. The evidence can support a coverage discussion without implying that every decision needs continuous staffing.'},
    {heading:'Returned work is part of the latency path',citations:[1,4],text:'Measure what happens when the recipient declines an escalation. A justified rejection can prevent an unauthorized decision and reveal a missing verification step. An unexplained rejection can restart the clock without moving the case closer to an answer. Preserve the original sent time, rejection time, reason, missing item, new owner, and revised customer update. Do not overwrite the first destination when work is rerouted. That history allows reviewers to distinguish intake defects, routing defects, unavailable expertise, and unclear authority. Sample the longest and shortest cases rather than inspecting only averages. A very short acknowledgement may be an automatic acceptance that nobody acts on; a long interval may contain an immediate safe stop and regular updates. The research question concerns accepted ownership, so later action and customer communication remain necessary context.'},
    {heading:'A controlled retest turns timing into a decision',citations:[1,2,5],text:'Choose one intervention supported by the sample: clarify the escalation question, add a named backup owner, separate urgency levels, or move the acknowledgement checkpoint. Repeat the same matched cohorts and definitions after the change. Check whether more packets reach an authorized owner, whether rejection reasons become specific, and whether promised customer updates occur on time. Do not declare success from a lower median alone. Inspect cases that exceeded the window and cases accepted quickly but resolved incorrectly or without a customer update. The evidence-led conclusion is that acknowledgement latency becomes useful when send, acceptance, authority, due point, and customer promise are distinct fields. It can reveal where ownership stalls, but the client must set targets and decide whether the remedy concerns coverage, packet quality, routing, or policy.'},
  ]
});

const verification = make({
  slug:'call-center-partial-verification-safe-stop-research',title:'Call center partial verification: what should happen before a safe stop?',excerpt:'Research on incomplete identity checks, permitted assistance, escalation evidence, and customer-safe next steps in outsourced support.',hero:'/sep3-research-heroes/call-center-partial-verification-safe-stop-research.png',question:'When a customer completes only part of an approved verification process, what evidence supports a safe call center response?',
  methodology:'We compare simulated interactions at different verification checkpoints. The unit is one request from verification start to permitted action, stop, or escalation. The review observes process fields and does not reproduce credentials or real customer data.',
  limitations:'Public frameworks do not define one verification script. This study cannot determine identity, fraud, legal compliance, security adequacy, or customer intent. Each organization must set controls for its systems, risks, contracts, and request types.',
  takeaways:['Partial verification is a process state, not partial permission.','The representative needs a permitted response for each failed or unavailable step.','Research extracts should record checkpoints without exposing credentials.','Restricted actions stay with the authorized security or client owner.'],
  sections:[
    {heading:'Study the checkpoint, not the customer',citations:[1,2,3],text:'This September 3, 2026 study asks what evidence supports a safe response when a customer completes only part of an approved verification process. The unit is one support request from the first identity checkpoint to a permitted action, stop, or escalation. The research record notes the request type, verification method version, checkpoints attempted, result category, system condition, permitted alternative, representative action, escalation owner, and customer-facing next step. It does not contain passwords, answers, document images, full identifiers, or live customer records. Partial completion does not create partial authority to disclose or change protected information. Nor does a failed step prove bad intent. The operating question is whether the representative followed a defined boundary and left the customer with an accurate, usable path that did not weaken the control.'},
    {heading:'Separate mismatch, absence, and system failure',citations:[1,4],text:'A single "verification failed" label hides different mechanisms. The customer may provide information that does not match, be unable to access a factor, decline a channel, encounter an unavailable system, or request an action outside the process. Build cohorts for each state and compare routine and sensitive requests. Record only the category needed for review. A system outage should not be interpreted as customer failure, and an accessibility barrier should not be treated as suspicious behavior without an approved basis. The representative needs a documented response for each category: retry under stated limits, use an approved alternative, provide general information that requires no protected access, pause, or escalate. The research tests whether that route is visible and consistently applied. It does not decide which authentication strength is appropriate for the organization.'},
    {heading:'Observe what the representative does after stopping',citations:[1,2],text:'A safe stop is an action, not an empty refusal. Review the language used, the information withheld, the alternative offered, the next owner, and any promised follow-up. The representative should avoid confirming protected details through the wording of the refusal. General help may still be possible, but the boundary must be written by the client owner rather than improvised during a difficult interaction. Compare cases that end at the same checkpoint but receive different next steps. Variation can reveal unclear instructions, unavailable escalation coverage, or a system design that encourages workarounds. It can also reveal legitimate differences between request types. Read the source record with restricted access and keep the research extract minimal. The goal is to assess process evidence without creating a new collection of sensitive verification data.'},
    {heading:'Retries can become a security and service question',citations:[1,3,4],text:'Record the approved retry rule, the number of attempts as a category, any lock or pause state, and who may authorize another route. Do not publish a detailed bypass recipe. A short call may reflect a correct stop, while a long call may contain repeated prompts that frustrate the customer without improving assurance. Compare cases resolved through an approved alternative with cases escalated and cases abandoned after the stop. The result should not rank representatives solely by handle time or completion. Managers need to know whether the process offered a reachable next step and whether restricted requests stayed protected. Client security and privacy owners should review any proposal that changes factors, retry limits, data access, or retention. The offshore team can document the event and follow the route; it should not redefine the organization\'s identity standard.'},
    {heading:'Counterexamples test whether the rule is usable',citations:[2,5],text:'Include scenarios where the customer is traveling, cannot use the usual channel, requires accessibility support, contacts the queue after client hours, or passes one factor while the source system remains unavailable. These cases test whether the instruction distinguishes human circumstances from control outcomes. Ask two trained reviewers to state the permitted next action from the same record. Disagreement is evidence that the rule, example, or authority boundary needs work. It is not solved by choosing whichever answer completed the request. Compare the point of disagreement and the information each reviewer relied on. If the alternative route needs a client specialist, verify that the escalation can be accepted during the relevant coverage window. If no safe path exists, the customer message should be truthful about the stop without suggesting that persistence will bypass it.'},
    {heading:'Retest the path without weakening the boundary',citations:[1,3],text:'Change one element supported by the review, such as the result categories, a general-information fallback, an escalation packet, or an accessibility route. Keep the verification standard unchanged unless the authorized owner separately approves a control change. Repeat the same scenarios and compare whether reviewers identify the state, permitted response, and next owner more consistently. Track corrections and unauthorized workarounds as separate outcomes. A higher completion rate is not automatically better if protected actions moved forward without the required evidence. The evidence-led conclusion is narrow: a partial verification safe stop is observable when the record identifies the checkpoint state, preserves the control, limits data exposure, gives an approved next step, and routes restricted decisions to the right owner. Legal, fraud, and security conclusions remain outside this scenario study.'},
  ]
});

const callback = make({
  slug:'offshore-call-center-hold-to-callback-conversion-study',title:'Offshore call center hold-to-callback conversion: does context survive?',excerpt:'A study of long-hold callbacks, customer choice, context preservation, queue ownership, and completed contact evidence.',hero:'/sep3-research-heroes/offshore-call-center-hold-to-callback-conversion-study.png',question:'When an offshore call center converts a long hold into a callback, what evidence shows that the customer did not lose their place or context?',
  methodology:'We trace simulated interactions from the offered callback through final disposition. Cohorts compare continued holds, accepted callbacks, declined callbacks, unreachable customers, and callbacks dependent on specialists across shifts.',
  limitations:'Scenario evidence cannot establish a universal hold threshold, staffing level, satisfaction effect, causation, or provider performance. Telephony behavior, consent rules, queue design, accessibility, and customer needs differ.',
  takeaways:['A callback offer must preserve customer choice and the original queue context.','Leaving the live queue is not proof that the work has an owner.','Attempt evidence and completed-contact evidence are different.','Specialist dependencies and shift crossings need explicit due points.'],
  sections:[
    {heading:'The conversion is a new ownership event',citations:[1,5],text:'This September 3, 2026 study asks whether customer context survives when an offshore call center converts a long hold into a callback. The unit is one interaction from the callback offer through completed contact, customer decline, permitted closure, or escalation. Observe the original request, queue position or wait state available to the system, offer wording, customer choice, contact channel, promised window, verification state, context packet, assigned owner, dependency, attempt record, and outcome. The research does not assume that leaving the live queue improves service. A callback can reduce time spent waiting while also creating a second opportunity for lost context or unclear ownership. The customer should know what will happen next, and the internal record should preserve enough information for the callback owner to continue safely.'},
    {heading:'Compare callbacks with the alternatives customers faced',citations:[1,2],text:'Create separate cohorts for customers who remained on hold, accepted a callback, declined it, disconnected before choosing, or requested another channel. Match cases by request type, time band, shift, urgency, and need for a specialist. Do not compare an easy status question with a restricted decision and call the time difference a callback effect. Review the original offer and later action. A recorded selection shows a choice in the system, but not necessarily that the customer understood the window or permitted a different contact purpose. A callback attempt does not equal a completed conversation. The study separates offered, accepted, assigned, attempted, connected, and completed states. This sequence shows where the work can fail without turning one queue metric into a claim about customer satisfaction.'},
    {heading:'The context packet should be small and sufficient',citations:[2,3,4],text:'The callback owner needs the customer\'s stated need, relevant verification status, actions already taken, source version used, unresolved question, restricted boundary, and promised timing. They do not need an unrestricted copy of every interaction detail. Review whether the receiving owner can explain the next action without asking the customer to repeat material facts, while still performing any verification that policy requires. A repeated question may be a necessary security step rather than a context failure, so classify the reason. Keep personal data in the approved customer system and use coded identifiers in research extracts. Privacy sources support purpose and accountability comparisons, but the client decides the lawful basis, retention period, and access model. More notes are not automatically better if they spread sensitive information or bury the actual request.'},
    {heading:'A promise window needs a clock and a dependency owner',citations:[1,5],text:'Record the time convention used for the promised callback, especially when a Philippines shift serves customers in another region. If the callback depends on a client specialist, show the dependency owner and available decision window. The frontline team should not invent a completion estimate that the specialist has not accepted. Compare callbacks completed inside one shift with those crossing a handoff, weekend, outage, or client-hours boundary. Measure time to assignment, first permitted attempt, connection, and final next step separately. A timely attempt to an invalid number is not the same as a completed callback. An overdue contact with regular truthful updates differs from a case that disappeared after leaving the live queue. These distinctions let managers choose a routing or coverage test without promising a result the records cannot support.'},
    {heading:'Unreachable outcomes need a return path',citations:[2,4],text:'Study what happens when the customer does not answer. The record should retain the approved attempt rule, channel permission, result category, outstanding request, next review time, and closure or reopen path. It should distinguish no answer, technical failure, wrong contact detail, customer reschedule, and a stop request. Do not broaden the purpose or channel merely to complete the task. If the original interaction involved a restricted or urgent issue, the client owner may require a different escalation rather than routine closure. Review cases that later return through another channel. Ask whether the new representative can find the callback history and original commitment. A reopened case is not automatically a failure, but it is a useful test of whether the conversion preserved context and ownership.'},
    {heading:'Retest the conversion at its weakest transition',citations:[1,3,5],text:'Choose the point where evidence most often disappears: offer wording, assignment, context transfer, specialist dependency, attempt status, or closure. Change one field or routing rule and repeat the matched comparison. Keep customer choice visible and inspect both successful and unsuccessful contacts. A lower hold count may simply mean more work moved into an unobserved callback queue. A higher connection rate may reflect easier cohorts rather than a better process. The evidence-led conclusion is that hold-to-callback conversion is supportable when the customer chooses the route, the original request and boundaries remain available, a named owner accepts the promise, each dependency has a due point, and the final contact or return path is evidenced. Staffing, satisfaction, and compliance conclusions require separate authorized analysis.'},
  ]
});

const correction = make({
  slug:'call-center-post-closure-correction-propagation',title:'Call center post-closure corrections: which records need the revised answer?',excerpt:'Research on corrections discovered after case closure, affected-record tracing, customer recontact authority, and knowledge-source repair.',hero:'/sep3-research-heroes/call-center-post-closure-correction-propagation.png',question:'When a call center discovers that a closed case used an incorrect answer, how can it identify which records need correction without over-contacting customers?',
  methodology:'We start with one confirmed answer correction and trace simulated affected records through source version, case review, owner decision, and permitted customer follow-up. The evidence scope excludes real customer data and does not estimate prevalence.',
  limitations:'This study cannot decide legal notification duties, materiality, remedy, customer harm, causation, or provider quality. Organizations must define affected scope, authority, retention, and contact rules with appropriate owners.',
  takeaways:['A corrected knowledge article does not repair closed customer records by itself.','Affected scope depends on source version, effective time, request context, and action taken.','Customer recontact requires an authorized purpose and owner.','The correction trail should preserve the old answer without leaving it available for routine use.'],
  sections:[
    {heading:'Start with the confirmed correction event',citations:[1,2],text:'This September 3, 2026 study asks how a call center can identify closed records that need a revised answer without over-contacting customers. The unit begins with one confirmed correction: a named source owner states that a prior answer was wrong, incomplete, expired, or applied outside its boundary. Record the old source version, corrected version, effective time, affected request types, reason, approving owner, and action categories that may require review. The research does not treat every view of the old article as customer impact. It traces whether a representative used that version in a relevant interaction and what action followed. Publication of a replacement source fixes future discovery only if search results, macros, training examples, and cached instructions stop surfacing the prior wording. Closed cases remain a separate evidence problem.'},
    {heading:'Define affected scope before searching customer records',citations:[1,3,4],text:'The source owner and appropriate client reviewers should define which products, dates, channels, request types, jurisdictions, and actions fall inside the review. A broad text search can collect unrelated records and expose more personal information than the investigation needs. Begin with version identifiers, effective windows, queue, and disposition categories where possible. Use coded case references in the research extract and keep customer details in the approved system. Separate confirmed affected cases, possibly affected cases, and excluded cases with a documented reason. The study should report uncertainty rather than forcing ambiguous records into a clean count. Philippine privacy law and regulator rules provide accountability and processing context, but they do not decide the organization\'s notification or remedy duty. Those decisions remain with authorized privacy, legal, security, and business owners.'},
    {heading:'Usage evidence is different from consequence evidence',citations:[1,2],text:'A record may show that the old source opened, that its wording entered a macro, that an agent sent the answer, or that a downstream action occurred. These are different evidence levels. Build cohorts around what can actually be reconstructed. If the interaction record is incomplete, mark the consequence unknown. Do not assume a customer relied on the answer merely because it appeared on screen, and do not assume there was no effect because the case closed without complaint. Review a sample of excluded and included cases to test the scope rule. Counterexamples are useful: a representative may have opened the old article but escalated instead of using it, or may have stated the incorrect answer from a separate template. The correction process should find both without claiming certainty beyond the available records.'},
    {heading:'Recontact is a client-owned decision',citations:[2,3,4],text:'For each confirmed affected case, the record should show the requested decision: correct the internal note, repair an account action, contact the customer, notify another owner, or preserve evidence pending review. The offshore representative should not decide materiality, legal notice, compensation, financial remedy, or a new contact purpose unless the client has explicitly documented that authority. If recontact is approved, preserve the reason, permitted channel, message source, owner, timing, outcome, and stop request. A customer\'s historical contact detail is not blanket permission for unrelated outreach. Corrections should be accurate without speculating about harm or blaming an individual agent before the source and workflow are examined. The investigation may reveal a source defect, adoption gap, cached template, routing failure, or a combination.'},
    {heading:'Retire the old answer without erasing the trail',citations:[1,5],text:'Authorized reviewers may need the prior version to reconstruct what happened, but routine representatives should not continue finding it as a current answer. Preserve the old record in a controlled history, label its effective boundary, update links and macros, and test common search phrases. Record which queues received the corrected instruction and whether they can identify the changed cases they own. Training completion or a read receipt shows exposure, not safe application. Use short scenarios to test the new boundary, including an ordinary request, an exception, and a case that started before the effective time. Distributed teams need one source owner and a clear transition time across shifts. The correction remains open until future use is controlled and the defined affected-record review reaches its accountable owners.'},
    {heading:'Close the review with exclusions and a retest',citations:[1,2,3],text:'Document the search window, systems checked, unavailable records, inclusion logic, exclusions, decision owners, and unresolved cases. Then sample interactions after the correction to see whether the retired answer still appears and whether representatives use the new boundary correctly. Do not compare raw correction counts across periods without accounting for request volume, source visibility, and the breadth of the review. A larger affected set may reflect better tracing rather than worse performance. The evidence-led conclusion is narrow: post-closure correction propagation is reviewable when a confirmed source change defines the affected scope, record-level evidence distinguishes exposure from action, authorized owners decide customer follow-up, and the old answer is controlled without erasing history. The study cannot determine legal duties or customer harm, but it can show whether the operational correction reached the records and people it was meant to reach.'},
  ]
});

export const september3ResearchBatch: readonly ResearchPost[] = [silence,acknowledgement,verification,callback,correction];
