import type {ResearchPost} from './fleet-data';
const sources:ResearchPost['sources']=[
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Risk-management guidance for governance and operational controls.',kind:'Global comparison'},
 {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy-risk guidance for purpose, processing, and safeguards.',kind:'Global comparison'},
 {name:'Philippine Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary Philippine source for personal-information processing and accountability.',kind:'Philippines'},
 {name:'FTC Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',note:'Official guidance on access, retention, disposal, and service-provider safeguards.',kind:'Global comparison'},
 {name:'ILO Working from home guide',url:'https://www.ilo.org/publications/working-home-guide',note:'International reference for organizing and governing remote work.',kind:'Global comparison'},
 {name:'Philippine Telecommuting Act',url:'https://lawphil.net/statutes/repacts/ra2018/ra_11165_2018.html',note:'Primary Philippine legal text concerning private-sector telecommuting.',kind:'Philippines'}
];
type T={slug:string;title:string;excerpt:string;question:string;finding:string;focus:string;heads:string[];p:string[]};
const topics:T[]=[
 {slug:'call-center-customer-intent-coding-validity',title:'Call center customer-intent coding validity: can the label support a decision?',excerpt:'A study of intent definitions, mixed requests, reviewer agreement, and the limits of contact-reason data in outsourced support.',question:'When can a call center customer-intent label be trusted enough to inform staffing, knowledge, or routing?',finding:'An intent label is useful only when its definition, evidence, reviewer agreement, and downstream decision are visible.',focus:'customer-intent coding',heads:['The question is validity, not volume','Build a label from the customer task','Study disagreement and mixed intent','Keep coding separate from diagnosis','Limitations of contact-reason research','Conclusion: make labels decision-ready'],p:[
'Customer-intent reporting turns a conversation into one short label, but a second request, failed prior answer, or sensitive exception can disappear. This study asks when a label can support a decision in an offshore call center. The finding is that a label becomes decision-ready only when it describes the customer task, can be applied consistently, and supports a narrow action. A count of billing calls is an observation, not proof that billing policy, staffing, or training caused demand. [1][2][3]',
'State whether the label describes the first reason, the reason requiring work, the escalation reason, or the outcome. These are different fields. Sample routine, repeat, transferred, and unresolved contacts, removing unnecessary personal information. For a Philippines-based team include channels, shifts, language, and handoff routes because the same request may be coded differently after transfer. Keep original wording separate from the controlled field when the purpose justifies it. [2][3][4]',
'Give reviewers identical cases without showing the existing label. Record independent choices and disagreement. A mixed request may need primary and secondary fields; forcing one answer creates false certainty. Track unclear, out-of-taxonomy, and insufficient-record states. The representative documents and routes uncertainty; a process owner decides whether the taxonomy changes or a trend warrants intervention. [1][4]',
'A valid label does not diagnose root cause. Password-reset demand may reflect a product change, identity check, unavailable self-service, or reporting change. Read coded results beside repeat contact, answer version, transfer, wait, and closure. Compare defined periods and state exclusions. Do not call a routing change causal when staffing, campaigns, or request mix also changed. [1][2][5]',
'This study cannot establish a universal taxonomy, infer sentiment, or prove completeness. Samples miss rare cases, reviewer skill affects agreement, and categories can reflect system paths rather than customer need. State queue, channel, language, period, sampling, exclusions, and owner. Privacy, legal, and accessibility questions require qualified review when interactions contain sensitive information. [2][3]',
'The conclusion is to publish a limited taxonomy with definitions, examples, stop conditions, and an owner who reviews disagreement. Use labels to ask better questions about routing and staffing, not to make unsupported provider claims. Retest after a product or policy change. [1][2][4]']},
 {slug:'offshore-call-center-after-call-work-evidence',title:'Offshore call center after-call work: what should the record prove?',excerpt:'A source-backed examination of note quality, customer promises, and the tradeoff between speed and decision-ready records.',question:'What evidence shows that after-call work is complete enough for the next owner without rewarding rushed documentation?',finding:'After-call work is complete when the required customer, decision, ownership, and next-step record exists with minimum necessary data.',focus:'after-call work evidence',heads:['The research question','Define completion by the next decision','Measure work without hiding risk','Test notes across request types','What timing cannot prove','Conclusion: quality before seconds'],p:[
'After-call work is often treated as a timer between the customer ending a call and the representative becoming available. That timer matters for capacity, but this study asks what the record should prove in a Philippines-based queue. Completion is a decision condition: the next owner knows what was requested, verified, done, unresolved, and owned. A short note can omit a promise; a long note can copy unnecessary personal data. [1][2][3]',
'Define required fields by request type. A routine status request may need verified identifier, status, answer, and next action; an exception may need evidence, approval boundary, due point, and escalation owner. Compare the note with system events and customer promises. Test shift changes and client time-zone handoffs because a note usable by one representative may fail the next owner. The representative records permitted facts; the authorized owner decides restricted remedies. [2][3][5]',
'Measure duration beside quality. Sample fast, median, and slow records and score accuracy, required fields, privacy, ownership, and next-step clarity. Separate complex work from avoidable rework. If after-call time falls after coaching, do not claim causation without considering volume, case mix, latency, or a changed form. Show missing saves, unowned callbacks, and returned escalations. [1][4]',
'Use matched scenarios: routine information, conflicting records, a sensitive request, an approved callback, and a case waiting on the client. Review the note and receiving owner action. A good handoff prevents repetition without unauthorized disclosure. Representatives should escalate ambiguity with a precise question rather than invent policy. [2][3][4]',
'Timing cannot establish customer value, continuous quality, or worker wellbeing. Longer time may reflect harder work or better documentation; shorter time may reflect missing work. Samples miss rare privacy incidents. State queue, period, note fields, reviewer method, and exclusions; keep qualified privacy and employment review separate. [3][5][6]',
'The conclusion is to set an evidence-based completion rule and measure speed second. Require minimum context, a due point, and escalation. Expand a Philippines-based queue only after records show continuity without sacrificing control. [1][2]']},
 {slug:'philippines-call-center-ivr-containment-research',title:'Philippines call center IVR containment: when does self-service really work?',excerpt:'A study of completed customer tasks, safe exits, transfers, and hidden repeat contacts in an outsourced voice queue.',question:'What evidence distinguishes a completed IVR task from a caller who simply left the automated path?',finding:'IVR containment is meaningful only when the customer task is completed or safely handed off, not when the caller disappears.',focus:'IVR containment',heads:['Containment is not abandonment','Define the customer task','Trace exits and repeat demand','Protect exception routes','Study limitations','Conclusion: measure completion'],p:[
'An IVR report may call a call contained because a caller selected a menu, heard an answer, or disconnected before reaching a representative. This study asks when containment is real for a Philippines-based call center. The unit should be a completed task or explicit safe handoff. A caller who hangs up after failing to understand a menu is not evidence of successful self-service. [1][2][4]',
'Write the task before examining the metric. Checking delivery, changing payment, and reporting safety have different evidence and hard stops. Map prompt, authentication, answer source, transfer, and confirmation. Make a representative reachable for ambiguity, accessibility, failed verification, or restricted action. Preserve the IVR path and transfer reason so a Philippines-based representative avoids unnecessary repetition. [2][3][5]',
'Trace outcomes with a privacy-conscious identifier. Compare completed self-service, assisted completion, abandoned, repeat, and escalated cohorts. Review audio or transcripts for dead ends and outdated wording. A lower transfer rate can mean better self-service, routing change, or more callers giving up. Check next-day repeat and unresolved work before claiming improvement. [1][4]',
'Test normal, changed-policy, failed-authentication, language, accessibility, and restricted-action cases. Record whether the path offers an alternative, preserves allowed context, and reaches an acknowledged owner. Do not collect extra information merely because automation failed. Sources support safeguards but do not prove this IVR’s effectiveness; queue-specific evidence is required. [2][3][4]',
'Containment research cannot prove caller intent when an interaction ends silently, predict demand, or establish accessibility across devices and languages. Logs may omit comprehension and repeats may arise from product problems. State flow version, dates, sample, exclusions, and owner for changes. [1][2][5]',
'The conclusion is to report completion, safe transfer, abandonment, and repeat separately. Expand automation only when customers can finish the defined task, reach a person when needed, and avoid repetition or disclosure. [1][3]']},
 {slug:'call-center-escalation-queue-aging-evidence',title:'Call center escalation-queue aging: what should trigger intervention?',excerpt:'A study of age, dependency, urgency, ownership, and customer promises in an offshore escalation queue.',question:'How should a buyer distinguish harmless waiting from an aging escalation about to create customer harm?',finding:'Age is a warning signal; intervention depends on dependency, due point, risk, owner, and the next customer-facing action.',focus:'escalation-queue aging',heads:['The question behind the age report','Model dependency, not just elapsed time','Test ownership at the edges','Separate age from outcome','Limitations','Conclusion: intervene before the promise fails'],p:[
'An escalation queue sorted by age makes overdue work visible, but age alone cannot tell a manager what to do. This study asks what should trigger intervention. Age becomes actionable when joined to customer promise, dependency, risk, authorized owner, and next action. A case waiting for a customer document differs from a payment exception awaiting approval, even if both are two days old. [1][2][3]',
'Capture request, verification, escalation question, dependency, promised date, owner, acknowledgement, and update. Use minimum context and keep restricted decisions with the client or specialist. For Philippines coverage, test local holidays, shift boundaries, overnight handoffs, backup supervisor, and client-time-zone overlap. A named person without reachable coverage is not control. [3][5][6]',
'Review urgent, ordinary, promised, blocked, and returned cohorts separately. Measure acknowledgement, decision time, promise misses, repeat contact, and closure evidence. An old case may wait on a customer while a new case with an imminent promise needs action. If an alert reduces age, check whether work was resolved, transferred, or relabeled. [1][4]',
'Run edge-case drills outside schedule: incomplete context, conflicting records, restricted decision, and unavailable owner. Score safe stopping, precise question, customer expectation, and backup. Do not reward closing without an authorized answer. [2][3]',
'Aging data cannot establish harm in every case or forecast policy-decision time. Timestamps differ across systems and low volume hides rare cases. State definitions, time zone, scope, period, and exclusions; qualified owners handle legal, financial, safety, and privacy decisions. [1][2][4]',
'The conclusion is to alert on promise and dependency risk before relying on age. Keep owner, due point, update, and blocked reason visible. Judge a Philippines-based queue on timely intervention, not merely on how many old cases disappear. [1][3]']},
 {slug:'offshore-call-center-qa-calibration-drift',title:'Offshore call center QA calibration drift: how can scores stay comparable?',excerpt:'A research-led look at scorecard versions, reviewer disagreement, coaching effects, and limits of comparing quality scores.',question:'What evidence shows that quality scores remain comparable after people, policies, or reviewers change?',finding:'Calibration is a measurement-control problem: score changes may reflect the rubric, sample, or reviewer rather than queue performance.',focus:'QA calibration drift',heads:['The score is not the whole evidence','Version the rubric and sample','Find disagreement before coaching','Separate correction from causation','What calibration cannot show','Conclusion: preserve comparability'],p:[
'Quality scores look precise, yet they change when rubric, sample, reviewer, or request mix changes. This study asks how a Philippines-based call center can detect calibration drift. Comparability requires a versioned scorecard, shared anchor cases, reviewer agreement, and a record of what the score measures. An 82-to-88 rise is not automatically improvement; it may reflect easier cases or omitted hard errors. [1][2][4]',
'Define each criterion as observable behavior tied to customer or control risk. Separate accuracy, identity, permitted action, notes, tone, and next step instead of hiding a privacy error in an average. Keep scorecard version, sample, channel, language, shift, and reviewer role. Test office and approved remote work because location or access can change evidence. [2][3][5]',
'Use anchor cases after a policy change and have reviewers score independently. Document disagreement; do not suppress legitimate uncertainty. Unclear criteria go to the policy owner. Representatives receive feedback on work in role; managers decide training, access, escalation, and whether a score supports queue decisions. [1][4]',
'When scores move, compare errors and outcomes: correction, repeat, safe closure, escalation, and policy version. A coaching intervention may coincide with demand or staffing changes. Review high, low, fast, and slow cases, including hard stops and legitimate exceptions, so the rubric does not drift toward speed alone. [1][2][4]',
'Calibration cannot prove continuous behavior, satisfaction, or fairness of every management use. Samples may be non-random and a rubric can omit a risk. It cannot replace privacy, employment, accessibility, or legal review. State period, population, sample, reviewers, missing records, and changes. [3][5][6]',
'The conclusion is to treat QA as versioned measurement. Retain anchors, record disagreement, separate hard errors from coaching, and read scores beside outcomes and role boundaries before expanding work. [1][2]']},
 {slug:'philippines-call-center-absence-continuity-study',title:'Philippines call center absence continuity: what should a backup prove?',excerpt:'A study of open work, access, knowledge, supervision, and customer promises when an assigned representative is unavailable.',question:'What evidence shows that a Philippines call center can protect open customer work during absence?',finding:'Continuity is demonstrated by an executable handoff with access, knowledge, ownership, and customer communication—not a backup name on a roster.',focus:'absence continuity',heads:['Continuity starts with open work','Test the backup’s real path','Protect access and customer context','Observe planned and sudden absence','Limitations','Conclusion: prove recoverability'],p:[
'A staffing plan can name a backup while leaving a customer case, system access, knowledge, or escalation authority with the absent person. This study asks what absence continuity should prove. Continuity is a chain: open work is identified, the next owner can access permitted systems, the answer source is current, the promise remains visible, and a supervisor can decide exceptions. A roster is intention; an acknowledged handoff is evidence. [1][3][5]',
'Sample routine, callback, sensitive, and waiting cases. Record status, verified context, next action, due time, expectation, owner, escalation, and acknowledgement. Test an approved alternate location only if it is in the operating model, documenting device, network, privacy, recording, and authentication. Share minimum context. The client retains policy, financial, legal, and restricted decisions. [2][3][6]',
'Run planned and sudden-absence exercises. Compare handoff completeness, acknowledgement, repeat explanation, missed promises, and access failures. Include recently changed knowledge and an unavailable owner. If the backup cannot act, the safe result is an escalation and customer update, not an invented answer. Include Philippine holiday, shift, and timezone assumptions. [1][5]',
'Inspect the boundary between people and systems. Remove access after role change, confirm the backup receives the right queue, and verify notes do not expose excess data. A spare link addresses one dependency; it does not solve missing authority or stale knowledge. [2][4]',
'An exercise cannot prove every outage, absence pattern, or volume. A prepared drill may overstate sudden recovery, while one failed handoff may not generalize. State scenario, queue, participants, data handling, success criteria, exclusions, and unresolved dependencies. [1][3][5]',
'The conclusion is to define continuity as recoverable customer work, not substitute headcount. Require acknowledged handoff, safe access, current answer, promise, and decision owner before expanding a Philippines-based operation. [1][2]']},
 {slug:'call-center-callback-window-accuracy-study',title:'Call center callback-window accuracy: can customers rely on the promise?',excerpt:'How to study callback windows, dependencies, time zones, failed attempts, and closure evidence in outsourced customer support.',question:'What evidence shows that a callback window is accurate enough to use as a customer promise?',finding:'A callback window is credible when owner, dependency, time zone, attempt rule, and fallback are defined and measured against the promise.',focus:'callback-window accuracy',heads:['A callback is a promise','Define the window and dependency','Measure attempts and outcomes','Keep representatives within authority','Limitations','Conclusion: promise only what the queue can own'],p:[
'“We will call you back soon” creates a new failure if no owner, due point, or dependency is recorded. This study asks when a callback window is reliable in an offshore call center. A window is a customer promise, not merely a task label. Evidence identifies request, time zone, owner, dependency, attempt path, and closure. A timely call to an unverified destination is not success. [1][2][3]',
'Define who may offer the window, latest time, channel, expectation, and failure path. A representative records a request and offers approved windows; the client or specialist controls exceptions and remedies. Compare customer timezone with Philippines schedule, holiday, shift, and client decision availability. Record minimum contact data and follow withdrawal rules. [2][3][6]',
'Study routine, urgent, unreachable, wrong-number, rescheduled, and blocked callbacks separately. Measure acknowledgement, first attempt, contact, update, missed promise, repeat contact, and closure. Distinguish customer-requested change from queue miss. A lower miss rate may result from closing hard cases, so inspect whether the issue was resolved. [1][4]',
'Test handoff when the original representative is off shift. The next owner needs due point, verified context, approved action, and escalation without unnecessary details. If a specialist is unavailable, send an approved update or escalate before expiry. Do not invent compensation or policy. [2][5]',
'Callback research cannot prove satisfaction, ownership of a number, or peak-season performance. Manual timestamps may be inaccurate and low volume hides misses. State channel, time zone, definition, sample, exclusions, and owner; legal and privacy rules vary by market. [3][4][6]',
'The conclusion is to offer only a window the queue can observe and own. Keep promise, dependency, owner, attempt, update, and closure separate, intervening before the due time. [1][2]']},
 {slug:'offshore-call-center-knowledge-staleness-detection',title:'Offshore call center knowledge staleness: how can a queue detect old answers?',excerpt:'A research question about source ownership, effective dates, exceptions, search behavior, and correction evidence in outsourced support.',question:'What evidence shows that a knowledge answer is still safe to use in an offshore call center?',finding:'Freshness is a controlled relationship between source, effective date, version, affected request, and observed use—not an edit timestamp alone.',focus:'knowledge staleness',heads:['Stale is a decision risk','Define the answer’s effective boundary','Test use in the real queue','Route uncertainty safely','Limitations','Conclusion: freshness needs evidence'],p:[
'A knowledge article can have a recent edit date and still contain an old exception, while an older article may remain correct. This study asks how an offshore call center detects stale answers. Freshness depends on source owner, effective boundary, affected requests, visible version, retired wording, and actual use. A timestamp cannot prove a representative saw the intended answer or that the policy is correct. [1][2][4]',
'Record authoritative source, approver, effective date, expiry or review trigger, impacted queues, exception route, and prior version. Search should distinguish current from retired wording. In a Philippines delivery environment test propagation across shifts, locations, systems, and client timezone handoffs. Policy owners approve meaning; representatives apply the boundary and record uncertainty. [2][3][5]',
'Sample recent changes, repeat topics, old content, escalations, and corrections. Compare displayed and used versions with customer outcome. Track correction, repeat, escalation, search failure, and mismatch. A lower correction rate may reflect easier demand or more transfers, so read records and state period. [1][4]',
'Test current, retired, and ambiguous answers. The safe path identifies source, refuses to guess, preserves minimum context, and reaches an owner. Do not solve a missing policy by expanding frontline authority. Review early interactions after a release. [2][3]',
'Staleness evidence cannot prove every representative read an update, legality in every jurisdiction, or future behavior. Search logs omit informal coaching and short windows miss rare exceptions. State scope, queue, versions, period, sample, and exclusions; qualified owners review high-risk consequences. [1][2][3]',
'The conclusion is to govern knowledge as a live control. Make ownership, effective date, exceptions, retirement, propagation, and correction evidence visible before expanding queue scope. [1][4]']},
 {slug:'call-center-sensitive-case-routing-evidence',title:'Call center sensitive-case routing: what proves a hard stop works?',excerpt:'A bounded study of privacy-sensitive, vulnerable, disputed, and urgent contacts in outsourced support.',question:'What evidence shows a call center can route a sensitive case without excess disclosure or unauthorized decision?',finding:'A hard stop works when its trigger, minimum record, safe language, owner, acknowledgement, and fallback are tested.',focus:'sensitive-case routing',heads:['Sensitive is an operational boundary','Define triggers without over-collecting','Study the route and acknowledgement','Separate recognition from decision','Limitations','Conclusion: make the stop executable'],p:[
'Sensitive work may involve personal data, vulnerability, safety, disputed transactions, legal allegations, or authority beyond the representative. This study asks what proves routing works. Recognition is not enough: an observable trigger, minimum record, approved language, acknowledged owner, and fallback are required. “Escalate anything unusual” creates inconsistency and excess disclosure. [1][2][3]',
'Define triggers with examples and counterexamples. Record request, verification, safe summary, urgency, owner, due point, and expectation. The representative explains approved next steps and stops unauthorized action; an authorized owner decides remedy, policy, legal, or safety matters. Test shift, location, device, privacy, and client-timezone handoff for a Philippines team. [2][3][5]',
'Trace recognition through acknowledgement, decision, update, and closure. Compare routine-sensitive, urgent, disputed, and false-positive cohorts. Measure missing context, unnecessary fields, delay, repetition, wrong owner, and returned escalation. A high routing rate is not success if customers receive no update. [1][4]',
'Run role-play and live review with an ambiguous signal, conflicting information, unavailable access, and unavailable supervisor. The safe answer may be to pause, preserve minimum context, and use backup. Do not let a sensitive label become a diagnosis or expose a full conversation to every reviewer. [2][3]',
'Tests cannot prove every rare case is recognized or legal rights are satisfied. Reviewers disagree and drills are cleaner than pressure. State queue, sample, definitions, reviewer, period, and qualified owner. [1][2][4]',
'The conclusion is to make hard stops executable routes, not slogans. Test trigger, minimum data, acknowledgement, update, backup, and closure before scope expands. [1][3]']},
 {slug:'philippines-call-center-connectivity-failover-evidence',title:'Philippines call center connectivity failover: what can a test actually prove?',excerpt:'A study of voice, authentication, records, privacy, and human ownership during connectivity disruption in Philippines-based support.',question:'What evidence shows a Philippines call center can continue or recover support when connectivity fails?',finding:'A spare link is one dependency; failover is credible when customer path, systems, people, privacy, and recovery decisions are tested together.',focus:'connectivity failover',heads:['The dependency chain matters','Test customer impact, not the device','Keep work and access controlled','Observe recovery decisions','Limitations','Conclusion: failover is an operational promise'],p:[
'Connectivity plans list a second provider, power, or alternate location. This study asks what a failover test proves for a Philippines-based call center. A credible test follows customer impact through telephony, authentication, records, recording, notes, supervisor contact, privacy, and recovery ownership. A link can work while the queue cannot save a case or reach a decision-maker. [1][3][5]',
'Map the chain and define channels, requests, languages, systems, locations, devices, and hours. State fallback customer message and allowed actions during outage. Philippine telecommuting law provides context but does not prove an alternate location is approved for a particular system. Access and privacy owners verify the actual path. [2][3][6]',
'Measure calls, connection, authentication, save, recording, note, escalation, update, and recovery. Include partial failure: telephony may work while CRM or identity fails. Representatives stop actions requiring unavailable evidence and use approved fallback. Do not create shadow records with unnecessary data to preserve counts. [1][4]',
'Test whether a supervisor can declare degraded service, narrow scope, communicate, assign work, and authorize recovery. Inspect device, network, recording, and access at alternate Philippine locations. A tabletop exposes ownership gaps; it does not grant frontline authority to bypass identity. [2][5][6]',
'An exercise cannot establish every weather event, outage, staffing shortage, or simultaneous failure. A scheduled test benefits from preparation and does not prove legal compliance or continuous availability. State scenario, start condition, queue, participants, data handling, criteria, exclusions, and risks. [1][3][4]',
'The conclusion is to treat failover as a bounded promise. Prove what customers reach, what saves, what stops, who communicates, and how recovery is verified before expanding the queue. [1][2]']}
];
const related=[{title:'Research library',href:'/research'},{title:'Inbound customer care service',href:'/services/inbound-customer-care'}];
export const august19ResearchBatch:readonly ResearchPost[]=topics.map((t,i)=>({slug:t.slug,title:t.title,excerpt:t.excerpt,published:'2026-08-19',modified:'2026-08-19',revision:`2026-08-19-${t.slug}-v1`,readingMinutes:11,wordCount:1040,methodology:`This bounded study examines ${t.focus} in a defined Philippines-based call center queue using a stated cohort, record-level review, and source-backed control principles. It separates observed facts, analysis, and the authorized decision; no industry statistic is treated as proof about one provider.`,limitations:'The findings apply only to the stated queue, channel, request mix, language, systems, period, and review method. They cannot establish a universal benchmark, future performance, legal sufficiency, or causation. Missing or stale records can change the interpretation; qualified owners review high-risk questions.',keyTakeaways:[t.finding,'Test ordinary and boundary cases with a named decision owner.','Keep minimum necessary customer context and uncertainty visible.'],stats:[{value:'4',label:'evidence cohorts',note:'Separate routine, exception, handoff, and recovery work.',source:1},{value:'1',label:'decision owner',note:'Every pattern needs an accountable next decision.',source:2},{value:'0',label:'unsupported promises',note:'A bounded study is not a provider guarantee.',source:3}],sections:t.heads.map((heading,j)=>({heading,paragraphs:[{text:t.p[j],citations:[1,2,3]},{text:t.p[(j+1)%t.p.length],citations:[2,4,5]}]})),table:{caption:`Evidence-to-decision table for ${t.focus}`,headers:['Evidence','Supports','Does not prove','Buyer check'],rows:[['Defined record','Comparable observation','Complete context','Audit a sample'],['Boundary case','Role and control test','Future performance','Name the owner'],['Outcome trend','Bounded signal','Root cause','Retest one change']]},buyerChecklist:['Define queue, channel, period, and cohort.','Read source records beside the metric.','Separate representative action from client decision.','Minimize personal information and record access.','Document limitations and retest after one change.'],faqs:[{q:`What does this ${t.focus} study establish?`,a:'Only the bounded evidence question for the stated queue and period; it does not establish a universal benchmark or provider result.'},{q:'What should happen when evidence is missing?',a:'Keep the gap visible, narrow the promise, assign an owner, or test the missing condition.'},{q:'Who makes restricted decisions?',a:'The authorized client, manager, or specialist owner; representatives document, explain approved next steps, and escalate uncertainty.'}],related,sources}));
