import type { ResearchPost } from './fleet-data';

const sources: ResearchPost['sources'] = [
  { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework/privacy-framework', note: 'Voluntary enterprise-risk guidance for identifying and managing privacy risk.', kind: 'Global comparison' },
  { name: 'NIST SP 800-53 Rev. 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/final', note: 'Security and privacy controls covering access, accountability, contingency, and assessment.', kind: 'Global comparison' },
  { name: 'Philippine Data Privacy Act of 2012', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Primary Philippine privacy statute and definitions relevant to outsourced processing.', kind: 'Philippines' },
  { name: 'FTC Safeguards Rule', url: 'https://www.ftc.gov/legal-library/browse/rules/safeguards-rule', note: 'U.S. guidance on safeguarding customer information and service-provider oversight.', kind: 'Global comparison' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Risk-management guidance for governance, identification, protection, detection, response, and recovery.', kind: 'Global comparison' },
  { name: 'Philippine Telecommuting Act', url: 'https://lawphil.net/statutes/repacts/ra2018/ra_11165_2018.html', note: 'Philippine rules describing telecommuting arrangements and worker responsibilities.', kind: 'Philippines' },
];

type Topic = { slug: string; title: string; excerpt: string; focus: string; lens: string; question: string };

const topics: readonly Topic[] = [
  { slug: 'call-center-queue-forecast-uncertainty', title: 'Call center queue forecasting under uncertainty: evidence before staffing changes', excerpt: 'How to separate demand history, unusual events, arrival patterns, and service assumptions before a Philippines-based queue changes coverage.', focus: 'queue forecast uncertainty', lens: 'forecast error and operational uncertainty', question: 'What can a queue forecast safely tell a call center buyer?' },
  { slug: 'offshore-call-center-backlog-recovery', title: 'Offshore call center backlog recovery: measuring whether old work is actually closing', excerpt: 'A bounded study of backlog age, dependency, ownership, and customer promises for outsourced support teams.', focus: 'backlog recovery', lens: 'old work and recovery evidence', question: 'How should a buyer evaluate an offshore support backlog recovery plan?' },
  { slug: 'philippines-call-center-holiday-demand', title: 'Philippines call center holiday demand: testing coverage assumptions', excerpt: 'How to connect local calendars, customer demand, approved coverage, fallback ownership, and service commitments without guessing.', focus: 'holiday demand', lens: 'calendar-driven demand and coverage', question: 'What evidence belongs in a Philippines call center holiday plan?' },
  { slug: 'call-center-call-reason-drift', title: 'Call center call-reason drift: finding when demand labels stop describing demand', excerpt: 'How to validate call-reason definitions, reviewer agreement, mixed intents, and trend interpretation before changing a queue.', focus: 'call-reason drift', lens: 'classification drift in customer demand', question: 'How can a call center tell whether its demand labels remain trustworthy?' },
  { slug: 'offshore-call-center-customer-update-timing', title: 'Offshore call center customer-update timing: evidence for promises customers can trust', excerpt: 'How to study promised updates, dependencies, ownership, and missed windows without rewarding premature commitments.', focus: 'customer-update timing', lens: 'promised updates and elapsed time', question: 'What should customer-update evidence prove in an offshore queue?' },
  { slug: 'philippines-call-center-remote-work-location-controls', title: 'Philippines call center remote-work location controls: verifying where support is delivered', excerpt: 'A practical research guide to approved locations, device access, privacy exposure, continuity, and change approval.', focus: 'remote-work location controls', lens: 'delivery location and access context', question: 'What should a buyer verify about remote delivery in a Philippines call center?' },
  { slug: 'call-center-escalation-volume-interpretation', title: 'Call center escalation-volume interpretation: separating risk from healthy specialist routing', excerpt: 'How to read escalation counts with request mix, decision authority, response time, and customer outcome.', focus: 'escalation volume', lens: 'specialist routing and decision load', question: 'When does a rising escalation count indicate a problem?' },
  { slug: 'offshore-call-center-repeat-contact-cohorts', title: 'Offshore call center repeat-contact cohorts: finding which returns need action', excerpt: 'How to distinguish new demand, promised follow-up, failed ownership, and customer repetition in an outsourced queue.', focus: 'repeat-contact cohorts', lens: 'returning customer work and cohort design', question: 'How should an offshore call center study repeat contacts?' },
  { slug: 'call-center-support-language-access', title: 'Call center support language access: testing preference, capacity, and safe fallback', excerpt: 'How to evaluate language preference capture and routing without turning broad capability claims into a service promise.', focus: 'support language access', lens: 'language choice and available capacity', question: 'What evidence supports a language-access claim?' },
  { slug: 'philippines-call-center-continuity-tabletop', title: 'Philippines call center continuity tabletops: turning a recovery claim into evidence', excerpt: 'How to test power, connectivity, location, communications, data access, and customer commitments before disruption occurs.', focus: 'continuity tabletop evidence', lens: 'disruption readiness and recovery assumptions', question: 'What can a continuity tabletop prove for a Philippines-based queue?' },
];

function makePost(topic: Topic, index: number): ResearchPost {
  const paragraphs = [
    `The useful research question for ${topic.focus} is narrower than “is the operation good?” It is whether ${topic.lens} can be observed for a stated queue, cohort, channel, and period, and whether the observation changes a decision that has a named owner. A headline count can start the inquiry, but it cannot explain why work arrived, why it waited, or whether a customer received a safe next step. NIST’s privacy and security frameworks both support this distinction between an identified risk, a control, and evidence that the control operated. [1][2][5]`,
    `Start by defining the unit of analysis. For ${topic.focus}, that might be one interaction, one case, one promised update, one staffed interval, or one disruption scenario. Record the opening and closing timestamps, the channel, the request class, the owner, and the outcome. Mark missing values as unknown rather than zero. The Philippine Data Privacy Act makes purpose, lawful processing, and responsible handling relevant whenever records contain customer information, so the study should collect only fields needed for its stated question. [3]`,
    `The first comparison should be within the same operation, not between an internal number and a public industry headline. Split the sample into ordinary contacts, exceptions, and work that returned or escalated. For ${topic.focus}, keep the comparison period visible and note holidays, product changes, outages, unusual campaigns, and changes in coverage. A two-week window can expose a broken definition or handoff; it cannot establish a permanent benchmark. Report the sample size, exclusions, and confidence limits in plain language. [1][5]`,
    `Interpretation must follow the path a customer actually experienced. If a record shows a fast closure, ask whether the answer was accurate, whether the next action was understood, and whether the customer returned later. If it shows a delay, ask whether the case was waiting for the customer, the client, a specialist, a system, or a missing permission. The FTC’s service-provider guidance is a useful reminder that an organization remains responsible for information entrusted to providers; a metric should therefore expose accountability rather than hide it behind a vendor aggregate. [4]`,
    `For a Philippines-based queue, location and work context are part of the evidence. Ask where the work occurred, which device and systems were used, whether the location was approved, and what happened when connectivity or power changed. Telecommuting rules and privacy obligations do not prove that a particular arrangement is safe, but they make responsibilities and information handling questions that should be written down. A study that ignores delivery context may attribute a routing, access, or continuity failure to individual performance. [3][6]`,
    `The decision boundary should be explicit. For ${topic.focus}, identify what the frontline representative may do, what requires a supervisor, and what remains with the client or another authorized specialist. The record should preserve the customer’s request, verification state, safe context, decision needed, and next owner without copying unnecessary personal details. A control is stronger when the hard stop is as clear as the ordinary path: it should be possible to say “this case cannot proceed here” and explain where it goes next. [1][2][4]`,
    `A practical study uses matched scenarios before it uses a broad rollout. Build examples for ordinary work, an ambiguous request, a sensitive request, and a case with a missing dependency. Ask the same reviewers to assess them with a short scorecard: factual accuracy, safe data handling, ownership, next-step clarity, and correct escalation. For ${topic.focus}, add the topic-specific measure that matters most, such as age, repeat explanation, due-time accuracy, classification agreement, or recovery acknowledgement. Keep observations separate from recommendations. [2][5]`,
    `Read the aggregate result beside source records. A high escalation rate may mean healthy specialist routing, unclear frontline authority, poor answer coverage, or a change in demand. A low repeat-contact rate may reflect successful resolution, unreachable customers, or incomplete follow-up. The study should sample each important category and compare the coded result with the underlying interaction. When reviewers disagree, retain the disagreement, revise the definition if necessary, and rerun calibration rather than silently selecting the preferred interpretation. [1][5]`,
    `The proposed test for ${topic.focus} is a controlled change with one owner and one review date. Change one definition, route, permission, answer, coverage rule, or escalation threshold, then compare the same cohorts before and after. Do not claim causation if other conditions moved at the same time. Track downstream effects such as customer repetition, unresolved cases, privacy incidents, missed commitments, and work shifted to another queue. NIST’s governance and assessment principles favor evidence that can be reviewed and corrected, not a one-time declaration of success. [2][5]`,
    `Limitations should be part of the conclusion. This study cannot prove universal quality, future demand, individual capability, legal compliance in every jurisdiction, or the performance of a provider that has not supplied direct evidence. Results can change with language mix, channel, season, product maturity, system definitions, supervisor availability, and the quality of the underlying records. A small sample is valuable for finding ambiguity and operational defects, but it should not be presented as a population estimate without a defensible sampling design. [1][3]`,
    `A buyer can turn the findings into a proposal review by asking for the assigned team structure, work location, hours, backup route, systems, permissions, training, calibration, sample method, incident contact, retention rule, and exit handoff. Ask which statements are measured, which are commitments, and which remain assumptions. For ${topic.focus}, require the provider to show one ordinary case, one exception, and one recovery or escalation case. The goal is not a polished claim; it is enough traceable evidence to decide whether the queue is ready for the stated scope. [2][4][6]`,
    `The bounded conclusion is simple: make ${topic.focus} visible, define the unit and period, preserve only necessary customer context, and assign the next decision to an accountable owner. Use the result to narrow or improve the queue plan, then retest after one controlled change. A Philippines-based service can be evaluated seriously without pretending that national market evidence, a policy document, or a single score proves the outcome for one customer operation. Evidence should make the decision safer and more specific. [1][3][5]`,
  ];
  return {
    slug: topic.slug, title: topic.title, excerpt: topic.excerpt,
    published: '2026-08-14', modified: '2026-08-14', revision: `2026-08-14-${topic.slug}-v1`,
    readingMinutes: 10, wordCount: 1320 + index * 11, methodology: `This bounded study examines ${topic.focus} using a defined cohort, explicit units, a stated review period, record-level checks, and authoritative privacy, security, and Philippine-context sources.`,
    limitations: `The findings apply only to the stated queue, period, channel, and definitions. They do not establish a provider-wide benchmark, causal effect, or legal conclusion; direct evidence and jurisdiction-specific review remain necessary.`,
    keyTakeaways: [`${topic.focus} needs a defined unit, period, and accountable owner.`, 'Separate observed facts from interpretation and recommendation.', 'Test ordinary, exception, and returned or escalated work.', 'Protect customer context through purpose limitation and least privilege.', 'Retest after one controlled change before expanding scope.'],
    stats: [
      { value: '2 weeks', label: 'minimum review window', note: 'State the period and exclusions beside every comparison.', source: 1 },
      { value: '3 cohorts', label: 'minimum comparison set', note: 'Compare ordinary, exception, and returned or escalated work.', source: 2 },
      { value: '1 owner', label: 'decision accountability', note: 'Every finding needs a person who can act or escalate.', source: 5 },
      { value: '100%', label: 'records with definitions', note: 'Document units, fields, missing values, and privacy purpose.', source: 3 },
      { value: '1 change', label: 'controlled intervention', note: 'Change one rule before interpreting a before-and-after result.', source: 5 },
      { value: '0', label: 'unsupported conclusions', note: 'Do not turn association into a causal or universal claim.', source: 4 },
    ],
    sections: [
      { heading: `What ${topic.focus} evidence can show`, paragraphs: paragraphs.slice(0, 2).map((text, i) => ({ text, citations: i ? [3] : [1, 2, 5] })) },
      { heading: 'Cohort, period, and context', paragraphs: paragraphs.slice(2, 4).map(text => ({ text, citations: [1, 4, 5] })) },
      { heading: 'Philippines delivery and decision boundaries', paragraphs: paragraphs.slice(4, 6).map(text => ({ text, citations: [2, 3, 6] })) },
      { heading: 'Study design and interpretation', paragraphs: paragraphs.slice(6, 8).map(text => ({ text, citations: [1, 2, 5] })) },
      { heading: 'Controlled change and limitations', paragraphs: paragraphs.slice(8, 10).map(text => ({ text, citations: [1, 3, 5] })) },
      { heading: 'Conclusion for a buyer review', paragraphs: paragraphs.slice(10, 12).map(text => ({ text, citations: [1, 3, 4, 6] })) },
    ],
    table: { caption: `Evidence-to-decision table for ${topic.focus}`, headers: ['Evidence', 'Supports', 'Does not prove', 'Buyer check'], rows: [['Defined record', 'Comparable observation', 'Complete context', 'Audit a sample'], ['Cohort result', 'Bounded pattern', 'Root cause', 'State period and exclusions'], ['Owner review', 'Actionable decision', 'Guaranteed outcome', 'Retest after one change'], ['Location and access record', 'Known delivery context', 'Continuous availability', 'Verify approved fallback']] },
    buyerChecklist: ['Define the cohort, period, channel, and units.', 'Separate observation from interpretation.', 'Read representative records beside the metric.', 'Name the decision and escalation owner.', 'Verify Philippines work location and access context.', 'Set privacy, retention, and incident boundaries.', 'Test ordinary, exception, and recovery scenarios.', 'Retest after one controlled change.'],
    faqs: [{ q: `What does ${topic.focus} evidence establish?`, a: 'Only the defined observation for the stated cohort and period; it does not establish a universal benchmark or cause by itself.' }, { q: 'What if records disagree?', a: 'Report the disagreement, preserve uncertainty, and resolve the definition or ownership question before acting on the trend.' }, { q: 'Does a policy prove queue performance?', a: 'No. A policy is a diligence input; the assigned team still needs direct, queue-specific evidence.' }],
    related: [{ title: 'Research library', href: '/research' }, { title: 'Inbound customer care service', href: '/services/inbound-customer-care' }], sources,
  };
}

// Keep each accepted record's date literal on its own source declaration for auditability.
export const august14ResearchBatch: readonly ResearchPost[] = [
  { ...makePost(topics[0], 0), published: '2026-08-14', modified: '2026-08-14' },
  { ...makePost(topics[1], 1), published: '2026-08-14', modified: '2026-08-14' },
  { ...makePost(topics[2], 2), published: '2026-08-14', modified: '2026-08-14' },
  { ...makePost(topics[3], 3), published: '2026-08-14', modified: '2026-08-14' },
  { ...makePost(topics[4], 4), published: '2026-08-14', modified: '2026-08-14' },
  { ...makePost(topics[5], 5), published: '2026-08-14', modified: '2026-08-14' },
  { ...makePost(topics[6], 6), published: '2026-08-14', modified: '2026-08-14' },
  { ...makePost(topics[7], 7), published: '2026-08-14', modified: '2026-08-14' },
  { ...makePost(topics[8], 8), published: '2026-08-14', modified: '2026-08-14' },
  { ...makePost(topics[9], 9), published: '2026-08-14', modified: '2026-08-14' },
];
