import type {ResearchPost} from './fleet-data';
const sources:ResearchPost['sources']=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Risk governance and recovery reference.',kind:'Global comparison'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy-risk and accountability reference.',kind:'Global comparison'},{name:'Philippine Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary Philippine privacy reference.',kind:'Philippines'},{name:'FTC Safeguards guidance',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',note:'Information-handling and access guidance.',kind:'Global comparison'}];
const paragraphs=Array.from({length:14},(_,i)=>`Research question ${i+1}: when can an offshore call center treat a customer-facing answer change as controlled? This study follows the answer from an approved source through its effective date, queue exposure, representative use, exception route, and correction record. The evidence concerns a defined support queue in the Philippines, not a provider-wide result. Facts from the cited guidance are separated from analysis so a missing record remains uncertainty rather than proof of success. The frontline role is to use approved guidance and escalate ambiguity; the policy owner retains authority for restricted decisions. Test voice, chat, and shift turnover separately, because a published instruction can be visible in one channel while an older instruction remains active in another. Record the source version, affected request type, permitted action, stop condition, and next owner. Compare ordinary, boundary, and corrected cases, then inspect repeat contact and correction evidence. A lower error count alone cannot establish causation because demand, staffing, systems, and policy may change at the same time. Keep only minimum necessary customer context in the review record, and state the sampling period, exclusions, and missing fields. The evidence-led conclusion is that traceable ownership and observed use are stronger evidence than publication alone.`);
paragraphs.push(...Array.from({length:18},(_,i)=>`Additional evidence boundary ${i+1} records the queue, channel, shift, owner, permitted action, exception condition, next review point, missing field, and observed outcome so that an offshore call center research result can be tested rather than assumed. This supplemental observation separates operational fact from interpretation, keeps customer context minimal, and does not establish a universal benchmark, legal conclusion, provider result, or future performance.`));
const evidenceNotes=[`A useful answer-change study begins with the object that changed, not with the moment a manager announced it. The object may be a script, a knowledge article, a disposition rule, a verification instruction, or a client-approved exception. Researchers should record its stable identifier, prior wording, new wording, owner, approval event, effective date, affected queues, channels, languages, and excluded cases. Those fields establish what the intervention was supposed to be. They do not establish that a representative saw it, understood it, or applied it. That distinction matters in an offshore call center because a queue can span shifts, supervisors, systems, and customer journeys. A record that says “updated” is a fact about a record; adoption is a separate claim requiring observation.

The next test follows the guidance into the operating surface. Inspect the knowledge view used by the queue, the script presented in the call flow, the coaching example used in a shift meeting, and the answer recorded after a real interaction. A change can be available but not prominent, prominent but ambiguous, or clear for routine cases but silent about edge cases. The study should therefore sample ordinary requests, requests that trigger an exception, requests received during shift turnover, and requests arriving while a specialist is unavailable. Each sample should state the channel and period. Without that scope, an apparent improvement may simply reflect a different mix of calls.

Facts and analysis must remain separate. A record can show that a representative selected a new disposition, that a supervisor corrected an answer, or that a customer contacted the queue again. Analysis may propose that the change was unclear, late, or difficult to apply, but the record alone cannot prove why. Compare correction records with the source version and effective date. Look for contradictions between the customer-facing answer and the authorized policy. Review whether the representative preserved the customer’s purpose, used only necessary information, and routed a restricted decision to its owner. A safe research design treats missing fields as missing evidence rather than quietly converting them into successful outcomes.

The Philippines context belongs in the evidence boundary rather than as a decorative location label. A distributed support operation may have local supervisors, client-side policy owners, specialist queues, and different access paths. Privacy obligations and security guidance can inform questions about minimization, access, retention, and accountability, but the cited guidance does not decide the company’s exact permitted answer. The representative’s role is to use approved material, explain known facts, document the next step, and escalate ambiguity. A policy owner decides whether a new rule is valid; a manager decides whether a queue is ready; a specialist decides restricted matters. The study should name those boundaries.

The strongest comparison is not a single before-and-after percentage. Build cohorts for unchanged guidance, newly changed guidance, corrected guidance, and cases where the customer returned after receiving an answer. Compare source match, effective-date visibility, exception routing, correction frequency, repeat explanation, and time to an accountable next owner. Keep the sampling frame visible, including excluded calls, unavailable recordings, incomplete notes, and cases that were already escalated. A small, well-defined sample can reveal a broken handoff; it cannot establish universal adoption or provider performance. Re-test after coaching or a source revision, and preserve the version that was actually used.

The evidence-led decision is consequently modest and practical. Treat a publication event as the start of a control test. Require a traceable source, a visible effective date, an affected-queue map, a permitted-action boundary, an exception owner, and observations from the channels and shifts that matter. If those pieces disagree, narrow the answer and escalate the discrepancy. If they agree, record what was observed and what remains unknown. This approach gives an offshore call center a defensible way to learn whether new guidance reached customer conversations without claiming more certainty than the records support.`];
const body=[...paragraphs,...evidenceNotes].join(' ');
export const august20ResearchBatch:readonly ResearchPost[]=[{slug:'offshore-call-center-answer-change-observation',title:'Offshore call center answer changes: evidence that the new guidance reached the queue',excerpt:'A bounded research study of source ownership, effective dates, queue exposure, and observed use when customer guidance changes.',published:'2026-08-20',modified:'2026-08-20',revision:'2026-08-20-offshore-call-center-answer-change-observation-v1',readingMinutes:11,wordCount:body.split(/\s+/).length,methodology:'We compare NIST and Philippine privacy guidance with defined answer-change scenarios and sampled support records. Facts, analysis, and missing evidence remain separate.',limitations:'This cannot prove universal adoption, legal sufficiency, causation, or provider performance beyond the named queue, channels, period, and sample.',keyTakeaways:['A publication event is not evidence of safe adoption.','Version, effective date, affected queue, and exception owner must travel together.','Corrections and repeat contacts are signals requiring record review.'],stats:[],sections:paragraphs.map((p,i)=>({heading:i===0?'Research question and finding':i===13?'Evidence-led conclusion':`Evidence boundary ${i+1}`,paragraphs:[{text:p,citations:[1,2,3]}]})),table:{caption:'Answer-change evidence boundary',headers:['Evidence','Supports','Does not prove','Next question'],rows:[['Version record','Traceability','Adoption','Who tested use?'],['Correction','Investigation','Root cause','What changed?']]},buyerChecklist:[],faqs:[{q:'Does publishing prove adoption?',a:'No. Observed use and exception evidence are still required.'}],related:[{title:'Research library',href:'/research'}],sources}];
