import type {ResearchPost} from './fleet-data';

const sources: ResearchPost['sources'] = [
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance, accountability, protection, detection, response, and recovery concepts.',kind:'Global comparison'},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy-risk concepts for purpose, access, communication, and data minimization.',kind:'Global comparison'},
  {name:'Philippine Data Privacy Act, Republic Act No. 10173',url:'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html',note:'Primary Philippine statutory text concerning personal-information processing.',kind:'Philippines'},
  {name:'National Privacy Commission Philippines',url:'https://privacy.gov.ph/',note:'Philippine regulator resources for organizational accountability and privacy questions.',kind:'Philippines'},
  {name:'ILO Working from home guide',url:'https://www.ilo.org/publications/working-home-guide',note:'Distributed-work organization, safety, communication, and continuity context.',kind:'Global comparison'},
];

const makePost = (slug:string,title:string,excerpt:string,question:string,unit:string,fields:string,comparison:string,decision:string,conclusion:string,takeaways:string[]):ResearchPost => {
  const sections = [
    {heading:'Research question and September 2 evidence boundary',text:`This route-specific research record is dated September 2, 2026. ${question} The unit of analysis is ${unit}. We compare simulated routine, ambiguous, transferred, and exception records with public governance, privacy, and distributed-work sources. The method separates observed fields from operational interpretation and decisions reserved to an authorized owner. It uses no private customer records and makes no provider-wide performance claim.`},
    {heading:'Observable record and reconstruction test',text:`A reviewable record preserves ${fields}. Reviewers should be able to reconstruct the event in sequence, including what initiated it, what the representative knew, what action was permitted, what remained unresolved, and who accepted the next step. A timestamp without an owner proves activity but not accountability. Missing evidence should remain missing rather than being converted into a favorable status or assumed outcome.`},
    {heading:'Cohort comparison and counterexamples',text:`The bounded comparison is ${comparison}. Stratify the records by channel, shift, request type, source version, and need for client-side approval. Read examples behind each category because an average can hide different mechanisms. A cautious privacy stop is not equivalent to abandoned work, and rapid closure does not prove that the customer received an accurate answer. Differences identify a test question; they do not establish causation.`},
    {heading:'Privacy, access, and decision authority',text:`Use only the customer context necessary to examine the operating event. Restrict source-record access to authorized reviewers and avoid copying unrelated personal information into calibration notes. Philippine Data Privacy Act and National Privacy Commission materials are comparison sources, not legal conclusions for a specific organization. Sensitive disclosure, remedy, account, retention, access, and policy exceptions remain with the designated client, privacy, security, or legal owner.`},
    {heading:'Decision use and controlled retest',text:`The study supports this bounded decision: ${decision}. Select one repair, preserve the definitions and sample frame, and repeat the comparison after the change. Document exclusions, uncertainty, and counterexamples. A manager should be able to state which observation triggered the action, who owns it, when it will be reviewed, and which result would pause expansion. This connects research to an operating decision without turning description into a guarantee.`},
    {heading:'Limitations and evidence-led conclusion',text:`This scenario study cannot prove legal compliance, customer satisfaction, workforce capacity, financial impact, causation, or provider-wide quality. Results depend on the chosen period, queues, channels, definitions, and record completeness. The defensible conclusion is narrow: ${conclusion} Buyers should validate it with their own authorized owners and records, then retest after any material instruction, access, staffing, routing, or system change.`},
  ];
  return {slug,title,excerpt,hero:'/offshore-call-center-agent.jpg',published:'2026-09-02',modified:'2026-09-02',revision:`2026-09-02-${slug}-v1`,readingMinutes:8,wordCount:sections.map(s=>s.text).join(' ').split(/\s+/).length,methodology:`A bounded scenario-record comparison using ${unit} as the unit of analysis and five named public governance, privacy, and work-organization sources.`,limitations:'Scenario evidence and public frameworks cannot prove legal compliance, causation, satisfaction, provider-wide quality, capacity, or financial impact.',keyTakeaways:takeaways,stats:[],sections:sections.map((s,i)=>({heading:s.heading,paragraphs:[{text:s.text,citations:i%2===0?[1,3,5]:[2,4]}]})),table:{caption:'Evidence-to-decision boundary',headers:['Observed evidence','Supports','Does not prove','Next test'],rows:[[fields.split(',')[0],'Traceable event','Successful outcome','Review one exception'],['Named owner and time','Sequence and accountability','Adequate capacity','Compare matched cohorts'],['Recorded authority boundary','Permitted next step','Legal compliance','Validate with the client owner']]},buyerChecklist:['Define the event and accountable owner.','Preserve source, status, time, dependency, and next action.','Sample routine, ambiguous, transferred, and exception records.','Record exclusions, missing evidence, and uncertainty.','Change one control and repeat the comparison.'],faqs:[{q:`What does this report establish about ${title.toLowerCase()}?`,a:'It establishes a bounded evidence design and decision questions, not a universal benchmark, legal conclusion, or provider guarantee.'},{q:'Who owns actions outside the documented workflow?',a:'The authorized client or specialist owner retains those decisions.'}],related:[{title:'Research library',href:'/research'},{title:'Call quality monitoring',href:'/services/call-quality-monitoring'}],sources};
};

export const september2ResearchBatch: readonly ResearchPost[] = [
  makePost('offshore-call-center-queue-reassignment-research','Offshore call center queue reassignment: when does ownership actually change?','A bounded comparison of customer work waiting on client decisions, third parties, systems, and customer responses.','Which record evidence distinguishes justified waiting from an aging dependency with no accepted next action?','one unresolved case from the first blocked action through the next owner response','dependency category, source, blocked time, due point, customer update, current owner, acceptance state, and resolution evidence','customer-, client-, third-party-, and system-dependent cases, separated by accepted ownership and kept update promise','whether a dependency register, acknowledgement rule, or earlier customer-update trigger should be piloted','Dependency age becomes actionable only when the blocker, promise, and accepted owner remain visible.',['Waiting is not one outcome; the dependency and owner must be explicit.','A customer update promise differs from a resolution estimate.','Age bands should trigger a named decision.']),
  makePost('philippines-call-center-weather-continuity-research','Philippines call center weather continuity: which controls protect customer queues?','Research on the overlap between Philippines queue hours and client-side availability for restricted decisions.','How does the alignment of offshore coverage and client weather disruption windows affect accepted escalations and customer updates?','one restricted request from frontline stop to authorized decision','request category, Philippines shift, client time zone, sent time, available approval window, acceptance time, interim message, decision, and final update','requests arriving inside versus outside weather disruption windows, separated by urgency, queue, and available fallback owner','whether to change escalation hours, acknowledgement coverage, queue scope, or interim customer language','Approval-window alignment is observable through arrival, availability, acceptance, and customer-update evidence.',['Round-the-clock intake does not prove round-the-clock decision authority.','Time zones and available windows must be explicit.','Interim messages should not invent resolution times.']),
  makePost('call-center-repeat-contact-context-research','Call center repeat-contact context: which facts prevent another restart?','An evidence-led study of verified needs, completed checks, promises, authority boundaries, and receiving-owner acceptance.','Which required facts are most often lost or changed when customer work repeat contacts between call center owners?','one transferred interaction from sending decision to receiving-owner action','customer need, verification state, completed action, source version, unresolved question, promise, sent time, receiving owner, and acceptance result','same-channel versus cross-channel repeat contacts, same-shift versus cross-shift moves, and accepted versus returned work','whether the minimum handoff fields, receiving criteria, or acknowledgement method should change','Context loss is measurable only when required fields and receiving-owner use are defined before sampling.',['More notes do not necessarily create a better transfer.','Required context should be minimal, specific, and reconstructable.','Acceptance and return reasons reveal whether the record was usable.']),
  makePost('offshore-call-center-override-frequency-research','Offshore call center override frequency: exception signal or hidden operating rule?','A bounded review of supervisor changes to routes, priorities, statuses, scripts, and closure decisions.','When do repeated supervisor overrides indicate a valid exception pattern versus an outdated or incomplete operating rule?','one supervisor override from original rule through later review','original rule, override type, reason, authorized approver, customer impact, timestamp, affected queue, follow-up owner, and review outcome','one-time versus repeated overrides, grouped by rule, supervisor, shift, request type, and customer consequence','whether to retain the exception, revise the rule, improve access, or clarify the escalation route','Override counts become useful when each event links the original rule, authority, reason, and later decision.',['An override is neither automatically good nor automatically noncompliant.','Repeated reasons may reveal an outdated workflow.','Customer impact and authorization must remain traceable.']),
  makePost('call-center-recording-coverage-gap-research','Call center recording coverage gaps: what can a quality sample honestly claim?','Research on missing audio, failed capture, excluded channels, specialist repeat contacts, and substitute evidence limits.','How should a quality program measure and report interactions that could not enter an audio-based review?','one sample-eligible interaction and its recording-availability decision','queue, channel, shift, eligibility rule, selection result, recording state, failure reason, substitute evidence, reviewer action, and remediation owner','recorded versus unavailable interactions across queues, channels, shifts, exceptions, and transfer types','whether recording controls, sample rules, reviewer access, or the stated quality conclusion should be narrowed','A quality conclusion is bounded by the interactions that were eligible, available, selected, and actually reviewed.',['Missing recordings are coverage evidence, not neutral absences.','Substitute records cannot prove tone or spoken accuracy.','Availability gaps need reasons, owners, and trend review.']),
];
