import type {ResearchPost} from './fleet-data';

const sources:ResearchPost['sources']=[
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Primary NIST framework used to define governance, protection, detection, response, and recovery boundaries.',kind:'Global comparison'},
 {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Primary NIST framework used to frame privacy risk and data processing decisions.',kind:'Global comparison'},
 {name:'Republic Act No. 10173, Data Privacy Act of 2012',url:'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html',note:'Official Philippine statutory text used for operational context, not a legal conclusion.',kind:'Philippines'},
 {name:'National Privacy Commission Philippines',url:'https://privacy.gov.ph/',note:'Official regulator guidance used to identify accountability and protection considerations.',kind:'Philippines'},
 {name:'ISO 18295-1:2017 overview',url:'https://www.iso.org/standard/64739.html',note:'Official ISO overview of customer contact centre requirements used as a standards comparison.',kind:'Global comparison'},
];
type Study={slug:string;title:string;excerpt:string;question:string;unit:string;evidence:string;comparison:string;proposition:string;pilot:string;limitations:string;takeaways:readonly string[]};
const make=(s:Study):ResearchPost=>{
 const sections=[
  {heading:'Research question and scope',text:`${s.question} The unit of analysis is ${s.unit}. This September 10, 2026 report defines a bounded record review for a Philippines-based contact center. It does not benchmark providers, establish causation, or offer legal advice.`,citations:[3,4,5]},
  {heading:'Methodology',text:`Set the queue, review period, eligibility rule, and exclusion rule before sampling. Preserve ${s.evidence}. Draw a time-bounded sample, retain excluded records in a log, and ask a second reviewer to classify ambiguous cases without seeing the first label.`,citations:[1,2,5]},
  {heading:'Comparison and analysis',text:`Compare ${s.comparison}. Keep request type, channel, shift, system availability, customer promise, and authority requirement visible. Report numerators, denominators, missing fields, and counterexamples rather than converting the sample into a provider-wide score.`,citations:[1,5]},
  {heading:'Inference boundaries',text:`The testable operational proposition is that ${s.proposition} The records can show observed events and associations inside the selected sample. They cannot show customer intent, unrecorded conversations, legal compliance, employee motivation, or effects outside the defined period.`,citations:[1,2,3,4]},
  {heading:'Pilot and decision rule',text:`Test the proposition by ${s.pilot}. Define the success measure and stop rule before the pilot. Change one control, preserve contrary cases, and compare the next eligible sample with the baseline using the same definitions.`,citations:[1,5]},
  {heading:'Limitations',text:`${s.limitations} Selection bias, incomplete records, reviewer disagreement, and changing queue conditions may alter the result. A larger count does not repair a poorly defined unit or missing source evidence.`,citations:[1,2,5]},
 ];
 const words=sections.map(x=>x.text).join(' ').split(/\s+/).length;
 return {slug:s.slug,title:s.title,excerpt:s.excerpt,hero:'/offshore-call-center-agent.jpg',published:'2026-09-10',modified:'2026-09-10',revision:`2026-09-10-${s.slug}-v1`,readingMinutes:9,wordCount:words,methodology:`A bounded source-record review of ${s.unit}, with eligibility rules set before sampling, retained exclusions, explicit comparison groups, and independent review of ambiguous cases.`,limitations:s.limitations,keyTakeaways:s.takeaways,stats:[],sections:sections.map(x=>({heading:x.heading,paragraphs:[{text:x.text,citations:x.citations}]})),table:{caption:'Evidence and interpretation boundary',headers:['Evidence','Can support','Cannot prove','Review step'],rows:[[s.evidence.split(',')[0],'An observed event','A correct outcome','Read the source record'],['Accepted owner','Recorded responsibility','Adequate staffing','Trace the acknowledgement'],['Recorded result','A bounded status','Customer intent','Check contrary cases']]},buyerChecklist:['Define the unit, queue, period, and exclusions.','Preserve source events and missing fields.','Separate observed facts from reviewer labels.','Review ambiguous and contrary cases independently.','Pilot one control with a pre-set decision rule.'],faqs:[{q:'What does this report establish?',a:'It provides a bounded review method and a testable operational proposition. It does not establish a universal benchmark, causal effect, or legal conclusion.'},{q:'How should a buyer use the result?',a:'Use it to decide whether one narrowly defined workflow control merits a pilot, then repeat the same measurement before expanding the change.'}],related:[{title:'Research library',href:'/research'},{title:'Call quality monitoring',href:'/services/call-quality-monitoring'}],sources};
};

export const september10ResearchBatch:readonly ResearchPost[]=[
 make({slug:'call-center-silent-call-recovery-study',title:'Silent-call recovery in contact centers: an event-trace study',excerpt:'A bounded method for testing connection checks, privacy stops, callback choices, and ownership after audio disappears.',question:'Which recovery steps are associated with a safe and usable outcome after a live call loses audio?',unit:'one connected customer call with a recorded interval of one-way or two-way silence',evidence:'audio event time, agent check-in, phone control state, verification state, disclosure after silence, disconnect time, callback permission, callback attempt, case note, and final owner',comparison:'one-way and two-way failures, recovered and disconnected calls, verified and unverified contacts, permitted and prohibited callbacks, and cases with or without accepted ownership',proposition:'a timed check-in, a stop on private disclosure, and an owned callback rule produce a clearer recovery record than silence followed by an unexplained disconnect.',pilot:'adding a three-field silent-call disposition to one queue and comparing missing recovery evidence, unsafe continuation, callback completion, and repeat contact across two periods',limitations:'Audio telemetry may not reveal what either person heard, and recordings may omit phone-control state or local equipment faults.',takeaways:['Treat lost audio as an uncertain connection state.','Stop private disclosure until the caller can respond.','Trace any callback to a named owner.']}),
 make({slug:'offshore-call-center-supervisor-approval-trace-study',title:'Supervisor approval traces in offshore call centers: linking decisions to actions',excerpt:'A source-record design for examining approval authority, scope, conditions, action, and customer communication.',question:'Does the approval record let a reviewer connect an authorized decision to the exact action and customer update that followed?',unit:'one frontline request that requires documented supervisor or specialist approval',evidence:'requested action, policy or exception, requester, approver role, decision time, scope, conditions, action taken, case update, and customer communication',comparison:'approved, declined, conditional, pending, expired, and undocumented requests, plus actions inside or outside the recorded scope',proposition:'approval is traceable only when authority, scope, conditions, action, and customer communication remain connected in the system of record.',pilot:'requiring a structured approval receipt for one decision type and comparing unsupported actions, missing conditions, search time, and customer-update completion with the baseline',limitations:'Informal consultations may be absent, an approver title may not prove current authority, and the record cannot establish whether the customer understood the outcome.',takeaways:['Record the exact scope of approval.','Keep the decision in the case record.','Compare the approved action with what actually happened.']}),
 make({slug:'philippines-call-center-power-continuity-study',title:'Power continuity in Philippine call centers: measuring accepted work handoffs',excerpt:'A bounded review of interruption windows, safe status checks, access, accepted backup ownership, and customer promises.',question:'Which controls preserve customer work during a power interruption without treating unsafe availability as a performance requirement?',unit:'one active contact or time-bound customer promise due within a declared power-interruption window',evidence:'interruption start and end, staff status, safety constraint, system access, active contact state, promise due time, backup assignment, acceptance time, customer update, and outcome',comparison:'site and remote interruptions, planned and unplanned coverage, accepted and unaccepted handoffs, available and unavailable approved access, and promises met or missed',proposition:'safe status reporting and acknowledged backup ownership protect customer commitments better than measuring individual availability without infrastructure context.',pilot:'using a promise register and receiver acknowledgement during one bounded interruption exercise, then tracing customer updates, orphaned work, unsafe workarounds, and missed commitments',limitations:'Interruption severity varies by location, exercises may not reproduce real hazards, and workforce records should not be used to infer personal circumstances.',takeaways:['Put staff safety ahead of queue targets.','Require the backup owner to acknowledge work.','Measure promises and access, not attendance alone.']}),
 make({slug:'call-center-appointment-no-show-evidence-study',title:'Appointment no-show follow-up: separating customer absence from workflow failure',excerpt:'A method for testing reminders, time zones, provider availability, contact attempts, rescheduling, and unresolved decisions.',question:'Which recorded events distinguish a customer no-show from a reminder, scheduling, access, or provider-side failure?',unit:'one scheduled customer appointment recorded as missed or incomplete',evidence:'booking source, service, scheduled date and zone, reminder instruction, delivery result, customer preference, provider availability, join or arrival event, follow-up attempt, reschedule, and disposition',comparison:'customer and provider absence labels, delivered and failed reminders, correct and disputed time zones, accessible and inaccessible channels, and completed or unresolved follow-up',proposition:'a no-show label is usable only when the record preserves the appointment basis, reminder result, availability evidence, and follow-up outcome.',pilot:'adding a short evidence checklist before no-show closure and comparing disputed labels, successful rescheduling, missing reminders, provider-side failures, and unresolved cases',limitations:'Arrival telemetry may be incomplete, delivery does not prove a reminder was read, and the review cannot infer why a customer did not attend.',takeaways:['Treat the no-show label as a conclusion that needs evidence.','Check both customer and provider availability.','Keep unresolved fee or eligibility decisions with the authorized owner.']}),
 make({slug:'offshore-call-center-attachment-handling-study',title:'Attachment handling in offshore call centers: a minimum-evidence review',excerpt:'A bounded study of expected files, source checks, system warnings, approved storage, escalation, and customer response.',question:'Can an attachment rule reduce unsafe opening and copying while still routing expected customer evidence to the right owner?',unit:'one inbound customer message containing or linking to a file',evidence:'message source, expected-file indicator, case relationship, file type, system scan result, warning, open or block event, storage location, escalation, customer instruction, and final disposition',comparison:'expected and unexpected files, allowed and blocked types, clean and warned scans, approved and unapproved storage, escalated and locally resolved cases, and false alarms',proposition:'agents make more defensible attachment decisions when expectation, case relationship, system result, storage boundary, and escalation outcome are recorded separately.',pilot:'adding an expected-file flag and security disposition in one channel, then comparing unsafe downloads, unnecessary opens, unresolved blocks, false alarms, and time to an accepted owner',limitations:'A clean scan does not prove a file is safe, security tools change during a review, and case records may not capture copying outside approved systems.',takeaways:['Do not treat urgency as proof a file is expected.','Keep customer files in approved systems.','Preserve warnings and escalation outcomes for review.']}),
];
