import type {ResearchPost} from './fleet-data';

export type DecisionResearchTopic={slug:string;title:string;excerpt:string;question:string;decision:string;unit:string;fields:string;groups:string;control:string;failure:string;service:string;serviceHref:string;takeaways:readonly string[]};

const sources:ResearchPost['sources']=[
 {name:'NIST SP 800-63-4: Digital Identity Guidelines',url:'https://pages.nist.gov/800-63-4/sp800-63.html',note:'Official NIST digital-identity guidance, published July 2025; checked September 22, 2026. Used for risk-based identity, authentication, and recovery design. It is guidance for U.S. federal systems, not proof that a private workflow complies with any law.',kind:'Global comparison'},
 {name:'NIST SP 800-61 Rev. 3: Incident Response Recommendations and Considerations',url:'https://csrc.nist.gov/pubs/sp/800/61/r3/final',note:'Official NIST incident-response publication; checked September 22, 2026. Used for preparation, detection, response, recovery, and improvement concepts.',kind:'Global comparison'},
 {name:'FTC: Mail, Internet, or Telephone Order Merchandise Rule',url:'https://www.ftc.gov/legal-library/browse/rules/mail-internet-or-telephone-order-merchandise-rule',note:'Official Federal Trade Commission rule and compliance resources; checked September 22, 2026. Used to frame promised shipment, delay, cancellation, and refund evidence for covered U.S. orders. This report is not legal advice.',kind:'Global comparison'},
 {name:'HHS: Minimum Necessary Requirement',url:'https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/minimum-necessary-requirement/index.html',note:'Official U.S. Department of Health and Human Services HIPAA guidance; checked September 22, 2026. Used to frame role-based limits for covered workflows, without assuming every scheduling operation is subject to HIPAA.',kind:'Global comparison'},
 {name:'CFPB: Your company’s role in the complaint process',url:'https://www.consumerfinance.gov/compliance/consumer-complaint-program/company-process/',note:'Official Consumer Financial Protection Bureau description of company review and response steps; checked September 22, 2026. Used as a bounded comparison for complaint ownership, not as a universal complaint-handling standard.',kind:'Global comparison'},
 {name:'Republic Act No. 10173: Data Privacy Act of 2012',url:'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html',note:'Official Philippine statutory text; checked September 22, 2026. Used as Philippines privacy and accountability context, not legal advice.',kind:'Philippines'},
 {name:'National Privacy Commission: Data Privacy Act resources',url:'https://privacy.gov.ph/data-privacy-act/',note:'Official Philippine regulator resource; checked September 22, 2026. Used for accountability and personal-data handling context.',kind:'Philippines'},
 {name:'ISO 18295-1:2017 — Customer contact centres',url:'https://www.iso.org/standard/64739.html',note:'Official ISO standard overview; checked September 22, 2026. Used only as a contact-centre requirements comparison; the full standard was not reviewed for this report.',kind:'Global comparison'},
];

const topics:readonly DecisionResearchTopic[]=[
 {slug:'call-center-account-recovery-verification-study',title:'Account recovery in a call center: a verification-boundary study',excerpt:'A buyer-focused test for deciding what an offshore support agent may verify, what evidence is sufficient, and when recovery must stop or escalate.',question:'Can a Philippines-based support role help a legitimate customer recover access without turning the call center into a weaker authentication path?',decision:'whether to delegate a recovery step, restrict it to information gathering, or retain the action with an authorized client-side owner',unit:'one account-recovery request from the first identity claim through verification, action, notification, and post-event review',fields:'channel, claimed identity, account state, recovery trigger, evidence requested, evidence result, failed attempts, risk signal, permitted action, escalation owner, notification, and final outcome',groups:'successful and failed checks, ordinary and high-risk accounts, first and repeated attempts, available and unavailable authenticators, and completed and stopped recoveries',control:'a risk-tiered recovery matrix with non-overridable stops, separate approval for sensitive changes, attempt limits, customer notification, and reviewable event records',failure:'a helpful agent is allowed to replace stronger authentication with knowledge that an attacker can research or persuade the customer to reveal',service:'inbound customer care',serviceHref:'/services/inbound-customer-care',takeaways:['Treat recovery as an authentication path, not a courtesy script.','Define evidence, attempt limits, and hard stops before launch.','Keep sensitive resets with an authorized owner unless the tested role is explicitly approved.']},
 {slug:'technical-support-incident-escalation-evidence-study',title:'Technical support incident escalation: an evidence-completeness study',excerpt:'A practical method for testing whether tier-one support can recognize a possible security incident, contain its actions, and deliver a usable escalation record.',question:'Does a technical-help-desk workflow turn a suspicious customer report into a timely, bounded, and usable incident escalation?',decision:'whether tier-one support may continue troubleshooting, must stop, or should transfer the case to the client’s incident owner',unit:'one suspicious support contact from intake through classification, permitted diagnostic action, acknowledgement, transfer, and receiving-owner decision',fields:'report time, affected service, observed symptom, customer statement, account identifier, diagnostic step, prohibited action, severity cue, escalation time, receiving owner, acknowledgement, and disposition',groups:'known faults and possible incidents, complete and incomplete reports, acknowledged and unacknowledged transfers, normal and privileged accounts, and events inside and outside staffed incident coverage',control:'a short recognition guide, least-privilege diagnostic steps, a stop rule, a named incident route, receiver acknowledgement, and preservation of the original report',failure:'frontline troubleshooting continues after incident signals appear, changing evidence or delaying the team authorized to investigate and contain the event',service:'technical help desk support',serviceHref:'/services/technical-help-desk',takeaways:['Teach observable incident cues, not security diagnosis.','Stop unapproved changes when escalation criteria are met.','Measure receiver acknowledgement and evidence completeness.']},
 {slug:'ecommerce-delivery-promise-exception-study',title:'Ecommerce delivery promises: an exception-evidence study',excerpt:'A source-record method for testing how an offshore ecommerce team handles shipment promises, delay notices, cancellation requests, and refund handoffs.',question:'Can an ecommerce support role explain an order’s actual status and route a delivery exception without inventing a promise or exercising unapproved refund authority?',decision:'which status messages and coordination steps may be delegated and which cancellation, refund, or remedy decisions remain with the store owner',unit:'one customer order that is delayed, unavailable, disputed, or at risk of missing its stated shipment basis',fields:'order date, stated shipment basis, inventory state, carrier event, delay discovery, customer notice, customer choice, cancellation request, refund owner, action time, and final outcome',groups:'on-time and delayed orders, documented and missing shipment bases, customer-accepted and declined delays, fulfilled and cancelled orders, and routine and disputed outcomes',control:'a system-of-record view of the shipment basis, approved delay language, preserved customer choice, a named refund owner, and an exception queue with due times',failure:'agents repeat an optimistic estimate from a storefront or supplier even when the order record no longer supports that customer-facing promise',service:'ecommerce contact center support',serviceHref:'/services/ecommerce-contact-center',takeaways:['Answer from the current order record, not a generic estimate.','Preserve the promise, delay notice, and customer choice.','Separate status coordination from refund authority.']},
 {slug:'healthcare-scheduling-minimum-data-study',title:'Healthcare scheduling support: a minimum-data workflow study',excerpt:'A scoped test for deciding which patient details a Philippines-based scheduling role needs to view, record, repeat, and escalate.',question:'What is the smallest set of information a non-clinical scheduling role needs to complete an approved appointment task safely?',decision:'whether each data field and system permission is necessary for the scheduling step or should stay hidden, optional, or with authorized clinical staff',unit:'one appointment request from identity check through slot selection, confirmation, reminder, change, cancellation, or clinical escalation',fields:'request channel, identity check, appointment type, required field, field purpose, system view, note location, disclosure recipient, urgent language, escalation owner, and scheduling outcome',groups:'new and existing patients, routine and urgent language, required and optional fields, completed and escalated requests, and permitted and denied system views',control:'a task-to-data matrix, role-based screen access, approved neutral language, a clinical hard stop, secure notes, and periodic review of fields actually used',failure:'a scheduling script collects or repeats sensitive information because a broad template asks for it, even though the scheduling decision does not require it',service:'healthcare scheduling support',serviceHref:'/services/healthcare-scheduling-support',takeaways:['Map each data field to a scheduling purpose.','Keep clinical judgment and urgent triage outside the administrative role.','Test denied views and escalation language before live handling.']},
 {slug:'customer-complaint-response-ownership-study',title:'Customer complaint responses: an ownership and evidence study',excerpt:'A decision framework for separating intake, acknowledgement, investigation, remedy approval, response, and follow-up in an offshore support workflow.',question:'Which complaint-handling steps can a customer-success assistant complete, and where must a named client owner investigate or approve the response?',decision:'whether to delegate intake and follow-up while retaining findings, contract decisions, credits, regulatory responses, or sensitive communications',unit:'one complaint from receipt through acknowledgement, classification, evidence collection, owner decision, customer response, promised follow-up, and closure',fields:'received time, channel, product or service, customer statement, requested outcome, severity cue, owner, evidence request, acknowledgement, finding, remedy approval, response, due promise, and closure basis',groups:'routine and sensitive complaints, complete and incomplete records, acknowledged and overdue cases, approved and unapproved remedies, and resolved and reopened complaints',control:'a stage-and-owner matrix with preserved customer language, due times, approval boundaries, response evidence, open-promise tracking, and a reopen path',failure:'one queue status is treated as ownership even though no person is accountable for the investigation, decision, customer response, and promised follow-up',service:'customer retention support',serviceHref:'/services/customer-retention-support',takeaways:['Separate acknowledgement from investigation and remedy authority.','Name an owner and due time for every stage.','Close only when the response and open promises are recorded.']},
];

export function makeDecisionResearch(t:DecisionResearchTopic):ResearchPost{
 const paragraphs=[
  `This report asks: ${t.question} The buying decision is ${t.decision}. That is narrower than asking whether an offshore team can “handle” the category. A usable scope describes the action, the information available at that moment, the conditions that stop work, and the person who owns the next decision. Buyers should agree on those boundaries before pricing seats or training agents, because a staffing plan cannot repair an undefined authority model.`,
  `The unit of analysis is ${t.unit}. Monthly averages and provider presentations are not substitutes for this unit: they can conceal a weak verification, a late transfer, or an unsupported customer promise. The minimum evidence fields are ${t.fields}. Record an unavailable value as missing. A later note should not be treated as proof that a required check, notice, approval, or acknowledgement happened earlier.`,
  `The comparison should separate ${t.groups}. Define the groups, eligibility rules, evidence window, and exclusions before reading outcomes. Include ordinary cases and credible edge cases, because a workflow that succeeds only when every input is complete is not ready for customer use. Where live testing could affect a customer, use a controlled non-production scenario or a carefully selected historical record instead.`,
  `The baseline failure mode is that ${t.failure}. The relevant fact is not that a policy or training slide exists. Reviewers need to see the triggering condition change the next recorded action. Evidence should connect the source event, the permitted response, any stop, the receiving owner, and the customer-facing result. Retrospective checklist completion cannot replace time-stamped evidence from the systems where the work occurred.`,
  `A bounded pilot uses ${t.control}. Run it in one named queue for a fixed period. Set success conditions, safety stops, sample rules, and owners in advance. Include several seeded edge cases when that can be done safely. Compare the same fields across cases and inspect contrary results rather than reporting only a completion average. If the control transfers work elsewhere, the delay and workload created downstream are part of the result.`,
  `Facts in this study are limited to source records and the public materials cited below. Analysis connects those facts to a buyer decision. The main operational inference is that a narrow, observable authority boundary is easier to supervise than broad discretion. That remains an inference until the buyer tests the relevant systems, channels, hours, customer mix, and exception volume. No cited source proves a provider’s performance, worker intent, legal compliance, or universal benchmark.`,
  `For Philippines-based delivery, privacy and accountability need to become specific work instructions. Identify the authoritative system, necessary fields, approved note location, retention owner, and route for requests outside the role. Do not copy sensitive data into chat, spreadsheets, personal notes, or a second ticket merely to make a handoff convenient. The Philippine Data Privacy Act and National Privacy Commission materials supply context; qualified advisers should assess the buyer’s actual jurisdictions and processing arrangement.`,
  `Quality review should score the decision path as well as the final disposition. A correct-looking result may follow an unsupported action, while a stop or escalation may be the safest successful outcome. Draw a stratified sample, have a second reviewer independently classify ambiguous cases, calculate agreement, and reconcile definitions before coaching. Do not turn reviewer disagreement into an agent defect until the instruction and evidence boundary are clear.`,
  `Implementation starts with a written role brief, examples of permitted and prohibited actions, test credentials, and a named escalation owner. Supervisors need a current view of stops, overdue acknowledgements, and unresolved customer promises. Frontline staff need plain language for explaining the next step without inventing an answer or guaranteeing an outcome. A change to policy, system configuration, channel, staffing, or risk level should trigger a targeted retest.`,
  `Record the buyer decision as approve, approve with conditions, redesign, or retain with the client. Attach the sample dates, tested configuration, exceptions, unresolved questions, owner, and retest date. A positive pilot supports only that scope. Expansion to another product, channel, geography, system, or authority level requires a new boundary review. A failed pilot is useful when it identifies the exact instruction, access, capacity, handoff, or record that must change.`,
  `Limitations are material. Logs may omit calls, manual work, failed integrations, or activity in third-party tools. Small samples expose control defects but do not estimate rare-event frequency reliably. Reviewers may interpret incomplete notes differently. Regulations and platform behavior can change. Customer outcomes may also depend on product, fulfillment, clinical, financial, security, or policy decisions outside the support team. Put these limits next to each conclusion.`,
  `For a sourcing discussion, ask the provider to demonstrate representative cases in a non-production environment where possible. Confirm what the frontline role can see and change, how exceptions reach the client, how receipt is captured, and what evidence remains after closure. Connect the demonstration to ${t.service} instead of a generic outsourcing claim. The output should be a launch condition and review routine, not a promise that future cases will match the sample.`,
  `Source quality needs its own boundary. The official publications below explain requirements, risks, or process concepts; they contain no measurement of this buyer’s queue and do not endorse this operating design. Record each title, publisher, URL, and checked date. Preserve the interpretation used if a source changes, then review the affected control. Marketing claims, unsourced benchmarks, and search snippets should never be promoted into facts because they agree with a preferred conclusion.`,
  `Governance continues after launch. Assign a client policy owner, a delivery owner for daily execution, a privacy or security contact where protected information is involved, and a receiving owner for exceptions. Decide which changes need prior approval. Review open exceptions, missing evidence, overdue receipts, and repeated stops at a fixed cadence. Trends show where to investigate, but record review is still required before attributing a problem to staffing, training, technology, or conduct.`,
  `Commercial comparison should use the same evidence boundary. Ask what the stated service includes, which systems and licenses the buyer supplies, how backup coverage works, and who performs escalated or reworked tasks. Give competing providers the same scenarios instead of accepting demonstrations each seller chooses. Price, staffing ratios, and relevant experience matter, but none proves the team can follow the exact access, authority, handoff, and review design the buyer plans to operate.`,
  `The practical conclusion is conditional. Approve the workflow only if the tested records show that the intended role completes permitted work, stops where required, transfers exceptions to a real owner, and leaves enough evidence for an independent reviewer. Redesign when missing fields or ambiguous rules make that conclusion impossible. Retain the decision with the client when its consequence exceeds the role’s written authority, even if a faster frontline answer would appear more convenient.`,
 ];
 const headings=['Decision and scope','Unit and evidence fields','Comparison design','Failure mode to test','Controlled pilot','Facts, analysis, and inference','Philippines privacy context','Quality review','Operating design','Decision rule','Limitations','Buyer application','Source evaluation','Ongoing governance','Commercial comparison','Conditional conclusion'];
 return {slug:t.slug,title:t.title,excerpt:t.excerpt,hero:'/offshore-call-center-agent.jpg',published:'2026-09-22',modified:'2026-09-22',revision:`2026-09-22-${t.slug}-v1`,readingMinutes:12,wordCount:paragraphs.join(' ').split(/\s+/).length,methodology:`A bounded source-record study of ${t.unit}. Eligibility, comparison groups, required fields, exclusions, reviewer disagreement, success conditions, and stop conditions are defined before outcome review. Official public sources were checked on September 22, 2026.`,limitations:'The method depends on complete operational records and a stable tested workflow. It cannot establish legal compliance, causation, provider-wide performance, employee intent, or results outside the stated sample.',keyTakeaways:t.takeaways,stats:[],sections:headings.map((heading,i)=>({heading,paragraphs:[{text:paragraphs[i],citations:i===6?[6,7]:i===7?[8]:i===12?[1,2,3,4,5,6,7,8]:t.slug.includes('account-recovery')?[1,6]:t.slug.includes('incident')?[2,6]:t.slug.includes('ecommerce')?[3,6]:t.slug.includes('healthcare')?[4,6]:[5,6]}]})),table:{caption:'Evidence boundary for the buyer decision',headers:['Evidence','Supports','Does not prove','Buyer action'],rows:[[t.fields.split(',')[0],'A recorded event','A complete workflow','Inspect the source record'],['Accepted escalation','Named receipt','A correct decision','Trace the downstream result'],['Pilot comparison','A bounded difference','Universal performance','Retest before expansion']]},buyerChecklist:['Define the customer outcome and retained client decisions.','Name the unit, sample period, eligibility rules, and exclusions.','Test routine, ambiguous, denied, and exception cases.','Preserve missing data and reviewer disagreement.','Record a launch decision, conditions, owner, and retest date.'],faqs:[{q:'Does a successful pilot prove the provider will always perform?',a:'No. It supports only the tested workflow, sample, systems, dates, and conditions. Continue monitoring and retest material changes.'},{q:'Is this report legal advice?',a:'No. It is an operational research framework. Obtain qualified advice for the jurisdictions, data, channels, and contractual arrangement involved.'}],related:[{title:`Explore ${t.service}`,href:t.serviceHref},{title:'Research library',href:'/research'}],contextualService:{heading:`Apply the evidence to ${t.service}`,text:'Turn the tested boundary, exception owner, and review fields into a scoped queue plan.',href:t.serviceHref,label:`Explore ${t.service}`},sources};
}

export const september22ResearchBatch:readonly ResearchPost[]=topics.map(makeDecisionResearch);
