import type {ResearchPost} from './fleet-data';
import {makeDecisionResearch,type DecisionResearchTopic} from './research-sep22';

const topics:readonly DecisionResearchTopic[]=[
 {slug:'call-center-customer-vulnerability-support-boundary-study',title:'Customer vulnerability in call centers: a support-boundary study',excerpt:'A buyer framework for recognizing requests for added support without diagnosing customers, recording unnecessary sensitive detail, or granting unapproved remedies.',question:'Can a Philippines-based support queue respond safely when a customer signals vulnerability without turning a service conversation into diagnosis or an unsupported commercial decision?',decision:'which preference capture, communication adjustment, pause, and escalation steps may be delegated and which health, capacity, eligibility, credit, and legal judgments remain with authorized owners',unit:'one customer contact in which a need for additional support is stated or observed, from recognition through consent, adjustment, escalation, follow-up, and record review',fields:'customer words, requested adjustment, consent to record, minimum operational note, channel, immediate safety cue, permitted response, escalation owner, receipt, due point, outcome, and retention review',groups:'customer-requested and agent-offered adjustments, temporary and continuing needs, routine and urgent contacts, accepted and declined support, and completed and unacknowledged escalations',control:'plain-language recognition cues, a no-diagnosis rule, minimum-note fields, customer choice, a safety route, named decision owners, receipt evidence, and restricted record access',failure:'an agent infers a condition, writes a detailed sensitive label, or promises a financial or policy exception merely because a customer sounds distressed',service:'inbound customer care',serviceHref:'/services/inbound-customer-care',takeaways:['Record the support needed, not an inferred diagnosis.','Give customers a choice about reasonable communication adjustments.','Route safety and remedy decisions to named authorized owners.']},
 {slug:'ecommerce-subscription-cancellation-proof-study',title:'Subscription cancellation support: an instruction-and-proof study',excerpt:'A source-record method for testing whether ecommerce support can capture, execute, and evidence cancellation instructions without adding friction or inventing retention authority.',question:'Can an offshore ecommerce queue complete an approved subscription cancellation accurately while preserving the customer instruction, effective date, billing boundary, and confirmation?',decision:'which authenticated cancellation steps may be delegated and which refund, dispute, contract interpretation, save-offer, and exception decisions remain with the merchant',unit:'one cancellation request from receipt and verification through instruction capture, system action, confirmation, billing reconciliation, and any exception handoff',fields:'request time, channel, verified account, customer instruction, subscription identifier, effective-date source, system action, result, confirmation route, billing event, exception owner, receipt, and final state',groups:'immediate and end-of-term requests, completed and failed actions, pre-bill and post-bill contacts, accepted and declined retention offers, and standard and disputed cases',control:'an unambiguous cancellation path, least-data verification, verbatim instruction field, prohibited dark-pattern steps, action receipt, billing check, and merchant-owned exception route',failure:'the queue treats an attempt to retain the customer as permission to delay cancellation, alter the requested date, or promise a refund it cannot authorize',service:'ecommerce contact center support',serviceHref:'/services/ecommerce-contact-center',takeaways:['Preserve the customer’s cancellation instruction and requested timing.','Separate system execution from refund and dispute authority.','Use confirmation and billing reconciliation as completion evidence.']},
 {slug:'technical-support-remote-access-consent-study',title:'Remote support access: a consent-and-session-control study',excerpt:'A practical evaluation of consent, visible scope, privileged actions, session termination, and evidence when a help desk uses remote-support tools.',question:'Can a technical support agent use approved remote access without expanding a troubleshooting session into silent surveillance or uncontrolled privileged work?',decision:'which consented diagnostic actions may occur in a remote session and which credential, administrator, security, financial, and destructive actions require a separate owner or approval',unit:'one remote-support session from tool invitation and customer consent through connection, action log, privilege boundary, disconnect, customer summary, and record retention',fields:'case identifier, approved tool, invitation source, consent event, connected identity, device, visible action, privilege request, file transfer, pause, disconnect time, summary, and exception owner',groups:'attended and unattended sessions, standard and privileged accounts, diagnostic and change actions, successful and interrupted sessions, and sessions with and without file transfer',control:'an approved-tool allowlist, per-session consent, visible action narration, privilege stops, transfer restrictions, automatic timeout, customer disconnect control, and immutable session evidence',failure:'a useful diagnostic connection remains open, gains broad privilege, transfers unnecessary files, or performs changes the customer and client never approved',service:'technical help desk support',serviceHref:'/services/technical-help-desk',takeaways:['Make consent specific to the session and visible task.','Stop before privileged or destructive actions outside the approved scope.','Prove disconnection, actions taken, and files transferred.']},
 {slug:'call-center-knowledge-article-retirement-study',title:'Knowledge article retirement: a stale-guidance containment study',excerpt:'A governance study for detecting, withdrawing, and replacing obsolete support guidance before it creates inconsistent customer promises.',question:'Can a distributed support operation retire obsolete knowledge fast enough that cached links, copied scripts, bookmarks, and queued cases do not keep the old instruction alive?',decision:'which withdrawal, replacement-link, queue-notice, and case-review steps the delivery team may perform and which policy interpretation and customer remediation decisions stay with the client',unit:'one material knowledge change from owner approval through publication, old-version withdrawal, frontline acknowledgement, affected-case search, correction, and monitoring',fields:'article identifier, old and new version, policy owner, effective time, affected queues, withdrawal event, redirect, cached copy location, acknowledgement, affected case, correction owner, and closure',groups:'scheduled and urgent changes, active and bookmarked content, acknowledged and unacknowledged users, affected and unaffected cases, and corrected and unresolved customer statements',control:'versioned articles, one canonical location, owner approval, effective-time notice, retirement redirect, cache search, targeted acknowledgement, and affected-case reconciliation',failure:'publishing a new article is mistaken for retirement while the old URL, pasted macro, local file, or open case continues to direct frontline work',service:'back-office support',serviceHref:'/services/back-office-support',takeaways:['Treat withdrawal as a separate control from publishing the replacement.','Search the places where agents actually retrieve and copy guidance.','Reconcile customer cases touched by materially wrong instructions.']},
 {slug:'offshore-call-center-demand-spike-triage-study',title:'Contact center demand spikes: a queue-triage evidence study',excerpt:'A decision framework for reducing work safely during an unexpected demand spike while protecting urgent contacts, customer promises, and deferred-case ownership.',question:'Can an offshore contact center simplify service during an unexpected spike without hiding abandonment, losing deferred work, or allowing urgency judgments beyond the frontline role?',decision:'which messages, intake fields, callback offers, routing changes, and temporary service levels may be activated and which safety, eligibility, staffing, and policy decisions remain with accountable owners',unit:'one demand-spike interval from trigger detection through triage-mode activation, customer treatment, deferred-work ownership, recovery threshold, reconciliation, and review',fields:'queue, timezone, trigger metric, cause confidence, approved mode, message version, contact class, urgency cue, callback choice, deferred owner, due point, recovery event, and final outcome',groups:'forecast and unforecast spikes, urgent and routine contacts, answered, abandoned, and deferred work, completed and missed callbacks, and normal and triage-mode intervals',control:'a preapproved trigger matrix, customer-visible notice, narrow urgency cues, callback consent, protected-contact route, deferred-work ledger, recovery owner, and post-event reconciliation',failure:'leaders optimize the live answer rate by closing channels or shortening calls while unmeasured customers, promises, and callbacks accumulate outside an owned queue',service:'workforce management support',serviceHref:'/services/workforce-management',takeaways:['Choose triage actions before pressure makes the decision.','Keep deferred work visible with an owner and due point.','Judge recovery by customer obligations, not only queue metrics.']},
];

const analysis:Record<string,{heading:string;text:string}[]>={
 'call-center-customer-vulnerability-support-boundary-study':[
  {heading:'Recognize a service need without naming a condition',text:'A frontline cue should describe the interaction, not diagnose the person. A customer may ask for slower speech, written confirmation, a trusted-person route, more time, or a different channel. The agent can acknowledge that request and check an approved adjustment. Tone, age, accent, confusion, or emotion alone should not become a vulnerability label. When an immediate safety statement appears, the agent follows the client’s emergency route and does not attempt counselling. Review should compare the customer’s own words with the operational note and remove unsupported interpretation.'},
  {heading:'Make customer choice operational',text:'Offering help is useful only when the customer can accept, decline, or change it without losing ordinary service. Scripts should explain what adjustment is available, what information would be recorded, who may see it, and whether the preference applies beyond the current contact. A representative should not pressure a customer to disclose a cause. If the requested adjustment is unavailable, the record needs a named owner and a truthful next step. The queue should preserve the original request instead of translating it into a convenient but different option.'},
  {heading:'Limit the record to the next service action',text:'A useful note might say “customer requests email confirmation after calls” or “allow additional response time.” It rarely needs a speculative medical, financial, family, or cognitive narrative. Access should follow the people who must deliver the adjustment, and retention should be reviewed when the need ends. Free-text copying across tickets increases exposure and makes corrections difficult. Buyers should test whether a preference travels to the channel where it matters while unrelated staff and exports remain unable to reveal sensitive context.'},
  {heading:'Separate support from remedy authority',text:'Communication changes do not automatically authorize fee waivers, refunds, contract changes, credit, account delegation, or identity exceptions. Those decisions require the normal evidence and owner. The agent can preserve the customer’s request and explain the review path without predicting approval. A vulnerability cue must never become a shortcut around authentication, nor should failed authentication erase a legitimate request for accessible communication. The two paths can proceed in parallel with different permissions and records.'},
  {heading:'Test refusal, correction, and urgent cases',text:'The pilot should include a customer who declines an offered adjustment, corrects an inaccurate note, uses a representative, changes channel, cannot complete the normal process, requests an unauthorized remedy, and makes a possible safety statement. Review customer choice, minimum recording, receipt by the right owner, and fulfilled follow-up. Count unsupported labels and excess sensitive detail as defects even if the contact closes quickly. A low escalation rate is not inherently better because safe recognition may increase correct referrals.'},
  {heading:'Vulnerability-support conclusion',text:'The defensible scope is a respectful service adjustment tied to the customer’s stated need, minimal evidence, and a defined owner. Diagnosis, capacity judgments, commercial remedies, legal conclusions, and emergency assessment stay outside the general support role. Buyers should observe both routine and uncomfortable cases, inspect who can retrieve the note, and test correction and deletion. Launch is conditional on customer choice remaining real and on escalation producing receipt rather than an unowned sensitive label.'},
 ],
 'ecommerce-subscription-cancellation-proof-study':[
  {heading:'Capture the instruction before offering alternatives',text:'The record should first preserve that the customer wants cancellation, the subscription concerned, and any stated timing. A permitted retention offer must not replace or obscure that instruction. If the customer declines the offer, execution continues without another loop. Agents should not invent a reason requirement when the system or policy does not need one. The buyer can replay test contacts to see whether the cancellation intent survives paraphrase, transfers, and channel switches and whether a save script adds measurable delay.'},
  {heading:'Anchor timing to an authoritative rule',text:'“Cancel now” can affect access, renewal, fulfillment, and billing differently. The representative should read the effective date and consequences from the approved subscription record and current policy, then state them plainly. When the account displays conflicting renewal dates or a charge is already pending, the case moves to the merchant’s exception owner. Frontline staff should not calculate prorated refunds or promise that a processor event will disappear. Preserve the timestamp used for the action so later review can distinguish instruction delay from payment processing.'},
  {heading:'Treat system action and confirmation as separate events',text:'Clicking a cancellation control is not enough. Evidence should show the targeted subscription, requested scope, resulting status, effective date, confirmation destination, and any failure message. Confirmation must avoid exposing account detail in a notification preview and should give the customer a safe route to report an error. If the platform times out, the agent checks current state before retrying so one request does not create conflicting events. A screenshot can supplement but should not replace structured system evidence.'},
  {heading:'Reconcile billing without granting hidden authority',text:'A charge after the request may reflect cutoff timing, failed execution, a different subscription, or a genuine error. The support queue can assemble the cancellation event and billing reference, but refund, dispute, and contract decisions remain with authorized owners. The handoff needs receipt and a customer-facing due point. Closing the cancellation ticket while the billing exception disappears into another queue is not completion. Sample linked records until the final state and any promised response agree.'},
  {heading:'Test the paths most likely to create friction',text:'Scenarios should include multiple subscriptions, end-of-trial timing, a pending shipment, an already posted renewal, failed authentication, system outage, an accepted save offer, a declined offer, and a customer returning after no confirmation. Measure instruction-to-action time, repeat prompts, incorrect scope, failed confirmation, unsupported refund statements, and unresolved billing links. Avoid treating retention rate as a support-quality result; it can reward friction unless customer choice and eventual execution are reviewed.'},
  {heading:'Cancellation conclusion',text:'Delegation is supportable when an authenticated instruction maps to a clear system action and durable confirmation without unnecessary obstacles. The merchant retains policy interpretation, disputed charges, refunds, and exceptions. Buyers should inspect the exact interface, permission, timestamp, message, and billing relationship before launch. A cancellation process is not complete because the agent used the correct script; it is complete when the requested subscription reaches the evidenced state and linked exceptions have accountable owners.'},
 ],
 'technical-support-remote-access-consent-study':[
  {heading:'Use an invitation the customer can authenticate',text:'The session should start from a case-linked invitation generated by an approved tool, not a search result, personal link, or unsolicited request to install software. The customer needs the agent identity or case reference, the purpose, expected visibility, and a way to stop. Agents should warn against sharing passwords and should never ask the customer to disable security broadly. Test look-alike links and wrong-case invitations because a correct remote-support product does not prevent social-engineering misuse.'},
  {heading:'Make consent granular and reversible',text:'Consent to view a screen is not blanket permission to control it, browse unrelated files, transfer data, install software, or use administrator rights. The workflow should surface a new explanation and approval when the action class changes. Customers need a visible disconnect control, and the agent must stop when consent is withdrawn. When communication drops, the safest default is to pause or terminate rather than continue silently. Record consent events as system evidence instead of relying only on a closing note.'},
  {heading:'Bound privilege and credential handling',text:'Customers should enter their own passwords into protected prompts where feasible; credentials do not belong in chat, tickets, recordings, or clipboard logs. A privilege request needs an approved reason and may require a client-side owner. The frontline role should stop before security-control changes, account administration, destructive commands, payment activity, or access to another user’s data unless explicitly authorized. Tool permissions and operating-system permissions both matter, so a restricted agent profile can still be unsafe on an overprivileged customer session.'},
  {heading:'Account for files and persistent components',text:'Remote tools may support clipboard sharing, file transfer, recording, unattended agents, or diagnostic collection. Each capability needs a purpose, default state, storage location, access owner, and deletion rule. A diagnostic bundle should be reviewed for personal or secret data before upload. Temporary installers and unattended components should be removed when the approved workflow requires it. The closure record should identify what moved, where it was stored, and whether the customer received a summary.'},
  {heading:'Prove termination and review anomalous sessions',text:'The session log should include connection and disconnection times, agent identity, device or case reference, privilege changes, transfers, and tool result. Automatic timeout limits abandoned connections, but supervisors also need alerts for unusually long sessions, repeated reconnects, off-hours access, or sessions without a linked case. Review should inspect the action sequence, not merely duration. A long session may be justified; a short unauthorized command may be severe. Preserve uncertainty if tool logging cannot show a specific action.'},
  {heading:'Remote-access conclusion',text:'Remote support is defensible only as a specific, observable, customer-controlled session. The approved tool, authenticated invitation, reversible consent, permission boundary, file rules, timeout, and evidence should work together. Buyers should conduct attended tests that include withdrawal, privilege refusal, interrupted communication, and incorrect invitations. Launch should pause when the tool cannot prove termination or when the delivery role can silently establish persistent access beyond the stated task.'},
 ],
 'call-center-knowledge-article-retirement-study':[
  {heading:'Define the authoritative version and effective moment',text:'A knowledge system needs one canonical article identifier, current version, policy owner, approval event, and effective time. Titles alone are weak because duplicates and translations can share names. A future-dated change should not silently replace guidance early, and an urgent correction should not wait for a normal release window. The notice must explain which decision changes and which queues are affected. Reviewers should be able to reconstruct what guidance was valid when a customer answer occurred.'},
  {heading:'Withdraw old routes, not just edit the index',text:'Agents may reach content through bookmarks, search results, direct URLs, macros, copied documents, onboarding packets, or open browser tabs. Retirement should make the old route visibly obsolete and point to the replacement without preserving actionable old text. Search indexes and macro libraries need explicit refresh. A redirect can help, but it must not merge distinct policies or conceal the prior version needed for audit. Inventory each retrieval path and verify it after the effective time.'},
  {heading:'Make acknowledgement proportional to consequence',text:'Minor wording corrections may need no interruption, while a change to eligibility, safety, payment, identity, or customer promise may require targeted acknowledgement before more work. The event should identify the person, version, and time rather than count an opened email as comprehension. A short scenario can test the changed decision. Staff who are off shift need a route on return, and supervisors need a view of remaining users without exposing the report as a performance score.'},
  {heading:'Find customer cases touched by obsolete guidance',text:'For material corrections, search the affected period, queues, dispositions, macros, and article references. The goal is not to reread every case but to define a defensible cohort and sample uncertainty. Each likely affected customer promise needs an owner who decides whether correction or remediation is required. The offshore team may assemble records and deliver approved notices; policy and remedy decisions stay with the client. Record exclusions so a narrow search is not later described as complete.'},
  {heading:'Test caches, partial outages, and local workarounds',text:'A retirement exercise should include a direct old URL, a stale search result, a pasted macro, an offline file, an agent returning from leave, and a knowledge platform outage. Observe whether the old guidance remains actionable and whether the replacement can be authenticated. Telling staff never to save material locally is insufficient if the live tool is unreliable. Provide a controlled continuity route whose owner and expiry are explicit, then inspect and remove obsolete copies after recovery.'},
  {heading:'Knowledge-retirement conclusion',text:'A replacement is operationally complete only when obsolete instructions stop directing work and affected cases have been considered. Buyers should verify canonical versioning, effective-time handling, retrieval paths, consequence-based acknowledgement, and customer reconciliation. Publication counts and article freshness scores cannot establish this. The launch condition is a repeatable withdrawal mechanism with policy ownership and evidence that frontline users encounter the right instruction at the decision point.'},
 ],
 'offshore-call-center-demand-spike-triage-study':[
  {heading:'Trigger triage from several observable signals',text:'A single average speed metric can be noisy or delayed. The activation rule should combine offered demand, oldest work, abandonment, staffing availability, channel backlog, and known incident context for a defined interval. The person authorized to enter triage mode should record the reason and selected playbook. Forecast variance is evidence of pressure, not proof of its cause. Avoid waiting for a perfect diagnosis when the queue needs a reversible response, but do not label a product incident, routing fault, or channel outage as simple understaffing.'},
  {heading:'Reduce scope explicitly and tell customers',text:'Triage might prioritize urgent contacts, offer callbacks, pause low-value outbound work, shorten optional surveys, or move administrative tasks. Each action needs a preapproved boundary and customer-facing message. Agents should not rush authentication, omit required disclosures, close unresolved cases, or promise shorter response times merely to improve dashboards. If a channel is limited, publish what remains available and how existing customers will be handled. Different queues may need different modes because urgency and downstream harm are not interchangeable.'},
  {heading:'Use narrow urgency cues with a protected route',text:'Frontline representatives can recognize defined words or conditions and route them; they should not diagnose medical, safety, fraud, or legal severity. The playbook should say what to capture, what not to ask, and who receives the contact at each staffed hour. Test false positives and ambiguous messages. An urgent label without receiving capacity only rearranges a backlog, so receipt and fallback coverage matter. Preserve the customer’s own description and distinguish it from the operational category applied by the queue.'},
  {heading:'Make callbacks and deferred work real inventory',text:'A callback offer needs customer consent, a verified route, a bounded window from an approved source, queue ownership, attempt rules, and a way to cancel or update the request. Deferred emails and cases also need a timestamp and due point. Do not remove them from workload forecasts when they leave the live queue. During recovery, deduplicate repeat contacts and check whether another channel resolved the need before acting. The ledger should expose aged, unmatched, and missed commitments until an accountable outcome exists.'},
  {heading:'Choose recovery thresholds before the surge',text:'Leaving triage mode too early can create a second spike; leaving it active hides normal service indefinitely. Define recovery using backlog age, staffing stability, callback completion, incident state, and protected-contact coverage over a sustained period. A named owner declares recovery and restores paused work in an explicit order. Sample contacts from the beginning, peak, and recovery tail. Compare customer obligations and error signals as well as answer metrics, because a queue can look normal while old deferred work remains unresolved.'},
  {heading:'Demand-spike conclusion',text:'The safe objective is not maximum contacts per hour. It is preserving urgent access and truthful communication while converting lower-priority demand into visible owned work. Buyers should tabletop multiple causes, channels, time zones, and recovery collisions. Approve the model only if triggers are observable, scope changes are authorized, customers understand their options, and every deferred promise survives into reconciliation. Staffing changes should follow repeated reconciled evidence rather than one unexplained interval.'},
 ],
};

export const october2ResearchBatch:readonly ResearchPost[]=topics.map(topic=>{
 const post=makeDecisionResearch(topic);
 const bespoke=analysis[topic.slug].map(section=>({heading:section.heading,paragraphs:[{text:section.text,citations:[2,6,7]}]}));
 const sections=[...post.sections.slice(0,5),...bespoke,post.sections[10],post.sections[12]];
 return {...post,published:'2026-10-02',modified:'2026-10-02',revision:`2026-10-02-${topic.slug}-v1`,sections,wordCount:sections.flatMap(s=>s.paragraphs).map(p=>p.text).join(' ').split(/\s+/).length,sources:post.sources.map(source=>({...source,note:source.note.replaceAll('September 22, 2026','October 2, 2026')})),methodology:post.methodology.replaceAll('September 22, 2026','October 2, 2026')};
});
