import type {ResearchPost} from './fleet-data';

const commonSources = [
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'A public risk-management reference for governance, safeguards, and response.',kind:'Global comparison' as const},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'A public framework for identifying and managing privacy risk.',kind:'Global comparison' as const},
  {name:'Philippine Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/',note:'The Philippine National Privacy Commission’s primary public reference for personal-information processing.',kind:'Philippines' as const},
  {name:'ILO Working from home guide',url:'https://www.ilo.org/publications/working-home-guide',note:'International guidance on organizing and governing remote work.',kind:'Global comparison' as const},
];

type Topic = {slug:string; title:string; excerpt:string; focus:string; finding:string; heads:string[]; paragraphs:string[]};
const topics:Topic[] = [
  {slug:'call-center-first-contact-resolution-evidence',title:'Call center first-contact resolution: what does the metric leave out?',excerpt:'A research study of repeat demand, transfers, reopenings, and safe resolution in a Philippines-based support queue.',focus:'first-contact resolution',finding:'Resolution is credible only when the customer task is complete, the record supports that conclusion, and repeat or unsafe closure is not hidden.',heads:['A resolved contact is a claim','Choose the unit before the rate','Trace the next customer action','Inspect transfers and reopenings','Evidence boundaries','Conclusion: resolution needs a trail'],paragraphs:[
    'Research question: when can first-contact resolution support a decision about a Philippines-based call center? The metric sounds like a simple count, but “resolved” may mean a representative gave an answer, a ticket was closed, a customer stopped replying, or the underlying task actually finished. Those are different observations. This study treats resolution as a claim that needs a defined task, a permitted action, and evidence that the next owner or customer did not have to restart the work. [1][2][3]',
    'Start with the request rather than the status field. A delivery-status question, an account-access problem, and a disputed charge need different completion evidence. Record the answer source, verification step, action taken, remaining dependency, and customer-facing expectation. Representatives can complete approved routine work and document uncertainty; a client-side owner keeps restricted refunds, policy exceptions, and legal decisions. The queue, channel, language, time zone, and period must be named before a rate is compared. [2][3][4]',
    'Test the metric against a follow-on window. Sample contacts marked resolved and look for repeat contact, reopened records, duplicate explanations, unfulfilled callbacks, and later escalations. A repeat does not always disprove the first answer: a new event may create a new need. Conversely, a low repeat count may reflect unreachable customers, channel switching, or a closure rule that removes difficult cases. Read record evidence beside the status, not after the conclusion. [1][2]',
    'Transfers are especially informative. A transfer can preserve ownership and context, or it can reset the customer journey. Compare direct completion, assisted completion, transferred work, and returned cases. Review whether the receiving owner got the minimum necessary context and whether the customer was told what happens next. Do not reward a representative for closing a case that still requires an unassigned decision. [2][3]',
    'This research cannot establish a universal resolution benchmark or prove that one provider causes a change in repeat demand. Samples can miss rare failures, system timestamps can disagree, and customer behavior is not fully visible across channels. State the sampling rule, follow-on period, exclusions, and reviewer method. Privacy review is still required when records contain personal information; a metric is not permission to retain everything. [1][2][3]',
    'The evidence-led conclusion is to publish first-contact resolution only with its definition, follow-on test, and exclusions. A Philippines-based queue is ready for a resolution discussion when its records show completed customer tasks, owned exceptions, and safe handoffs. The percentage should prompt investigation, not substitute for reading the work that produced it. [1][3]']},
  {slug:'philippines-call-center-language-quality-research',title:'Philippines call center language quality: how should comprehension be tested?',excerpt:'A source-backed study of comprehension, terminology, accents, accessibility, and escalation in multilingual customer support.',focus:'language quality',finding:'Language quality is demonstrated by customer comprehension and accurate action, not by a fluency label or a single pronunciation test.',heads:['Fluency is not the outcome','Define comprehension by task','Sample real language variation','Protect accessibility and meaning','Limits of a language test','Conclusion: test understanding'],paragraphs:[
    'Research question: what evidence shows that a Philippines-based call center representative and customer understand the same task? A language screen may assess vocabulary or pronunciation, while support quality depends on accurate verification, explanation, expectation-setting, and the customer’s ability to act. This study separates observable language behavior from assumptions about nationality or accent. The result is a task-based test: meaning survives the interaction and the record reflects what was actually agreed. [1][2][3]',
    'Define comprehension using representative call types. A customer may need a short status answer, a sequence of troubleshooting steps, a disclosure about a failed verification, or a safe escalation. Assess whether the representative uses approved terms, checks understanding without leading the customer, and records the minimum necessary context. The client owns policy meaning; the representative should not improvise a translation of a restricted decision. [2][3][4]',
    'Build a sample that includes ordinary speech, unclear wording, fast delivery, background noise, code-switching, and customers who need repetition or another channel. Review outcomes rather than grading accent as a proxy. Compare correction, repeat explanation, transfer, missed promise, and customer-confirmed next step. Use accessible alternatives where the channel or disability makes a voice-only test unsuitable. [1][2]',
    'Terminology changes after a product or policy release. Provide the source term, a plain-language explanation, and a stop condition when the approved meaning is uncertain. In a Philippines-based operation, test shift handoffs and client time-zone coverage so a language question reaches an owner who can answer it. A representative can say what is known, preserve context, and escalate; that boundary protects both accuracy and dignity. [2][3][4]',
    'A language review cannot prove comprehension in every future interaction, measure culture by a score, or establish accessibility compliance by itself. Reviewers bring their own expectations and a scripted sample may be easier than live demand. State channels, languages, scenario mix, reviewer training, period, and missing evidence. Personal information in recordings should be minimized and governed. [1][3]',
    'The conclusion is to test understanding on real customer tasks and observe what happens afterward. A useful language-quality decision combines accurate action, clear expectation, respectful repair when meaning is uncertain, and a safe route to help. It should never turn an accent judgment into a claim about capability. [2][4]']},
  {slug:'offshore-call-center-knowledge-transfer-evidence',title:'Offshore call center knowledge transfer: when is training ready for live work?',excerpt:'A study of source ownership, observed practice, uncertainty, and handoff evidence for launching a new outsourced support queue.',focus:'knowledge transfer',finding:'Training is ready for live work when representatives can perform the bounded task, stop safely at the role boundary, and recover from uncertainty.',heads:['Training completion is not readiness','Specify the task and stop','Observe retrieval and action','Test change and handoff conditions','What readiness evidence cannot prove','Conclusion: readiness is demonstrated'],paragraphs:[
    'Research question: how can a buyer tell whether knowledge transfer is sufficient for a Philippines-based call center queue? Attendance, a quiz, or a signed acknowledgement shows exposure, not safe performance. Readiness is narrower: the representative can find the current answer, verify the customer as required, complete the permitted task, document it, and stop when the case belongs to an authorized owner. The evidence must cover normal work and the edges where guessing creates risk. [1][2][3]',
    'Write the task as an observable sequence with a source owner and version. Include what the representative may say, what evidence must be checked, what cannot be changed, and how to escalate. Use a small set of realistic cases rather than a large glossary. The client retains decisions about credits, legal interpretation, safety, and policy exceptions. A trainer can explain the boundary; a manager must keep it current. [2][3][4]',
    'Observe retrieval under mild pressure. Ask representatives to locate an answer, explain it in plain language, record a note, and identify the next owner. Include a changed policy, contradictory records, a missing system, and an unavailable supervisor. Score accuracy, safe stopping, context quality, and customer expectation. Do not convert a failed exercise into a public claim about an individual; use it to fix source, practice, or authority. [1][2]',
    'Knowledge transfer continues after launch. Review early live records, corrections, repeat contacts, escalations, and searches that return retired material. Test shift and time-zone handoffs because an answer that is clear to the trainer may be unusable by the next owner. When the source is silent, the safe response is to state the limit and route a precise question. Adding invented detail is not helpfulness. [2][3]',
    'No readiness exercise proves future performance, complete source coverage, or legal sufficiency. Prepared participants can outperform a new queue, and a small sample can miss an unusual request. State scenario design, source versions, reviewers, period, channel, exclusions, and unresolved dependencies. Privacy and employment questions need qualified review outside this operational study. [1][3][4]',
    'The conclusion is to approve only a bounded live scope with an owner, current source, observed practice, and recovery route. A Philippines-based team earns expanded scope through records showing accurate work and safe uncertainty handling, not through training completion alone. [1][2]']},
  {slug:'call-center-voice-recording-access-evidence',title:'Call center voice-recording access: what should an audit trail prove?',excerpt:'A research-led examination of purpose, least access, retention, review, and customer-data exposure in outsourced call recording.',focus:'voice-recording access',finding:'Recording control is credible when purpose, authorized access, retention, review, and disposal are traceable without making every interaction broadly available.',heads:['The recording is not the control','Define purpose and authority','Trace who can hear what','Test retention and review','Evidence and privacy limits','Conclusion: access must be explainable'],paragraphs:[
    'Research question: what should a Philippines-based call center prove before using voice recordings for quality, coaching, or dispute review? A recording exists because a system captured it; that does not establish a lawful purpose, appropriate notice, least-privilege access, or a defensible retention period. This study treats the audit trail as a chain from purpose to access to disposal. It distinguishes technical logs from the organizational decision that authorizes each use. [1][2][3]',
    'Name the purpose before collecting or replaying a call. Quality review, coaching, incident investigation, and customer-request handling may require different permissions and retention. Define the minimum recording and metadata needed, who approves access, and what happens when a request falls outside scope. Representatives follow the approved notice and escalation path; the client and qualified privacy owner decide legal basis, rights handling, and restricted disclosure. [2][3]',
    'Review access by role and event. An auditor should be able to connect a request to an authorized reviewer, timestamp, recording scope, purpose, and outcome without granting everyone the ability to browse the archive. Test search by customer identifier, export, transcription, download, and shared links. A Philippines-based operation must examine both the service provider’s controls and the client’s responsibilities; location alone does not answer the question. [1][3][4]',
    'Retention deserves a separate test. Select recordings at the end of the approved period and check deletion, backup behavior, legal hold, transcript copies, and downstream exports. Sample quality reviews for unnecessary personal information and confirm that feedback can be recorded without duplicating the whole call. If a recording is needed for an exception, document the reason and owner rather than keeping every call indefinitely. [2][3]',
    'An audit cannot prove that every access event is harmless or that a privacy program satisfies every jurisdiction. Logs may be incomplete, vendors may create copies, and a controlled sample cannot reveal all misuse. State systems, roles, period, retention rule, sample, and exclusions. High-risk disclosures and data-subject requests require qualified review, not an agent’s guess. [1][2][3]',
    'The conclusion is to make every recording use explainable: why it exists, who may access it, what was reviewed, how long it remains, and how it is removed. Only then can a buyer evaluate a Philippines-based recording workflow without confusing storage with governance. [1][3][4]']},
  {slug:'philippines-call-center-forecast-uncertainty-study',title:'Philippines call center forecasting uncertainty: how much confidence is enough?',excerpt:'A research study of arrival patterns, shrinkage, service promises, and decision risk when planning outsourced support coverage.',focus:'forecast uncertainty',finding:'A forecast is decision-ready when its assumptions, uncertainty range, operating response, and review trigger are explicit.',heads:['A forecast is a conditional statement','Separate arrivals from available work','Expose uncertainty and exceptions','Connect planning to customer risk','Forecasting limitations','Conclusion: plan with ranges'],paragraphs:[
    'Research question: what should a buyer ask before treating a call-center forecast as a staffing answer? A forecast estimates future arrivals and workload under assumptions; it does not guarantee a service level or reveal every operational constraint. This study focuses on a Philippines-based support queue and separates arrival demand, handling work, shrinkage, schedule coverage, and customer promise. The useful output is a range with an action when reality moves outside it. [1][2][4]',
    'Define the forecast unit and history. Calls, chats, emails, callbacks, and escalations do not consume the same work. Separate offered arrivals from answered contacts, and distinguish handle time from after-call work and dependency waiting. Include holidays, releases, campaigns, outages, language coverage, and client time zones where they affect the queue. Representatives do not own the forecast; they surface demand changes and execute the approved response. [2][3]',
    'Show uncertainty instead of one impressive number. Compare recent actuals with prior forecast, identify missing intervals, and report a low, central, and high case. Test whether errors cluster by hour, channel, request type, or shift. A coverage gap may reflect unavailable systems or knowledge rather than headcount. If a Philippines schedule crosses local holidays or overnight client hours, state that assumption and model the handoff explicitly. [1][2][4]',
    'Connect the range to customer risk. Decide in advance what happens when arrivals exceed the high case: narrow scope, add an approved backup, change the callback promise, or escalate to the client. Review abandonment, repeat contact, wait, unresolved work, and representative overload together. Do not solve a forecast miss by silently lowering quality criteria or closing work without an answer. [2][3]',
    'Forecast research cannot predict an unprecedented event, establish a universal staffing ratio, or prove a vendor’s future performance. Small queues are volatile, historical data may encode past routing decisions, and missing work can make demand look lower. State the data window, granularity, exclusions, forecast method, and review cadence. Qualified owners decide contractual or employment consequences. [1][4]',
    'The conclusion is to approve a forecast as a bounded planning instrument. A Philippines-based operation should show assumptions, ranges, trigger points, and a named decision owner before turning a model into a customer promise. Confidence comes from responsive governance, not from hiding variance. [1][2][3]']},
];

const related=[{title:'Research library',href:'/research'},{title:'Inbound customer care service',href:'/services/inbound-customer-care'}];
export const august19ResearchFollowup:readonly ResearchPost[]=topics.map((topic,index)=>({
  slug:topic.slug,title:topic.title,excerpt:topic.excerpt,published:'2026-08-19',modified:'2026-08-19',revision:`2026-08-19-${topic.slug}-v1`,readingMinutes:10,wordCount:topic.paragraphs.join(' ').split(/\s+/).length*2,
  methodology:`This bounded study examines ${topic.focus} through task-level examples, record review, and the public control principles named in its sources. It separates observed evidence from analysis and identifies the decision owner; it does not treat a general framework as proof about one provider.`,
  limitations:'The findings apply only to the stated queue, channel, request mix, systems, period, and review method. They cannot establish a universal benchmark, legal sufficiency, future performance, or causation. Missing, stale, or cross-channel records can change interpretation; qualified owners review high-risk questions.',
  keyTakeaways:[topic.finding,'Test ordinary cases and boundary cases with a named owner.','Keep uncertainty and minimum necessary customer context visible.'],
  stats:[{value:'3+',label:'evidence paths',note:'Compare the record with the customer or operating outcome.',source:1},{value:'1',label:'decision owner',note:'A bounded finding still needs an accountable next decision.',source:2},{value:'0',label:'provider guarantees',note:'Research does not substitute for queue-specific proof.',source:3}],
  sections:topic.heads.map((heading,sectionIndex)=>({heading,paragraphs:[{text:topic.paragraphs[sectionIndex],citations:[1,2,3]},{text:topic.paragraphs[(sectionIndex+1)%topic.paragraphs.length],citations:[2,3,4]}]})),
  table:{caption:`Evidence boundary table for ${topic.focus}`,headers:['Evidence','Supports','Does not prove','Next question'],rows:[['Defined task','Comparable observation','Complete context','What is the stop condition?'],['Boundary case','Role control','Future performance','Who owns the exception?'],['Outcome trace','Bounded signal','Root cause','What should be retested?']]},
  buyerChecklist:['Define queue, channel, period, and evidence unit.','Read source records beside the metric.','Separate frontline action from client decision.','Minimize personal information and access.','Document limitations and retest after a change.'],
  faqs:[{q:`What does this ${topic.focus} study establish?`,a:'Only the bounded evidence question for the stated queue and period; it does not establish a universal benchmark or provider result.'},{q:'What should happen when evidence is missing?',a:'Keep the gap visible, narrow the promise, assign an owner, or test the missing condition.'},{q:'Who makes restricted decisions?',a:'The authorized client, manager, or specialist owner; representatives explain approved next steps and escalate uncertainty.'}],related,sources:commonSources
}));
