import type {ResearchPost} from './fleet-data';
const body=[
'Research question: what evidence shows that a Philippines call center adopted a knowledge change safely across shifts instead of merely publishing a new article? The date of this route-specific record is 2026-08-21. A changed answer has a source owner, effective date, exposure event, point of use, exception path, and retest. Adoption is not proved by a read receipt because a representative may see a notice without finding or applying the operative instruction.',
'Methodology and evidence scope: we compared governance and recovery concepts at https://www.nist.gov/cyberframework, privacy-risk practices at https://www.nist.gov/privacy-framework, Philippine privacy requirements at https://privacy.gov.ph/data-privacy-act/, and distributed-work context at https://www.ilo.org/global/topics/non-standard-employment/platform-work/lang--en/index.htm. We used a scenario review of version publication, shift briefing, search, answer, exception, correction, and later retest. The unit is one support case after a defined effective date. Facts are version IDs, timestamps, exposure records, observed answers, escalation, and corrections. Analysis distinguishes a source defect from a training or access defect.',
'A knowledge change begins with authority. The source owner should state what changed, why, effective date, affected request types, and what to do outside scope. Keep the prior version for audit while removing it from ordinary answer paths. A representative needs a clear signal at the point of work, not only a message in a general channel. If two articles disagree, the safe response is to pause the answer and escalate. A frontline role can apply approved content and record uncertainty; it should not resolve policy conflicts by improvising.',
'Shift coverage changes adoption evidence. A briefing attended by one team is not evidence for a later team. Record who received the change, through which channel, and when the new version became available. Sample first cases after the effective date and later cases after the change has had time to settle. Early uncertainty may reflect exposure or navigation; later errors may reveal an old template, search ranking, or unresolved exception. For a Philippines-based operation, compare day, evening, and overnight boundaries without turning one team into a claim about every team.',
'Point-of-use behavior is stronger evidence than publication. Ask the representative to locate the current source, explain the changed instruction, identify the effective date, and name the escalation path. Review actual notes for the version or article used. A correct answer with an obsolete source is still a control concern because the next case can diverge. A wrong answer from a current but ambiguous source is a content issue. This classification lets an owner fix search, wording, access, coaching, or policy rather than attributing every miss to memory.',
'Version adoption also has a privacy boundary. A new article may change which fields are collected, displayed, or retained. Review whether the change asks for more information than the support purpose requires and whether sensitive exceptions have a restricted path. The Philippine Data Privacy Act is external context, not a legal opinion about a particular operation. The operational test is narrower: the source should identify safe handling, role permissions, and the owner for questions outside the approved answer. Representatives should not copy unnecessary personal data into a knowledge example.',
'Analysis should compare cases by request type, shift, channel, version, source location, and escalation. Count corrections and repeat contacts only after defining them. A drop in corrections may mean safer adoption, fewer sampled cases, or easier requests. Read a stratified sample and preserve both the answer and the source identifier. Change one control, such as a point-of-use alert, a retired-template rule, or a short shift-specific exercise. Retest on comparable cases and report whether the evidence changed at the source, access, or behavior layer.',
'Limitations: this study cannot prove every representative saw a notice, that a source is legally sufficient, or that a correct answer caused a customer outcome. Scenario evidence is not a randomized training evaluation. Shift, channel, product, and request mix can change, while records can omit informal coaching. External governance and privacy frameworks provide questions, not a score for one Philippines call center. Findings apply only to the defined version, cases, period, and observable fields.',
'Evidence-led conclusion: safe knowledge adoption is supported when a Philippines call center can identify the authoritative version, effective date, exposure path, point-of-use behavior, exception owner, and retest evidence across shifts. Publication alone is not adoption. Managers should retain prior versions for audit but remove competing answers from normal work, then test one weak boundary. The conclusion should preserve whether the remaining problem is source quality, access, navigation, training, or authority instead of hiding it in a generic compliance rate.'
,'A version study should also inspect the first exception after publication. The representative may find a case that the new source does not cover, and that gap is evidence about scope rather than failure to memorize. Record the question, source searched, escalation owner, interim answer authority, and later correction. Keep the prior source unavailable for ordinary answering while retaining it for audit. For a distributed Philippines team, the effective date and shift handoff should be visible in the same place. This produces evidence about adoption and scope without inventing a provider-wide rate.'
,'A route-level knowledge study should preserve the customer’s request separately from the representative’s activity. Compare the authoritative version, effective date, exposure, source opened, answer, exception, and correction in sequence. If one field is absent, report the absence plainly and assign a repair. Do not infer adoption from publication, attendance, or a read receipt. The strongest evidence is specific enough for another reviewer to reproduce the finding, while the conclusion remains limited to the sampled shift, request type, version, and period.'
].join(' ');
const sources=[{name:'NIST CSF',url:'https://www.nist.gov/cyberframework',note:'Governance.',kind:'Global comparison' as const},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy.',kind:'Global comparison' as const},{name:'Philippine Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary law.',kind:'Philippines' as const},{name:'ILO platform work',url:'https://www.ilo.org/global/topics/non-standard-employment/platform-work/lang--en/index.htm',note:'Work context.',kind:'Global comparison' as const}];
export const august21KnowledgeVersion:readonly ResearchPost[]=[{slug:'philippines-call-center-knowledge-version-adoption-study',title:'Philippines call center knowledge versions: evidence of safe adoption across shifts',excerpt:'A bounded study of source authority, exposure, point-of-use behavior, and correction evidence.',hero:'/aug21-research-heroes/philippines-call-center-knowledge-change-adoption.png',published:'2026-08-21',modified:'2026-08-21',revision:'2026-08-21-philippines-call-center-knowledge-version-adoption-study-v1',readingMinutes:7,wordCount:body.split(/\s+/).length,methodology:'Scenario review of version adoption against four external sources.',limitations:'The study cannot prove universal exposure, legal sufficiency, or training causation.',keyTakeaways:['Publication is not adoption.','Version authority must be visible at point of use.','Shift boundaries need direct evidence.'],stats:[],sections:[{heading:'Research question, methodology, analysis, limitations, and conclusion',paragraphs:[{text:body,citations:[1,2,3,4]}]}],table:{caption:'Knowledge adoption evidence boundary',headers:['Observed evidence','Supports','Does not prove','Next test'],rows:[['Source identifier','Version use','Understanding everywhere','Sample the next shift']]},buyerChecklist:[],faqs:[{q:'Does a read receipt prove safe adoption?',a:'No. Point-of-use behavior and source-specific case evidence are needed.'}],related:[{title:'Research library',href:'/research'}],sources}];
