import type {ResearchPost} from './fleet-data';

const sources: ResearchPost['sources'] = [
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance, accountability, detection, response, and recovery concepts.',kind:'Global comparison'},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'Privacy-risk concepts for purpose, access, and data minimization.',kind:'Global comparison'},
  {name:'Philippine Data Privacy Act, Republic Act No. 10173',url:'https://lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html',note:'Primary Philippine statutory text for personal-information processing.',kind:'Philippines'},
  {name:'National Privacy Commission Philippines',url:'https://privacy.gov.ph/',note:'Philippine regulator resources for accountability and privacy questions.',kind:'Philippines'},
  {name:'ILO Working from home guide',url:'https://www.ilo.org/publications/working-home-guide',note:'Distributed-work organization and communication context.',kind:'Global comparison'},
];

const makePost = (slug:string,title:string,excerpt:string,question:string,unit:string,fields:string,comparison:string,decision:string,takeaways:string[]):ResearchPost => {
  const sections = [
    {heading:'Research question and evidence boundary',text:`Methodology for this route-specific research record, dated August 31, 2026: ${question} We treated ${unit} as the unit of analysis and compared simulated routine, ambiguous, transferred, and exception records with public governance, privacy, and distributed-work sources. Observed fields, operational interpretation, and decisions reserved to an authorized client owner were kept separate. The review uses no private customer records and makes no provider-wide performance claim. Public frameworks supply control questions; they do not certify one call center workflow.`},
    {heading:'Fields that make the event observable',text:`The record should preserve ${fields}. Each field must have an operational use. A timestamp without an owner shows activity but not accountability; a status without a definition cannot be compared; a note without an authority boundary may encourage the next representative to guess. Reviewers should reconstruct the sequence from the original request through the next accountable action. Missing evidence should remain visible rather than being converted into a favorable outcome code.`},
    {heading:'Cohort comparison and interpretation',text:`The bounded comparison is ${comparison}. Stratify by channel, shift, request type, source version, and whether client-side approval was required. Read representative records behind every category because an average can hide different failure modes. A delay caused by a cautious privacy stop is not equivalent to unowned work, and a quick closure does not prove that the customer received an accurate or complete next step. Differences identify questions for a controlled test; they do not establish causation.`},
    {heading:'Privacy, access, and authority',text:`Use the minimum customer context needed to examine the operating event. Limit source-record access to authorized reviewers and avoid copying unrelated personal information into calibration or reporting notes. The Philippine Data Privacy Act and National Privacy Commission materials are comparison sources, not legal conclusions for a particular organization. Sensitive disclosures, policy exceptions, account changes, remedies, and changes to retention or access remain with the designated client, privacy, security, or legal owner.`},
    {heading:'Decision use and next test',text:`The decision supported by this study is ${decision}. Select one repair, keep the definitions and sample frame stable, and repeat the comparison after the change. Preserve exclusions, uncertainty, and counterexamples. The manager should be able to explain which observation triggered the action, who owns it, when it will be reviewed, and what result would pause expansion. This connects research to a bounded operating decision without turning a descriptive pattern into a promise.`},
    {heading:'Limitations and evidence-led conclusion',text:`This scenario study cannot prove customer satisfaction, legal compliance, workforce capacity, provider quality, causation, or financial impact. Results depend on the selected period, queues, channels, record quality, and definitions. The evidence supports a narrow conclusion: ${takeaways[0].toLowerCase()} A buyer should validate the finding with its own records and authorized owners, then retest after a material instruction, access, staffing, routing, or system change.`},
  ];
  return {slug,title,excerpt,hero:'/offshore-call-center-agent.jpg',published:'2026-08-31',modified:'2026-08-31',revision:`2026-08-31-${slug}-v1`,readingMinutes:8,wordCount:sections.map(s=>s.text).join(' ').split(/\s+/).length,methodology:`A bounded scenario-record comparison using ${unit} as the unit of analysis and five public governance, privacy, and work-organization sources.`,limitations:'Scenario evidence and public frameworks cannot prove legal compliance, causation, customer satisfaction, provider-wide quality, capacity, or financial results.',keyTakeaways:takeaways,stats:[],sections:sections.map((s,i)=>({heading:s.heading,paragraphs:[{text:s.text,citations:i%2===0?[1,3,5]:[2,4]}]})),table:{caption:'Evidence-to-decision boundary',headers:['Observed evidence','Supports','Does not prove','Next test'],rows:[[fields.split(',')[0],'Traceable event','Successful outcome','Review an exception'],['Named owner and time','Sequence and accountability','Adequate capacity','Compare matched cohorts'],['Recorded boundary','Authorized next step','Legal compliance','Validate with the client owner']]},buyerChecklist:['Define the event and accountable owner.','Preserve the source, status, time, and next action.','Sample routine, ambiguous, transferred, and exception cases.','Record exclusions and uncertainty.','Change one control and repeat the comparison.'],faqs:[{q:`What does this research establish about ${title.toLowerCase()}?`,a:'It establishes a bounded evidence design and decision questions, not a universal benchmark or provider guarantee.'},{q:'Who owns decisions outside the documented workflow?',a:'The authorized client or specialist owner retains those decisions.'}],related:[{title:'Research library',href:'/research'},{title:'Call quality monitoring',href:'/services/call-quality-monitoring'}],sources};
};

export const august31ResearchBatch: readonly ResearchPost[] = [
  makePost('offshore-call-center-escalation-acceptance-latency-research','Offshore call center escalation acceptance latency: where does ownership pause?','A bounded study of sent, accepted, returned, and overdue escalations across offshore shifts.','What record evidence distinguishes escalation transmission from accepted ownership, and where does latency accumulate?','one escalation from frontline stop to receiving-owner action','request reason, sending owner, sent time, receiving owner, acceptance time, due point, dependency, return reason, and customer update','sent versus accepted escalations, accepted versus returned items, and same-shift versus cross-shift cases','whether an acknowledgement field, clearer receiving queue, or available decision window should be piloted',['Escalation timing becomes useful only when sent and accepted ownership are separate events.','Returned work needs a specific missing requirement.','Customer updates should not invent a resolution time.']),
  makePost('philippines-call-center-cross-shift-promise-survival-research','Philippines call center cross-shift promises: what survives the handoff?','Research on customer promises crossing Philippines shifts, client time zones, dependencies, and incoming-owner acceptance.','Which evidence shows that a customer promise remained actionable after a Philippines call center shift changed?','one customer promise crossing a defined shift boundary','original wording, customer-facing time zone, due point, outgoing action, unresolved dependency, incoming owner, acceptance state, and final update','promises completed within one shift versus those crossing shifts, with separate cohorts for available and unavailable approvers','whether the handoff field set or overlap review should change for one promise type',['A cross-shift promise survives only when its wording, due point, dependency, and next owner remain reconstructable.','Overlap attendance is not proof of accepted work.','Time-zone conventions must be explicit.']),
  makePost('call-center-knowledge-search-failure-patterns-research','Call center knowledge search failures: missing answer or broken path?','An evidence-led comparison of absent content, poor search labels, access limits, conflicting versions, and safe escalation.','How can a call center distinguish a missing knowledge answer from a search, access, version, or scope failure?','one support question and its complete knowledge-search path','customer question category, search terms, results shown, source version, access state, answer selected, stop reason, escalation owner, and later correction','successful searches versus no-result, conflicting-result, access-blocked, and out-of-scope searches','whether to change content, metadata, permissions, source hierarchy, or the representative stop rule',['A failed lookup is a family of observable conditions, not proof that an agent lacks knowledge.','The search path and source version must remain visible.','Safe escalation can be the correct outcome.']),
  makePost('offshore-call-center-callback-closure-validity-research','Offshore call center callback closure validity: attempt, contact, or completed promise?','A study separating callback attempts, customer contact, completed requests, changed promises, and justified closure.','What evidence makes a closed offshore call center callback record a credible customer outcome?','one callback promise from creation through closure','promise wording, permitted channel, time zone, attempt timestamps, connection result, work completed, changed expectation, closure reason, and accountable owner','attempted versus connected callbacks, connected versus completed requests, and closures with versus without customer confirmation','whether closure states, retry rules, or dependency ownership need a controlled revision',['A callback attempt, successful contact, and completed customer promise are different events.','Closure needs a reason tied to the original commitment.','Channel authority and retry limits belong in the evidence.']),
  makePost('call-center-quality-sample-coverage-bias-research','Call center quality sample coverage bias: which work remains unseen?','Research on exclusions, missing recordings, channel mix, specialist transfers, and the limits of a quality-review sample.','How can a call center identify coverage bias before interpreting a quality-review result?','one interaction eligible for a defined quality-review sample','queue, channel, shift, request type, eligibility rule, selection result, exclusion reason, recording availability, reviewer assignment, and scored criterion','included versus excluded work across queues, shifts, channels, exception types, and specialist transfers','whether sampling rules, recording coverage, reviewer access, or the stated conclusion should be narrowed',['A quality result is bounded by the work that could enter its sample.','Exclusions need reasons and owners.','A representative sample claim requires comparison with the eligible population.']),
];
