import { Header, Footer, CTA } from '../components';


const tiers = [
  { price: '$10/hour', name: 'Virtual & Executive Assistants', note: 'Good for clear, repeatable support work.', items: ['Calendar and inbox support', 'Research and document preparation', 'CRM, customer, and admin follow-up'] },
  { price: '$15/hour', name: 'Senior & Specialized Assistants', note: 'Good for experienced workflow ownership.', items: ['Cross-team coordination', 'Customer success or sales support', 'Exception tracking and reporting'] },
  { price: '$18/hour', name: 'C-Suite & Operations Support', note: 'Good for complex leadership support.', items: ['Executive operating rhythm', 'Project and process coordination', 'Leadership reporting support'] },
];
export const metadata = { title: 'Pricing', description: 'Public hourly pricing for Philippines-based virtual assistants, executive assistants, and operations support.' };
export default function Pricing() { return <><Header /><main><section className="page-hero"><div className="container page-hero-grid"><div><p className="cco-kicker"><span /> Clear hourly starting points</p><h1>Pick the level of support the work needs.</h1><p className="lead">Rates are for Philippines-based talent. Your final plan depends on role depth, schedule, tool access, and management responsibility.</p></div><div className="page-hero-art"><img src="/visuals/managed-team-comparison.svg" alt="Visual comparison of three virtual assistant support levels" /></div></div></section><section><div className="container pricing-grid-new">{tiers.map((tier, index) => <article className={`price-card-new ${index === 1 ? 'featured' : ''}`} key={tier.price}><p className="cco-kicker cco-dark"><span /> Tier {index + 1}</p><div className="price">{tier.price}</div><h2>{tier.name}</h2><p>{tier.note}</p><ul>{tier.items.map((item) => <li key={item}>{item}</li>)}</ul><a className="cco-btn cco-btn-primary" href="/contact-us">Scope this level <span>↗</span></a></article>)}</div></section><section className="cco-section"><div className="container cco-split"><div><p className="cco-kicker cco-dark"><span /> What changes the scope</p><h2>A rate only makes sense beside the role.</h2><p className="cco-section-lead">A calendar assistant and a multi-team operations coordinator do not carry the same judgment, risk, or onboarding load. Define the decisions and outputs before comparing prices.</p></div><img src="/visuals/quality-scorecard.svg" alt="Quality scorecard used to review outsourced assistant work" /></div></section><CTA /></main><Footer /></> }
